# Validiteit {#ch:validiteit}

## Inleiding

Experimenteel onderzoek heeft tot doel om hypotheses te toetsen. Ook in
ander, niet-experimenteel onderzoek kunnen hypotheses worden getoetst,
maar we beperken ons hier voor de helderheid tot experimenteel
onderzoek, d.w.z. onderzoek waarin het experiment als methode wordt
gebruikt. In experimenteel onderzoek wordt getracht causale verbanden
aannemelijk te maken. Als de resultaten van een experimenteel onderzoek
de onderzoekshypothese bevestigen (d.w.z. de nulhypothese wordt
verworpen), dan is het aannemelijk dat een verandering in de
onafhankelijke variabele de oorzaak (Latijn: *causa*) is voor een
verandering of *effect* in de afhankelijke variabele. Zo kunnen we na
experimenteel onderzoek met enige zekerheid concluderen, bijvoorbeeld,
dat een verschil in behandeling na een herseninfarct de oorzaak is, of
een belangrijke oorzaak is, van een verschil in taalvaardigheid van een
patiënt zoals geobserveerd 6 maanden na een herseninfarct. Het
experiment heeft aannemelijk gemaakt dat er een causaal of oorzakelijk
verband is tussen de behandelingsmethode (onafhankelijke variabele) en
de resulterende taalvaardigheid (afhankelijke variabele).

## Causaliteit {#sec:causaliteit}

Een causaal of oorzakelijk verband tussen twee variabelen is iets anders
dan een 'gewoon' verband of samenhang tussen twee variabelen. Als twee
verschijnselen met elkaar samenhangen, hoeft het ene niet de oorzaak van
het andere te zijn. Een eerste voorbeeld zien we bij de samenhang tussen
de lengte van personen en hun gewicht: lange mensen zijn over het
algemeen zwaarder dan korte mensen (en omgekeerd: korte mensen zijn over
het algemeen lichter dan lange mensen). Is er nu sprake van een causale
relatie tussen lengte en gewicht? Wordt het ene kenmerk (deels)
veroorzaakt door het andere? Nee, in dit voorbeeld is er wel samenhang
maar geen causaal verband tussen de kenmerken: zowel lengte als gewicht
worden "veroorzaakt" door andere variabelen, o.a. genetische
eigenschappen en voedingspatronen. Een tweede voorbeeld is de samenhang
tussen motivatie en taalvaardigheid van iemand die een vreemde taal
leert: hoog gemotiveerde studenten leren een nieuwe vreemde taal beter
en vlotter dan laag gemotiveerde studenten, maar ook hier is niet
duidelijk wat de oorzaak en wat het gevolg is.

Een causaal verband is een speciale vorm van samenhang. Een causaal
verband is een verband tussen twee twee verschijnselen of kenmerken,
waarbij bovendien voldaan moet zijn aan een aantal extra voorwaarden
[@SCC02]. Ten eerste moet de oorzaak aan het gevolg vooraf gaan (na
behandeling treedt verbetering op). Ten tweede moet het gevolg niet
optreden als de oorzaak niet aanwezig was (zonder behandeling geen
verbetering). Bovendien moet het gevolg --- althans in theorie ---
altijd optreden als de oorzaak aanwezig is (behandeling resulteert
altijd in verbetering). Ten derde kunnen we geen andere plausibele
verklaring vinden voor het optreden van het gevolg, behalve de mogelijke
oorzaak. Als we het causale mechanisme kennen (we snappen waarom
behandeling de oorzaak is van verbetering), dan zijn we beter in staat
om mogelijke andere plausibele verklaringen uit te sluiten. Helaas is
dat bij de gedragswetenschappen, inclusief de taalwetenschap, echter
zelden het geval. We constateren wel dat een behandeling resulteert in
verbetering, maar de theorie die oorzaak (behandeling) en gevolg
(verbetering) verbindt is zelden compleet en vertoont belangrijke
lacunes. Dat betekent dat we goede voorzorgen moeten treffen in onze
onderzoeksmethoden, teneinde mogelijke alternatieve plausibele
verklaringen voor de gevonden effecten uit te sluiten.

## Validiteit {#sec:validiteit}

Een bewering of conclusie is *valide* als de bewering *waar* (true) en
*gerechtvaardigd* (justified) is. Een ware uitspraak correspondeert met
de werkelijkheid: de bewering *ieder kind leert ten minste een taal* is
waar, omdat de bewering de werkelijkheid goed weergeeft. Een
gerechtvaardigde bewering ontleent geldigheid aan de empirische
evidentie waarop die bewering is gebaseerd: ieder kind dat wij hebben
geobserveerd, of dat anderen hebben geobserveerd, leert een taal of
heeft een taal geleerd (behalve bijzondere gevallen voor wie een aparte
verklaring nodig is). De rechtvaardiging van een bewering is sterker
naarmate de methode van (directe of indirecte) observatie sterker is en
meer zekerheid biedt. Dit houdt ook in dat de validiteit van een
bewering niet een categoriale eigenschap is (wel/niet valide) maar een
gradueel kenmerk: een bewering kan meer of minder valide zijn.

Aan de validiteit van een bewering kunnen drie verschillende aspecten
worden onderscheiden.

1.  In hoeverre zijn de conclusies over de relaties tussen de
    afhankelijke en de onafhankelijke variabele geldig? Deze vraag heeft
    betrekking op de *interne validiteit*.

2.  In hoeverre zijn de uitwerkingen, operationaliseringen, van de
    afhankelijke en onafhankelijke variabele adequaat? Deze vraag heeft
    betrekking op de *constructvaliditeit*.

3.  In hoeverre kunnen de conclusies gegeneraliseerd worden naar andere
    proefpersonen, stimuli, condities, situaties, observaties? Deze
    vraag heeft betrekking op de *externe validiteit*.

Deze drie vormen van validiteit zullen wij in de navolgende paragrafen
toelichten.

## Interne validiteit {#sec:internevaliditeit}

Het is vanzelfsprekend de bedoeling om in een experimenteel onderzoek
zoveel mogelijk alternatieve verklaringen voor de onderzoeksresultaten
uit te sluiten. Er moet immers aangetoond worden dat er een causaal
verband is tussen twee variabelen X en Y, en daarbij moeten storende
factoren zoveel mogelijk onder controle gehouden worden. Laten we eens
kijken naar voorbeeld 5.1 hieronder. 

---

> *Voorbeeld 5.1*: [@Verh04] onderzochten o.a. de hypothese dat
ouderen (boven de 45 jaar) langzamer spreken dan jongeren (onder de 40
jaar). Om dat te onderzoeken werd spraak opgenomen van 160 sprekers,
gelijk verdeeld over de twee leeftijdsgroepen, in een interview van
ongeveer 15 minuten. Na fonetische analyse van de articulatiesnelheid
blijkt dat de "jongeren" relatief snel spreken met 4.78 lettergrepen per
seconde, en de "ouderen" aanzienlijk langzamer, met 4.52 lettergrepen
per seconde [@Verh04, p.302]. We concluderen dat de hogere leeftijd de
*oorzaak* is van het lagere spreektempo bij de oudere sprekers --- maar
is die conclusie terecht?

---

Deze vraag naar de rechtvaardiging van de conclusie is een vraag naar de
interne validiteit van het onderzoek. De interne validiteit heeft
betrekking op de relaties tussen gemeten of gemanipuleerde variabelen,
en is onafhankelijk van de (theoretische) constructen die de
verschillende variabelen representeren (vandaar de term 'interne
validiteit'). Of, anders gezegd: de vraag naar de interne validiteit is
een vraag naar mogelijke alternatieve verklaringen voor de gevonden
onderzoeksresultaten. Veel van de mogelijke alternatieve verklaringen
kunnen worden ondervangen door de manier waarop de gegevens worden
verzameld. We bespreken hieronder de meest in het oog lopende
bedreigingen van de interne validiteit [@SCC02].

1. **Geschiedenis**
is een bedreiging van de
interne validiteit. Het begrip 'geschiedenis' omvat o.a. gebeurtenissen
die hebben plaatsgevonden tussen of tijdens een voormeting en een
nameting; het gaat dan om gebeurtenissen die geen deel uitmaken van de
experimentele manipulatie (de onafhankelijke variabele), maar die wel
van invloed zouden kunnen zijn op de afhankelijke variabele. Een
hittegolf, bijvoorbeeld, kan van invloed zijn op het gedrag van de
proefpersonen tijdens een onderzoek.

In een laboratorium wordt de 'geschiedenis' onder controle gehouden door
de proefpersonen af te sluiten van invloeden van buitenaf (zoals een
hittegolf), of door afhankelijke variabelen te kiezen die nauwelijks
beïnvloed kunnen worden door externe factoren. In onderzoek buiten het
laboratorium, waaronder veldonderzoek, is het veel lastiger en vaak
zelfs onmogelijk om invloeden van buitenaf onder controle te houden. In
het volgende voorbeeld wordt dit duidelijk.

---

> *Voorbeeld 5.2*: In een onderzoek worden twee methoden vergeleken om leerlingen een
vreemde taal te leren spreken, i.c. Nieuw-Grieks. De eerste groep moet
Griekse woordjes en grammatica leren in een klaslokaal, gedurende enkele
weken. De tweede groep gaat in diezelfde periode op een studiereis naar
Griekenland, waar leerlingen moeten converseren in de doeltaal. De
totale tijd besteed aan het taalvaardigheidsonderwijs is voor beide
groepen gelijk. Na afloop blijkt de taalvaardigheid van de tweede groep
groter dan die van de eerste groep. Wordt dat verschil in de
afhankelijke variabele inderdaad veroorzaakt door de lesmethode
(onafhankelijke variabele)?

---

2. **Rijping** is de natuurlijke veroudering of rijping van proefpersonen
tijdens een onderzoek. Als de proefpersonen gedurende een onderzoek
ouder worden, zich ontwikkelen, meer ervaren of sterker worden, èn als
deze rijping niet is opgenomen in de onderzoeksvraag, dan vormt rijping
een bedreiging van de interne validiteit. In experimenten waarin
reactietijden worden gemeten, bijvoorbeeld, zien we meestal dat de
reactietijden van een proefpersoon sneller worden gedurende het
experiment, als gevolg van training en oefening. We kunnen de interne
validiteit dan beschermen tegen dit leer-effect, door de stimuli voor
iedere proefpersoon in een andere willekeurige volgorde aan te bieden.

Meestal is er sprake van rijping doordat de proefpersonen vele malen
achtereen dezelfde taak uitvoeren of dezelfde vragen beantwoorden.
Rijping kan echter ook optreden wanneer proefpersonen hun antwoorden
kenbaar moeten maken op een juist niet gebruikelijke manier, bv. door
een ongewone vraagstelling, of in een ongebruikelijke vorm van
meerkeuze-vragen. Bij de eerste paar keer dat een proefpersoon dan
vragen beantwoordt, kan de wijze van beantwoorden interfereren met het
antwoord zelf. Achteraf kunnen we een vergelijking maken tussen bv. het
eerste kwart en het laatste kwart van de antwoorden, om zo te bekijken
of er een mogelijk effect was van ervaring, d.w.z. van rijping.

3. Ook de **instrumentatie** of instrumenten die voor een onderzoek
gebruikt worden, kunnen een bedreiging vormen voor de interne
validiteit. Verschillende instrumenten die worden geacht hetzelfde
construct te meten, moeten ook gelijke metingen produceren. En hetzelfde
instrument moet ook gelijke metingen produceren onder verschillende
omstandigheden. Voor computer-gestuurde experimenten is dat meestal geen
probleem. Maar bij vragenlijsten, of bij de beoordeling van
schrijfopdrachten, kan de interne validiteit wel worden bedreigd.

Bij veel onderzoek worden observaties gedaan zowel voorafgaand aan een
behandeling, als na afloop daarvan. Daarbij kan dezelfde toets gebruikt
worden, maar dan kan er een leer-effect optreden (zie hierboven).
Onderzoekers gebruiken daarom vaak verschillende toetsen bij de
voormeting en de nameting, maar daarbij kan er wel een
instrumentatie-effect optreden. De onderzoeker moet de mogelijke voor-
en nadelen tegen elkaar afwegen.

---

> *Voorbeeld 5.3*: [@Rijl86]
onderzocht het effect van 'peer evaluation' op de kwaliteit van
schrijfproducten. De opzet van zijn onderzoek was (enigszins
vereenvoudigd) als volgt: eerst schrijven de leerlingen een opstel over
onderwerp A, dan volgt het schrijfonderwijs inclusief 'peer evaluation',
waarna nogmaals een opstel geschreven wordt over onderwerp B. De
schrijfproducten van voormeting en nameting worden beoordeeld, waarna
getoetst wordt of de gemiddelde prestaties verschillen tussen voormeting
en nameting.

> In dit onderzoek vormt niet alleen de interventie (schrijfonderwijs) een
duidelijk verschil tussen de voormeting en de nameting, maar ook het
onderwerp van de schrijfopdracht (A of B) vormt een verschil. Het is
twijfelachtig of met beide schrijfopdrachten wel precies hetzelfde wordt
gemeten. Dit verschil in instrumentatie bedreigt de interne validiteit,
omdat er op verschillende momenten misschien een (deels) verschillend
aspect van de schrijfvaardigheid is gemeten. De instrumentatie (hier:
het verschil in onderwerpen van de schrijfopdrachten) geeft een
plausibele alternatieve verklaring voor een verschil in
schrijfvaardigheid, naast of in plaats van de onafhankelijke variabele
(hier: het tussentijdse schrijfonderwijs).

---

4. Een volgende bedreiging van de interne validiteit staat bekend als
het effect van **regressie naar het gemiddelde**. Regressie naar het
gemiddelde kan een rol spelen zodra het onderzoek gericht is op speciale
groepen, bijvoorbeeld slechte lezers, slechte schrijvers, maar evenzo:
goede lezers, goede schrijvers, etc. We geven eerst een voorbeeld, omdat
het verschijnsel niet direct intuïtief duidelijk is.

---

> *Voorbeeld 5.4*: 
Er is enige controverse over het gebruik van illustraties in
kinderboeken. Sommigen menen dat in boeken waarmee kinderen leren lezen
geen (of zo min mogelijk) illustraties mogen voorkomen: illustraties
leiden de aandacht af van te leren kenmerken van woorden. Anderen menen
dat in illustraties wezenlijke informatie weergegeven kan worden:
illustraties dienen als extra informatiebron.

> [@Dona83] onderzocht de invloed van illustraties bij een tekst op het begrip van
die tekst. De onderzoeker selecteerde 120 leerlingen (uit 1868
leerlingen) uit de derde en zesde groep van het basisonderwijs; 60 uit
elk van beide groepen. Volgens de prestaties op een eerder afgenomen
leestoets bleken van de 60 leerlingen per klas er 30 als slechte en 30
als goede lezers geclassificeerd te kunnen worden. Elke leerling kreeg
dezelfde tekst te zien, aangeboden met of zonder illustraties
(onafhankelijke variabele), zie Tabel \@ref(tab:designDona83).

> De resultaten bleken goeddeels de tweede hypothese te ondersteunen:
illustraties bevorderen het begrip van de tekst, ook bij onervaren
lezers. De slechtere lezers begrepen de tekst met illustraties beter, en
ook jongere lezers ondervonden voordeel van de illustraties.

---

Table: (#tab:designDona83) Aanbiedingscondities in het onderzoek van Donald (1983).

  groep    leesvaardigheid   conditie   $n$              
  ------- ----------------- ---------- -----
  3            slecht         zonder    15               
  3            slecht          met      15               
  3             goed          zonder    15               
  3             goed           met      15               
  6            slecht         zonder    15               
  6            slecht          met      15               
  6             goed          zonder    15               
  6             goed           met      15               


Wat is er nu mis met dit onderzoek? Het antwoord is gelegen in de manier
waarop leerlingen zijn geselecteerd. Lezers werden ingedeeld als
'slecht' of 'goed' op basis van een leesvaardigheidstoets, maar hun
prestaties op die toets worden altijd beïnvloed door toevallige
factoren, die niets met leesvaardigheid te maken hebben: Tom voelde zich
niet lekker, daarom heeft hij deze toets slecht gemaakt, Sarah was met
haar gedachten elders, Niels had last van zijn knie, Julie was enorm
gemotiveerd en heeft zichzelf overtroffen. Met andere woorden: de
leesvaardigheid is niet geheel betrouwbaar gemeten. Dit betekent (1) dat
de slechte lezers die toevallig boven hun niveau gepresteerd hebben, ten
onrechte niet bij de slechte lezers ingedeeld werden, maar deel
uitmaakten van de groep goede lezers; en omgekeerd (2) dat goede lezers
die bij deze toets toevallig onder hun niveau gepresteerd hebben, ten
onrechte als slechte lezers bestempeld werden. Onder de slechte lezers
zitten dus altijd ook een paar lezers die helemaal zo slecht nog niet
zijn, en onder de goede lezers zitten ook een paar lezers die eigenlijk
niet zo goed zijn.

Wanneer de eigenlijk-goede lezers, die ten onrechte geclassificeerd zijn
als niet-goede lezers, een tweede leestoets maken (nadat zij een tekst
met of zonder illustraties bestudeerd hebben), dan zullen zij meestal
weer op hun gewone hoge niveau presteren. Een hogere score op de tweede
toets (de nameting) kan dus een artefact zijn van de selectiemethode.
Hetzelfde geldt, mutatis mutandis, voor de eigenlijk-slechte lezers die
ten onrechte geselecteerd zijn als niet-slechte lezers. Wanneer deze
leerlingen een tweede leestoets maken, dan zullen ook zij meestal weer
op hun gewone (lage) niveau presteren. De score op de nameting ligt voor
hen dus lager dan de score op de voormeting.

Voor het aangehaalde onderzoek van betekent dit dat het geconstateerde
verschil tussen slechte en goede lezers deels toevallig is. Ook als de
onafhankelijke variabele geen effect heeft, zal de groep 'goede' lezers
bij de tweede leestoets gemiddeld slechter presteren, en zal de groep
'slechte' lezers bij de tweede leestoets gemiddeld beter presteren. Met
andere woorden: het verschil tussen de twee groepen is bij de nameting
minder groot dan bij de voormeting, als gevolg van toevallige variatie:
regressie naar het gemiddelde. Het zal duidelijk zijn dat
onderzoeksresultaten getroebleerd kunnen worden door dit verschijnsel.
Zoals we hierboven zagen kan een experimenteel effect afgezwakt worden
of verdwijnen als gevolg van regressie naar het gemiddelde; omgekeerd
kan regressie naar het gemiddelde ten onrechte aangezien worden als een
experimenteel effect [@RMP18].

In het algemeen kan regressie naar het gemiddelde optreden als er een
classificatie gemaakt wordt op basis van een voormeting, waarvan de
scores samenhang vertonen met de scores van de nameting (zie
Hoofdstuk \@ref(ch:samenhang)). Als er geen enkele correlatie is tussen
voormeting en nameting, dan speelt regressie naar het gemiddelde zelfs
de hoofdrol: een verschil tussen voormeting en nameting is dan alleen
het gevolg van regressie naar het gemiddelde. Als er perfecte correlatie
is, dan speelt regressie naar het gemiddelde geen enkele rol, maar dan
is ook de voormeting niet informatief, want immers geheel (achteraf) te
voorspellen uit de nameting.

Regressie naar het gemiddelde kan een alternatieve verklaring bieden
voor de vermeende grote toename van scores tussen voormeting en nameting
voor een lage prestatiegroep (bv. slechte lezers), ten opzichte van een
kleinere toename voor een hoge prestatiegroep (bv. goede lezers).
Omgekeerd kan het ook een alternatieve verklaring bieden voor de
vermeende afname van scores tussen voormeting en nameting voor een hoge
prestatiegroep (bv. goede lezers), ten opzichte van een lage
prestatiegroep (bv. slechte lezers).

Het is beter om de groepen *niet* samen te stellen op basis van een van
de uitkomsten van een van de metingen (voormeting of nameting), maar op
basis van een ander, onafhankelijk criterium. De proefpersonen van beide
groepen zullen dan zullen bij de voormeting ongeveer gemiddeld scoren,
en het effect van regressie naar het gemiddelde is dan klein. In alle
groepen zullen dan ongeveer evenveel proefpersonen zitten met een door
het toeval iets te hoge als met een iets te lage uitgevallen score,
zowel bij de voormeting als bij de nameting.

5. Een vijfde bedreiging van de interne validiteit is **selectie**.
Hiermee doelen we (voornamelijk) op een
zodanige verdeling van proefpersonen over verschillende condities dat
deze bij aanvang van het onderzoek niet gelijkwaardig zijn. Wanneer
bijvoorbeeld in de experimentele conditie alle slimme proefpersonen
zitten, terwijl in de controleconditie alleen de domme leerlingen
terecht gekomen zijn, dan kan een effect niet zonder meer aan de
manipulatie van de onafhankelijke variabele toegeschreven worden. Het
verschil in aanvangsniveau (hier: in intelligentie) levert dan een
plausibele alternatieve verklaring die de interne validiteit bedreigt.

---

> *Voorbeeld 5.5*: Voor een eerlijke vergelijking tussen scholen van hetzelfde schooltype
(VMBO, HAVO, VWO, etc) moeten we rekening houden met verschillen tussen
scholen in hun ingangsniveau van de leerlingen. Stel dat school A
leerlingen heeft met ingangsnivo 50, en eindexamennivo 100 (op een
willekeurige schaal). School B heeft leerlingen met ingangsnivo 30, en
eindexamennivo 90 (op dezelfde schaal). Is school B slechter dan A (want
lager eindnivo), of is school B beter dan A (want kleiner verschil in
eindnivo)?

---

In veel onderwijskundig onderzoek is het onmogelijk om leerlingen van
verschillende klassen op basis van het toeval aan condities toe te
wijzen --- dit wordt wel aselecte toewijzing genoemd. Dit kan namelijk
onoverkomelijke organisatorische problemen met zich meebrengen. Deze
organisatorische problemen omvatten meer dan alleen het (aselect)
splitsen van de klas, hoewel dit vaak al lastig te realiseren is. Ook
moet de onderzoeker rekenschap afleggen van mogelijke
overdrachtseffecten tussen de condities: de leerlingen praten met
elkaar, leren elkaar misschien zelfs wel de essentialia van de
experimentele conditie(s). Het uitblijven van een effect zou dan op
tenminste één alternatieve manier verklaard kunnen worden. Vanwege de
geschetste problematiek worden vaak complete schoolklassen toegewezen
aan een van de condities. Maar klassen bestaan uit een aantal leerlingen
van dezelfde school. Bij de keuze van leerlingen, en hun ouders, voor
een school treedt zelf-selectie op (in het Nederlandse
onderwijssysteem), waardoor er verschillen zijn in uitgangspositie
tussen condities (d.w.z. tussen klassen binnen condities). Eventuele
gevonden verschillen tussen condities zouden dus ook door zelfselectie
van leerlingen naar scholen veroorzaakt kunnen zijn.

Hierboven is al de meest eenvoudige manier aangegeven om verschillende
condities een gelijk aanvangsniveau te geven: wijs de leerlingen
aselect, volgens toeval, 'at random', toe aan de condities. Deze methode
staat bekend als *randomisatie* [@SCC02, p.294 ff]. We kunnen bijvoorbeeld
randomiseren door leerlingen een willekeurig (random) nummer te geven
(zie
Appendix \@ref(app:randomgetallen)) en daarna de 'even leerlingen' aan de
ene conditie en de 'oneven leerlingen' aan de andere conditie toe te
wijzen. Bij aselecte toewijzing van proefpersonen aan condities berusten
alle verschillen tussen de proefpersonen in de verschillende condities
op toeval, en worden die verschillen dus uitgemiddeld. Naar alle
waarschijnlijkheid zijn er dan geen systematische verschillen tussen de
onderscheiden groepen of condities. Dit geldt echter alleen indien de
groepen groot genoeg zijn.

Randomisatie, de aselecte toewijzing van proefpersonen aan condities,
moet onderscheiden worden van de aselecte steekproeftrekking uit een
populatie (zie
§\@ref(sec:aselectesteekproef)). Bij aselecte
steekproeftrekking gaat het om de willekeurige selectie van
proefpersonen uit de populatie van mogelijke proefpersonen naar de
steekproef; we streven er dan naar dat de steekproef of steekproeven
lijken op de populatie waaruit die getrokken is/zijn. Bij randomisatie
gaat het om de willekeurige toewijzing van de proefpersonen uit de
steekproef aan de verschillende condities van het onderzoek; we streven
er dan naar dat de steekproeven lijken op elkaar.

Een tweede methode om twee gelijke groepen te creëren is *matching*. Bij
matching worden proefpersonen eerst gemeten op een aantal relevante
variabelen. Daarna worden koppels gevormd die een gelijke score op deze
variabelen hebben. Van deze koppels wordt er één aan de ene conditie en
één aan de andere conditie toegewezen. Matching heeft echter
verschillende bezwaren. Ten eerste kan regressie naar het gemiddelde een
rol gaan spelen. Ten tweede is matching, wanneer de proefpersonen op
meerdere variabelen gematcht moeten worden, zeer bewerkelijk, en is een
grote groep potentiële proefpersonen vereist. Ten derde wordt bij
matching alleen rekening gehouden met variabelen die de onderzoeker
relevant acht, en niet met andere onbekende variabelen. Bij randomisatie
wordt niet alleen gerandomiseerd naar die relevante variabelen, maar ook
naar andere eigenschappen die mogelijk een rol zouden kunnen spelen
zonder dat de onderzoeker zich dat realiseert. Kortom, de relatief
eenvoudige randomisatie is verre te prefereren boven matching.

6. **Uitval** van respondenten is de laatste bedreiging van interne
validiteit. In sommige gevallen begint een onderzoeker met veel
proefpersonen. Gedurende het onderzoek vallen echter proefpersonen uit.
Zolang het percentage uitvallers beperkt blijft, is er geen probleem.
Maar er ontstaat wel een probleem, als de uitval selectief is voor één
van de onderscheiden condities. Is dat laatste wel het geval, dan kan er
over die conditie niet veel meer gezegd worden. Het probleem van uitval
speelt vooral een rol bij longitudinaal onderzoek. Dit is onderzoek
waarbij een beperkte groep respondenten gedurende een langere periode
gevolgd wordt. Men heeft daarbij echter te maken met mensen die
verhuizen, of overlijden gedurende het experiment, of participanten die
niet meer willen meewerken, enz. Dit kan een enorme reductie van het
aantal respondenten teweeg brengen.

Hierboven hebben we een aantal veel voorkomende problemen besproken die
de interne validiteit van een onderzoek kunnen bedreigen. De lijst is
echter niet uitputtend! Elk type onderzoek heeft zo z'n eigen problemen,
en het is de taak van de onderzoeker om alert te zijn op mogelijke
bedreigingen van de interne validiteit. Probeer daartoe plausibele
verklaringen te bedenken die een eventueel effect ook, of zelfs beter
zouden kunnen verklaren dan de te onderzoeken oorzaak. De onderzoeker
moet dus denken als zijn eigen scepticus, die geenszins overtuigd is dat
de onderzochte factor werkelijk de oorzaak is van het gevonden effect.
Welke mogelijke alternatieve verklaringen zijn er volgens die scepticus,
en hoe zou de onderzoeker die bedreigingen voor de validiteit kunnen
wegnemen door de opzet van het onderzoek? Dat vereist goed inzicht in de
logische relaties tussen de onderzoeksvragen, de onderzochte variabelen,
de resultaten, en de conclusie.

## Constructvaliditeit {#sec:constructvaliditeit} 

In een experimenteel onderzoek wordt een onafhankelijke variabele
gemanipuleerd. Dit kan, afhankelijk van de vraagstelling, op vele
manieren. Evenzo kan de wijze waarop de afhankelijke variabele(n)
gemeten wordt op verschillende manieren vorm gegeven worden. De manier
waarop de onafhankelijke en de afhankelijke variabelen vorm gegeven
worden noemen we de *operationalisatie* van deze variabelen. De
leesvaardigheid van leerlingen kan bijvoorbeeld geoperationaliseerd
worden als (a) hun score op een tekstbegriptoets met open vragen; (b)
hun score op een tekstbegriptoets met meerkeuzevragen; (c) hun score op
een zgn. cloze-toets (ontbrekend woord invullen); of (d) als de mate
waarin geschreven instructies uitgevoerd kunnen worden. Meestal zijn er
heel veel manieren om een variabele te operationaliseren, en zelden
volgt uit een theorie één dwingende beschrijving voor de wijze van
operationalisatie van de onafhankelijke of de afhankelijke variabelen.
*Constructvaliditeit*, of *begripsvaliditeit*, heeft betrekking op de
mate waarin de operationalisatie van zowel de afhankelijke variabele(n)
als de onafhankelijke variabele(n) een adequate afspiegeling is (zijn)
van de theoretische constructen waar het onderzoek zich op richt. Met
andere woorden: zijn de onafhankelijke en de afhankelijke variabelen
goed gerelateerd aan de theoretische concepten waar het onderzoek op
gericht is?

---

> *Voorbeeld 5.6*: De *taalontwikkeling* van
babies en peuters is lastig te observeren, en al helemaal als het gaat
om de auditieve en perceptieve ontwikkeling van deze proefpersonen die
nog niet of nauwelijks zelf spreken. Een veel gebruikte methode is het
Head Turn Preference Paradigm [@John10]. Bij deze methode kijkt de baby
eerst naar een groen knipperend licht recht voor zich. Als de aandacht
van het kind zo is gevangen, dooft vervolgens het groene licht en begint
een rood licht te knipperen, aan de linker of rechter zijde van de
proefpersoon. Het kind draait dan zijn of haar hoofd om het knipperende
licht te zien. Vervolgens wordt er een spraakgeluidsbestand afgespeeld,
via een luidspreker vlak bij het knipperende licht aan de zijkant. De
afhankelijke variabele is de periode waarin het kind zijwaarts blijft
kijken (met minder dan 2 s onderbreking). Daarna begint een nieuwe
aanbiedingscyclus. De kijktijd wordt opgevat als een indicatie voor de
mate van voorkeur van het kind voor de gesproken stimulus.

> De interpretatie van de verkregen kijktijden is echter lastig, omdat
kinderen nu eens voorkeur hebben voor nieuwe geluidsstimuli (bv zinnen
in een onbekende taal), en dan weer juist aan bekende stimuli (bv
grammaticale vs ongrammaticale zinnen). Zelfs als de stimuli nauwkeurig
zijn afgestemd op het ontwikkelingsniveau van de proefpersoon, is het
lastig om de afhankelijke variabele (kijktijd) goed te relateren aan het
bedoelde theoretische construct (voorkeur van kind).

---

> *Voorbeeld 5.7*: Zoals hierboven aangegeven kan het begrip *leesvaardigheid* op allerlei
manieren worden geoperationaliseerd. Volgens sommigen kan
leesvaardigheid niet goed gemeten worden met behulp van meerkeuzevragen
(Houtman 1986, Shohamy 1984). Bij meerkeuzevragen worden de antwoorden
zeer sterk beïnvloed door andere zaken zoals algemene ontwikkeling,
gokvaardigheid, ervaring met eerdere toetsen, en door de vraagstelling
zelf, zoals geïllustreerd in deze vraag:

> *Wie van de volgende personen heeft de afgelopen jaren een autobiografie
gepubliceerd?\
 a. Jeanne d'Arc *(algemene ontwikkeling)*\
 b. mijn buurvrouw *(vraagstelling, ervaring)*\
 c. Malala Yousafzai\
 d. Alexander Graham Bell *(algemene ontwikkeling)**\

> Deze vraag is duidelijk niet construct-valide voor het meten van kennis
over autobiografieën.

---

Uiteraard gelden bovengenoemde problemen met de constructvaliditeit niet
alleen voor schriftelijke vragen of meerkeuzevragen, maar ook voor
mondelinge vragen aan proefpersonen.

---

> *Voorbeeld 5.8*:
Als we ouders mondeling de vraag stellen *Hoe vaak leest U uw kind
eigenlijk voor?* dan wekken we met die vraag al de suggestie dat
voorlezen wenselijk is. De ouders zouden hun voorleesgedrag wel eens
kunnen overschatten. We meten dus niet alleen het construct
'voorleesgedrag', maar ook het construct 'neiging tot sociaal wenselijke
antwoorden' (zie hierna).

---

Een notoir lastig construct om te operationaliseren is
*schrijfvaardigheid*. Wat is een goed en wat is een slecht
schrijfproduct? En wat is dan eigenlijk schrijfvaardigheid? Kan
schrijfvaardigheid gemeten worden door een telling van relevante
inhoudselementen in een tekst, moeten er zinnen of woorden geteld
worden, of misschien vooral connectieven (*dus, want, omdat, hoewel*,
enz), moeten er oordelen van *lezers* verzameld worden over de
geschreven tekst (t.a.v. doelgerichtheid, publiekgerichtheid, stijl), of
moet er één oordeel van lezers verzameld worden over de globale
kwaliteit, moeten er spelfouten geteld worden, etc? De problemen bij de
operationalisatie komen voort uit een gebrek aan theorie over
schrijfvaardigheid, waaruit een definitie voor de kwaliteit van
schrijfproducten afgeleid zou kunnen worden [@BM93]. Kritiek op
onderzoek naar schrijfvaardigheid is daarom makkelijk, maar alternatieve
operationalisaties van het construct zijn moeilijk.

Een ander lastig construct is de *verstaanbaarheid* van gesproken
zinnen. Verstaanbaarheid ('intelligibility') kan op diverse manieren
worden geoperationaliseerd. De eerste mogelijkheid is dat de onderzoeker
de woorden of zinnen uitspreekt en dat de proefpersoon die naspreekt,
waarbij fouten in de reproductie geteld worden; een nadeel hierbij is
dat er nauwelijks controle is over de model-uitspraak van de
onderzoeker. Een tweede mogelijkheid is dat de woorden of zinnen vooraf
worden opgenomen en verder dezelfde procedure wordt gevolgd; een nadeel
blijft dat de responsies worden beïnvloed door kennis van de wereld,
grammaticale verwachtingen, bekendheid met de spreker of zijn
taalgebruik, enz. De meest betrouwbare methode is die van de zgn.
'speech reception threshold' [@Plomp79] beschreven in het volgende 
voorbeeld. Deze methode heeft echter als nadeel dat ze
tijdrovend is, niet goed automatisch afgenomen kan worden, en dat er
veel stimulusmateriaal (spraakopnamen) nodig is (zijn) voor een enkele
meting.

---

> *Voorbeeld 5.19*: We laten een lijst van 13
gesproken zinnen horen, gemaskeerd met ruisgeluid. De verhouding tussen
spraak en ruis (speech-to-noise ratio, SNR) wordt uitgedrukt in dB. Bij
0 dB SNR zijn spraak en ruis even luid, bij +3 dB SNR is de spraak 3 dB
luider dan de ruis, bij -2 dB SNR is de spraak 2 dB *zachter* dan de
ruis, etc. Na iedere zin moet de luisteraar de aangeboden zin naspreken.
Als dat foutloos gebeurt, dan wordt voor de volgende zin de SNR met 2 dB
verlaagd (minder spraak of meer ruis); als de responsie fout was, dan
wordt voor de volgende zin de SNR met 2 dB verhoogd (meer spraak of
minder ruis). Na een paar zinnen is er weinig variatie meer in SNR, en
schommelt de SNR rond een optimum. De gemiddelde SNR over de laatste 10
aangeboden zinnen vormt de 'speech reception threshold' (SRT). Deze SRT
is ook op te vatten als de SNR waarbij de helft van de zinnen goed wordt
verstaan.

---

Tot nog toe hebben we het gehad over problemen met betrekking tot de
constructvaliditeit van de afhankelijke variabelen. Maar ook de
operationalisatie van de *on*afhankelijke variabele staat vaak ter
discussie. De onderzoeker heeft immers vele keuzes moeten maken tijdens
de operationalisering van zijn onafhankelijke variabele (zie
§\@ref(sec:keuzemomenten)), en de gemaakte keuzes zijn vaak wel
aanvechtbaar.

Een onderzoek is niet constructvalide, of niet begripsvalide, als de
operationalisaties van de afhankelijke variabelen de toets der kritiek
niet kunnen doorstaan. Een onderzoek is ook niet constructvalide, als de
onafhankelijke variabele niet een valide operationalisatie is van
het-theoretische-begrip-zoals-bedoeld. Als die operationalisatie niet
valide is, dan wordt er dus eigenlijk iets anders gemanipuleerd dan de
bedoeling was. In dat geval is de relatie tussen de afhankelijke
variabele en de gemanipuleerde onafhankelijke variabele zoals bedoeld
niet eenduidig meer. Eventuele geobserveerde verschillen in de
afhankelijke variabele hoeven niet alleen veroorzaakt te worden door de
onafhankelijke variabele zoals bedoeld, maar kunnen ook beïnvloed zijn
door andere factoren. Een bekend effect in dit opzicht is het zogenaamde
Hawthorne-effect.

---

> *Voorbeeld 5.10*: De directie
van de Hawthorne Works Factory (Western Electric Company) in Cicero
(Illinois), USA, was gealarmeerd door slechte bedrijfsresultaten. Een
team onderzoekers nam de gang van zaken onder de loep, waarbij ongeveer
alles werd onderzocht: werktijden, beloning, pauzes, verlichting,
verwarming, werkoverleg, management, enz. De resultaten van dat
onderzoek (uit 1927) wezen uit dat de productiviteit enorm was gestegen
-- maar dat er geen verband was met een van de onafhankelijke
variabelen. De toename van productiviteit werd uiteindelijk
toegeschreven aan de grotere aandacht voor de werknemers.

---

Het Hawthorne-effect houdt dus in dat een verandering in gedrag niet
samenhangt met de manipulatie van enige onafhankelijke variabele, maar
dat die verandering van gedrag het gevolg is van een psychologisch
verschijnsel: proefpersonen die weten dat ze worden geobserveerd, doen
meer hun best om gewenst gedrag te vertonen.

---

> *Voorbeeld 5.11*: [@RDCPW78]
vergeleken de effectiviteit van twee methoden ter verbetering van de
leesvaardigheid van slechte lezers. De leerlingen werden geselecteerd op
basis van hun scores op drie toetsen. De 72 geselecteerde leerlingen
werden aselect toegewezen aan één van de twee methode-condities
(gestructureerd leesonderwijs versus geprogrammeerde instructie). In de
eerste conditie werd het gestructureerde leesonderwijs verzorgd door
vier docenten, die aan een klein groepje (van vier leerlingen) les
gaven. In feite is de leerling-docent-ratio dus $1:1$. In de tweede
conditie (geprogrammeerde instructie) bemoeiden de docenten zich zo min
mogelijk met de leerlingen. Het experiment nam 75 sessies van 45 minuten
in beslag. Na de tweede observatie bleek dat de leerlingen die volgens
de eerste (gestructureerde) methode les gekregen hadden, beter vooruit
waren gegaan dan de leerlingen die met behulp van de tweede methode
(geprogrammeerde instructie) les gekregen hadden.

> Tot zover is er geen probleem met dit onderzoek. Er ontstaat pas een
probleem als we zouden concluderen dat de gestructureerde methode beter
is dan de geprogrammeerde instructie. Een alternatieve verklaring, die
in dit onderzoek niet uitgesloten kan worden, is dat het gevonden effect
niet (alleen) het gevolg is van de methode, maar (ook) een gevolg is van
de grotere individuele aandacht in de eerste conditie (gestructureerd
leesonderwijs).

---

Net zoals bij de interne validiteit kan ook bij de construct- of
begripsvaliditeit een aantal validiteitbedreigende factoren genoemd
worden.

1. Een eerste bedreiging van de begripsvaliditeit is
*mono-operationalisatie*. In veel onderzoeken wordt de afhankelijke
variabele slechts op één manier geoperationaliseerd. De proefpersonen
hoeven slechts één taak uit te voeren, bv. één auditieve taak met
reactietijdmetingen (over meerdere aanbiedingen), of één vragenlijst
(met meerdere vragen). Het onderzoek staat of valt dan met deze
specifieke operationalisatie van de afhankelijke variabele. Over de
validiteit van deze specifieke operationalisatie zijn dan geen verdere
gegevens voorhanden. De onderzoeker laat in zo'n geval ruimte voor
twijfel. Strikt genomen moeten we de onderzoeker immers op zijn woord
geloven omtrent de validiteit van zijn operationalisering. Dergelijk
onderzoek kan veel beter worden uitgevoerd. De onderzoeker moet dan het
te meten construct op verschillende manieren operationaliseren, bv. door
meerdere auditieve taken te laten uitvoeren, met niet alleen
reactietijdmetingen maar ook met tellingen van foutieve responsies. Of
de onderzoeker laat niet alleen een vragenlijst invullen, maar
observeert het bedoelde construct ook d.m.v. andere taken en
observatiemethoden. Wanneer de prestaties op de verschillende typen
responsies in hoge mate samenhangen, kan daarmee aangetoond worden dat
al deze toetsen hetzelfde construct vertegenwoordigen. We noemen dit
*convergente validiteit*. Er is sprake van convergente validiteit als de
prestaties op instrumenten die hetzelfde theoretische construct
vertegenwoordigen, in hoge mate samenhangen (convergeren).

Het is echter niet voldoende om te laten zien dat toetsen die hetzelfde
concept of construct beogen te meten, inderdaad convergent valide zijn.
Daarmee is immers nog niet aangetoond wat dit construct is, en evenmin
of het gemeten construct wel het bedoelde construct is. Hebben we wel
echt 'vloeiendheid' van de spreker gemeten, met meerdere methoden, of
hebben we eigenlijk steeds het construct 'aandacht' of 'spreeksnelheid'
gemeten? En hebben we wel echt 'mate van tekstbegrip' gemeten, met
verschillende convergente methoden, of hebben we eigenlijk steeds het
construct 'faalangst' gemeten? Om de construct-validiteit te waarborgen
moet eigenlijk ook worden aangetoond dat de operationalisaties
*divergent valide* zijn ten opzichte van operationalisaties die een
ánder aspect of een ándere (verwante) vaardigheid beogen te meten.
Kortom de onderzoeker moet kunnen aantonen dat de prestaties op
instrumenten (operationalisaties) die één vaardigheid (construct)
vertegenwoordigen in hoge mate samenhangen (convergeren), terwijl de
prestaties op instrumenten die verschillende vaardigheden
vertegenwoordigen juist lage samenhang vertonen (divergeren). Pas dan
heeft de onderzoeker aannemelijk gemaakt dat de specifieke
operationalisaties inderdaad constructvalide zijn.

2. Ook de verwachtingen van de onderzoeker --- die zich uiten in bewust
èn onbewust gedrag --- kunnen de constructvaliditeit van een onderzoek
bedreigen. De onderzoeker is ook een mens, en is dus niet immuun voor de
invloed van zijn of haar eigen verwachtingen op de uitkomsten van het
onderzoek. Na afloop van het experiment is de invloed van de onderzoeker
helaas moeilijk te achterhalen.

---

> *Voorbeeld 5.12*:Kluger Hans was een paard dat kon rekenen. 
Als aan Kluger Hans gevraagd werd
*hoeveel is $4+4$?*, dan stampte het paard 8 maal met zijn rechter
voorhoef, als gevraagd werd *hoeveel is $3-1$?*, dan stampte Hans twee
maal met zijn voorhoef. Kluger Hans baarde veel opzien en werd onderwerp
van verschillende studies. Een commissie stelde in 1904 vast dat Kluger
Hans inderdaad kon rekenen (en communiceren met mensen). Later
constateerde een lid van de onderzoekscommissie, Carl Stumpf, samen met
zijn assistent Oskar Pfungst, echter: "...het paard laat verstek gaan,
als de oplossing van de gestelde opgave aan geen van de aanwezigen
bekend is" [@Pfung07 p.185, vert. HQ], of als het de persoon die de
oplossing weet niet kan zien. "Es bedarf also optischer Hilfen" (idem).
Na nauwkeurige observaties bleek dat de baas van Kluger Hans (en andere
aanwezigen) zich een heel klein beetje ontspande zodra Hans het juiste
aantal malen met zijn rechter voorpoot gestampt had. Dit onopzettelijke
teken was voor Kluger Hans voldoende aanleiding om het stampen te staken
(d.i. om zijn rechter voorhoef op de grond te houden), teneinde daarna
zijn beloning van wortels en brood in ontvangst te nemen
[@Pfung07] [@Watz77, p.38--47].

> Een misschien vergelijkbaar, recenter geval is dat van Alex, een
papegaai met bijzondere cognitieve gaven, zie o.a. [@BLLB14] en [@Alex15].

---

Het beroemde voorbeeld van Kluger Hans illustreert hoe subtiel de invloed van een
onderzoeker of proefleider op het te onderzoeken object kan zijn. Deze
invloed bedreigt natuurlijk de constructvaliditeit. Het is daarom beter
als de onderzoeker niet ook zelf fungeert als experimentator[^fn05-1] of
proefleider. Studies waarin de onderzoeker zelf optreedt als behandelaar
of docent of beoordelaar, kunnen worden bekritiseerd omdat de
(verwachtingen van de) onderzoeker de uitkomsten kunnen beïnvloeden,
waardoor de constructvaliditeit van de onafhankelijke variabele wordt
bedreigd. Onderzoekers kunnen zich wel verweren tegen deze 'experimenter
bias'. In het Head Turn Preference Paradigm
(voorbeeld 5.6), bijvoorbeeld, is het gebruikelijk dat de
experimentator niet weet uit welke groep een proefpersoon afkomstig is,
en dat de experimentator niet hoort welk geluidsbestand wordt aangeboden
[@John10, p.74].

3. Een derde bedreiging van de constructvaliditeit kan samengevat
worden onder de term *motivatie*. Aan de bedreiging van de validiteit
door motivatie zitten tenminste twee kanten. Als (ten minste) één van de
condities in een onderzoek erg belastend of vervelend is, dan kunnen de
proefpersonen gedemotiveerd raken en zich minder inspannen bij hun
taken. Ze presteren dan minder, maar dit is een effect van (gebrek aan)
motivatie, en niet een direct effect van de onafhankelijke variabele
(hier: conditie). Het effect hoeft dan niet veroorzaakt te worden door
de manipulatie van het bedoelde construct, maar door de onbedoelde
manipulatie van de *motivatie* van de proefpersonen. Ook het omgekeerde
kan natuurlijk een bedreiging van de constructvaliditeit vormen. Indien
van één van de condities een extra motiverende werking op de
proefpersonen heeft, dan kan een eventueel effect toegeschreven worden
aan motivationele aspecten. Ook dan kan er sprake zijn van een effect
van een onbedoeld gemanipuleerde variabele.

4. Een vierde bedreiging van de validiteit heeft te maken met de keuze
uit de vele mogelijke waarden van een onafhankelijke variabele, d.w.z.
de *'dosering'* ervan. Als de onafhankelijke variabele is 'het aantal
keren dat een gedicht ter voorbereiding mag worden doorgelezen', moet de
onderzoeker bepalen hoeveel keer de proefpersonen het gedicht mogen
doorlezen: één, twee, drie of meer keren? Als de onafhankelijke
variabele is 'de tijd die de proefpersonen mogen studeren', dan moet de
onderzoeker kiezen hoe lang de proefpersonen mogen leren: vijf minuten,
een kwartier, twee uur? De onderzoeker maakt een keuze uit de dosering
van de onafhankelijke variabele 'leertijd'. Op grond van deze dosering
kan de onderzoeker concluderen dat de afhankelijke variabele niet
beïnvloed wordt door de onafhankelijke variabele. In feite moet de
onderzoeker echter concluderen dat er geen verband lijkt tussen de
*gekozen dosering van* de onafhankelijke variabele, en de afhankelijke
variabele. Een mogelijk effect wordt verhuld door de keuze van de
dosering (waarden) van de onafhankelijke variabele.

---

> *Voorbeeld 5.13*: Als een personenauto en een voetganger botsen, 
loopt de voetganger een
risico te overlijden. Dat overlijdensrisico is relatief gering (kleiner
dan 20%) bij botsingssnelheden tot ca 50 km/u. Als we ons onderzoek naar
het verband tussen botsingssnelheid en overlijdensrisico zouden beperken
tot deze lage 'doseringen' van botsingssnelheden, dan zouden we wellicht
concluderen dat de botsingssnelheid géén invloed heeft op het
overlijdensrisico voor de voetganger. Dat zou een foutieve conclusie
zijn (van welk type?), want bij hogere botsingssnelheden neemt het
overlijdensrisico voor de voetganger toe tot bijna 100%
[@Rosen11; @SWOV12].

---

5\. Een vijfde bedreiging van de constructvaliditeit wordt veroorzaakt
door de *sturende werking van de voormeting*. In veel studies wordt de
afhankelijke variabele herhaaldelijk gemeten, zowel voor als na
manipulatie van de afhankelijke variabele: de zgn. voormeting en
nameting. De aard en inhoud van de voormeting kunnen echter sporen
nalaten bij de proefpersoon. Zo kan de proefpersoon zijn onbevangenheid
verliezen, waardoor het effect van de onafhankelijke variabele (bv.
behandeling) wordt verkleind. Een eventueel verschil in scores tussen de
experimentele condities kan dus op meerdere manieren worden verklaard.
De verklaring kan immers liggen in een effect van alleen de
onafhankelijke variabele, maar kan ook liggen in een effect van *de
combinatie van voormeting en onafhankelijke variabele*. Bovendien kan de
afwezigheid van een effect soms worden verklaard door het feit dat een
voormeting is verricht (zie het Solomon vier-groepen-ontwerp, in Hoofdstuk \@ref(ch:ontwerp), voor een onderzoeksontwerp dat
hiermee rekening houdt).

---

> *Voorbeeld 5.14*: We kunnen de effecten van twee behandelingen vergelijken in een
experiment waarin de deelnemers volgens het toeval in twee groepen
worden ingedeeld. De eerste groep (E) krijgt eerst een voormeting, dan
een behandeling, en dan een nameting. De tweede groep (C) krijgt geen
voormeting, en ook geen behandeling, maar alleen een nameting, die voor
deze groep de enige meting is.

> Als we bij de nameting een verschil vinden tussen de twee groepen, dan
is dat niet zonder meer toe te schrijven aan het verschil in
behandeling. Het verschil zou ook, of mede, veroorzaakt kunnen zijn door
de sturende werking van de voormeting, bv als gevolg van de sturende
woordkeuze of zinsbouw van de vragen of opdrachten in de voormeting.
Misschien hebben de deelnemers in groep E iets geleerd in de voormeting,
d.w.z. *niet* in de behandeling, waardoor ze beter of anders presteren
in de nameting dan de deelnemers in groep C.

---

6. Een ander probleem dat van invloed kan zijn op de
constructvaliditeit is *sociaal wenselijk
antwoorden*. Dat is niets anders dan dat mensen
geneigd zijn een antwoord geven, dat in de gegeven sociale situatie
wenselijk is, en dat hen dus niet in de problemen brengt of tot
gezichtsverlies leidt. Een voorbeeld kan dit verduidelijken.

---

> *Voorbeeld 5.15*: Bij peilingen voor verkiezingen zijn respondenten geneigd om sociaal wenselijk te antwoorden, en dat geldt ook voor de vraag of de respondent überhaupt zal gaan stemmen [@Karp05]. De neiging tot het sociaal wenselijke antwoord ("ja, ik ga stemmen") is sterker naarmate respondenten hoger zijn opgeleid, en dus is de overschatting van het opkomst-percentage groter voor hoger-opgeleiden dan voor lager-opgeleiden. Dat heeft weer gevolgen voor de uitslagen van de peilingen van de verschillende partijen, omdat de populariteit van de politieke partijen verschillend is voor kiezers van verschillend opleidingsniveau.

---

Dit effect heeft mede gezorgd voor de overschatting van het aantal
Clinton-stemmers, en onderschatting van het aantal Trump-stemmers, bij
de peilingen voorafgaand aan de Amerikaanse presidentsverkiezing in
2016.

7. Een laatste probleem met betrekking tot de constructvaliditeit kan
aangeduid worden als: een *beperkte generaliseerbaarheid* over
constructen. Bij de presentatie van onderzoeksresultaten worden
regelmatig opmerkingen gemaakt als: 'Ja, ik ben het eens met uw
conclusie dat X van invloed is op Y, maar hoe zit het met...'. Op de
puntjes kan dan van alles ingevuld worden: de toepasbaarheid bij andere
doelgroepen, of in andere genres, of in andere talen, etc. Deze aspecten
zijn weliswaar van belang, maar spelen in het onderzoek zelf niet direct
een rol: we hebben het onderzoek immers uitgevoerd met een bepaalde
selectie van doelgroep, genre, talen, etc.

Toch bevelen we wel aan om zulke vragen over generaliseerbaarheid onder
ogen te zien. Zijn de conclusies eveneens van toepassing op een andere
doelgroep of taal? Waarom wel of niet? Welke andere factoren zouden de
generalisatie kunnen beïnvloeden? Zou een gunstig effect voor de ene
groep of taal ook kunnen uitpakken als een ongunstig effect voor een
andere groep of taal die buiten het onderzoek is gevallen?

## Externe validiteit {#sec:externevaliditeit}

Op basis van de gegevens die zijn verzameld kan een onderzoeker --- als
het goed is --- de conclusie trekken: *in dit onderzoek geldt dat...*.
Het is echter zelden de bedoeling van een onderzoeker om conclusies te
trekken die alleen gelden voor één onderzoek. Een onderzoeker wil niet
aantonen dat tweetaligheid een gunstige invloed heeft op de
taalontwikkeling *van de steekproef van onderzochte kinderen*. Een
onderzoeker wil conclusies trekken als: tweetaligheid heeft een gunstige
invloed op de taalontwikkeling *van kinderen*. De onderzoeker wil
generaliseren. In het dagelijks leven doen we hetzelfde: we proeven één
hapje soep uit een hele pan, en op grond daarvan doen we een uitspraak
over die hele pan soep. We gaan er van uit dat onze bevindingen op basis
van dat ene hapje gegeneraliseerd mogen worden naar de hele pan, en dat
het niet nodig is om de hele pan leeg te eten voordat we er een
uitspraak over kunnen doen.

De vraag of een onderzoeker de resultaten kan en mag generaliseren is de
vraag naar de *externe validiteit* van een onderzoek [@SCC02].
Generalisatie heeft betrekking op o.a.

-   eenheden: zijn de resultaten ook geldig voor andere elementen (bv.
    scholen, personen, teksten) uit de populatie, die niet aan het
    onderzoek deelnamen?

-   behandelingen: zijn de resultaten ook geldig voor andere
    behandelingen die lijken op de specifieke condities in dit
    onderzoek?

-   situaties: zijn de resultaten ook geldig buiten de specifieke
    context van dit onderzoek?

-   tijden: zijn de resultaten van dit onderzoek ook geldig op andere
    tijdstippen?

Bij externe validiteit maken we een onderscheid tussen (1) de
generalisatie *naar* een beoogde specifieke doelgroep, situatie en tijd,
en (2) de generalisatie *over* andere doelgroepen, situaties en tijden.
Het generaliseren *naar* en *over* zijn twee aspecten van de externe
validiteit die goed uit elkaar gehouden moeten worden. Het generaliseren
*naar* een doelgroep of populatie, van personen en vaak ook van
taalmateriaal, heeft te maken met de representativiteit van de gebruikte
steekproef; in hoeverre is de steekproef een goede afspiegeling van de
populatie (van personen, van woorden, van relevante mogelijke zinnen)?
Het generaliseren *naar* is dus direct verbonden met het onderzoeksdoel;
pas als er gegeneraliseerd kan worden naar gedefinieerde populaties kan
een onderzoeksdoel bereikt zijn. Het generaliseren *over* doelgroepen
heeft te maken met de mate waarin de geformuleerde conclusies geldig
zijn voor te onderscheiden deel-populaties. We illustreren dit met een
voorbeeld.

---

> *Voorbeeld 5.16*: [@LevA10] onderzochten of luisteraars minder geloof hechten 
aan sprekers met een
vreemd buitenlands accent in de uitspraak van het Engels. Voor de
stimuli lieten ze zinnen uitspreken (bv. *A giraffe can hold more water
than a camel*) door verschillende sprekers zonder enig accent, met licht
accent, of met sterk accent. Luisteraars (moedertaal-sprekers van het
Engels) gaven aan in welke mate ze dachten dat de gesproken zin waar
was. De resultaten lieten zien dat de luisteraars de zinnen beoordeelden
als minder waar, als de zin was gesproken door een spreker met een
vreemd buitenlands accent.

---

We mogen aannemen dat deze uitkomst gegeneraliseerd kan worden *naar* de
beoogde doelgroep, nl. alle moedertaal-luisteraars van het Amerikaans
Engels. Deze generalisatie kan worden gemaakt ondanks de mogelijkheid
dat verschillende luisteraars misschien in verschillende mate beïnvloed
werden door het buitenlandse accent van de spreker.

Wellicht zou een latere analyse kunnen laten zien dat er verschil is
tussen vrouwelijke en mannelijke luisteraars. Het is denkbaar dat
vrouwen en mannen verschillen in hun gevoeligheid voor het accent van de
spreker. Zo'n (denkbeeldige) uitkomst zou laten zien dat er niet
gegeneraliseerd mag worden *over* deel-populaties binnen de doelgroep,
hoewel er wel gegeneraliseerd kon worden *naar* de doelgroep.

In het (toegepast) taalwetenschappelijk onderzoek proberen onderzoekers
doorgaans om *tegelijkertijd* te generaliseren naar *twee* populaties
van eenheden, nl. van personen (c.q. scholen of families) *en stimuli*
(woorden, zinnen, teksten, enz). We willen aannemelijk maken dat de
resultaten niet alleen geldig zijn voor de onderzochte taalgebruikers,
maar ook voor andere taalgebruikers. Tegelijkertijd willen we ook
aannemelijk maken dat de resultaten niet alleen geldig zijn voor de
onderzochte stimuli, maar ook voor andere vergelijkbaar taalmateriaal
waaruit de steekproef van stimuli is getrokken. Die gelijktijdige
generalisatie vereist een complex onderzoeksontwerp, doordat er
herhaalde observaties zijn binnen proefpersonen (meerdere oordelen van
eenzelfde proefpersoon) en binnen stimuli (meerdere oordelen over
dezelfde stimulus). Stimuli, proefpersonen en condities worden
vervolgens slim gecombineerd om de interne validiteit zo goed mogelijk
te beschermen. Uiteraard vereist de generalisatie naar ander
taalmateriaal wel, dat de stimuli willekeurig zijn geselecteerd uit de
(soms oneindig grote) populatie van al het mogelijke taalmateriaal (zie
Hoofdstuk \@ref(ch:steekproeftrekking)).

[^fn05-1]: De experimentator is degene die een experiment afneemt bij een proefpersoon. De experimentator kan een andere persoon zijn dan de onderzoekers die de onderzoekshypothesen hebben opgesteld en/of proefpersonen hebben gerecruteerd.
