--- 
title: "Kwantitatieve Methoden en Statistiek"
author:
  name: Hugo Quené \& Huub van den Bergh
  affiliation: Universiteit Utrecht
  email: h.quene@uu.nl
date: "Versie gecompileerd op `r format(Sys.time(), '%d %b %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, hhmhto.bib, pandoc.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/KMS-NL
description: "Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek 1 (TL2V17002, TW2V19002, TL2V23004), Dept Talen Literatuur en Communicatie, Universiteit Utrecht."

---

# Voorwoord {-}

Data spelen een steeds belangrijker rol, ook in de geesteswetenschappen. 
De beschikbaarheid van digitale gegevens  (o.a. tekst, spraak, video, en gedragsregistraties) leidt tot nieuwe onderzoeksvragen, die vooral met kwantitatieve methoden beantwoord worden. 
Dit boek biedt onderzoekers en studenten een overzicht en inleiding van de belangrijkste kwantitatieve methoden en statistische technieken in de geesteswetenschappen. Het boek geeft de lezer een stevig methodologisch fundament voor kwantitatief onderzoek, en biedt een inleiding in de meest gebruikte statistische technieken om gegevens te beschrijven en om hypothesen te toetsen. Daarmee is de lezer ook in staat om kwantitatief onderzoek kritisch te beoordelen.

Dit tekstboek wordt gebruikt als leesstof bij de cursus *Methoden en Statistiek 1* aan de Universiteit Utrecht. Het boek is tevens bruikbaar voor zelfstudie op inleidend niveau, voor iedereen die meer wil weten over kwantitatieve methoden en statistiek. 

De hoofdtekst is gevrijwaard van wiskundige afleidingen en formules, die voor geesteswetenschappers immers weinig bruikbaar zijn. De uitleg is vooral conceptueel, en rijk aan voorbeelden van geesteswetenschappelijk onderzoek. Waar nodig worden formules aangeboden in een aparte paragraaf. 

Dit boek bevat ook aanwijzingen over hoe de besproken statistische analyses en visualisaties uitgevoerd kunnen worden in drie statistische pakketten, nl. SPSS, JASP, en R. In §\@ref(sec:vooruitblik) worden deze pakketten nader besproken. De technische aanwijzingen voor het gebruik van deze pakketten staan eveneens los van de hoofdtekst, in afzonderlijke paragrafen. 

Graag willen we onze mede-docenten danken voor de vele discussies en voorbeelden die op enige wijze verwerkt zijn in dit tekstboek. Onze studenten danken we voor hun nieuwsgierigheid en nauwkeurigheid die geleid heeft tot deze versie van dit tekstboek.  

Ook betonen wij grote dank aan 
Gerrit Bloothooft, 
Margot van den Berg, 
Willemijn Heeren, 
Rianne Kraakman, 
Caspar van Lissa,
Els Rose, 
Tobias Quené, 
Kirsten Schutter, 
Marijn Struiksma, 
Tara Super, 
en Joanna Wall,
voor hun adviezen, data, en/of commentaar bij eerdere versies.

Wij danken Rianne Kraakman voor het schrijven van de subsecties met JASP-instructies (versie 1.2.0), en Tara Super voor redactiewerk (versie 1.3.0). 

Onze bijzondere dank gaat tenslotte uit naar Marijn Struiksma, voor haar inspiratie bij dit project en voor het coördineren van de JASP-uitbreidingen en de Engelse vertaling. 

versie 1.1.1+: februari 2021\
versie 1.2.0: juni 2021\
versie 1.3.0: mei 2022

Hugo Quené, <https://www.hugoquene.nl>

Huub van den Bergh

---

## In English please? {-}

Dit is de Nederlandstalige versie van het tekstboek, getiteld *Kwantitatieve Methoden en Statistiek*.

You are currently reading the Dutch version of the textbook. 
The parallel English version of this textbook, titled *Quantitative Methods and Statistics*, is available at <https://hugoquene.github.io/QMS-EN/>


## Notatie {-}

In aansluiting op het internationale gebruik en op de conventies van Engelstalige tijdschriften gebruiken we de punt als decimaalteken; we schrijven dus $\frac{3}{2}=1.5$. Hierbij is een waarschuwing op zijn plaats: het decimale symbool kan verschillen tussen computers, en zelfs tussen programma's op dezelfde computer. Controleer dus welk decimaal symbool gebruikt wordt door (elk programma op) jouw computer.


## Licentie {-}

This document is licensed under the _GNU GPL 3_ license (for details see 
https://www.gnu.org/licenses/gpl-3.0.en.html). 

## Citatie {-}

Gebruik een van de volgende manieren om te verwijzen naar dit tekstboek (in APA-formaat), met de datum van raadpleging:

Quené, H. \& Van den Bergh, H. (2022). *Kwantitatieve Methoden en Statistiek*. 
Geraadpleegd op 13 mei 2022 via https://hugoquene.github.io/KMS-NL/ .

Quené, H. \& Van den Bergh, H. (2022). *Kwantitatieve Methoden en Statistiek* [in Dutch]. 
Retrieved 13 May 2022 from https://hugoquene.github.io/KMS-NL/ .

## Technische details {-}

Alle materialen voor dit tekstboek zijn beschikbaar via <https://doi.org/10.5281/zenodo.4113980> of  rechtstreeks via <https://github.com/hugoquene/KMS-NL>: men vinde daar andere versies van deze tekst (EPUB, PDF, HTML), de broncode (Rmarkdown en R) van de tekst inclusief figuren en voorbeelden en uitwerkingen, de databestanden die worden gebruikt in tekst, en de figuren als afzonderlijke bestanden.

De tekst is geschreven in LaTeX, en daarna omgezet naar Rmarkdown, met behulp van `pandoc` [@pandoc] en het `bookdown` package [@R-bookdown] in [Rstudio](https://www.rstudio.com).\

## Over de auteurs {-}

Beide auteurs zijn verbonden aan de Faculteit Geesteswetenschappen van de Universiteit Utrecht. HQ is hoogleraar Kwantitatieve Methoden van Empirisch Onderzoek in de Geesteswetenschappen, en geeft daarnaast leiding aan het Centre for Digital Humanities. HvdB is hoogleraar Didactiek en Toetsing van het Taalvaardigheidsonderwijs, en is daarnaast vaksectievoorzitter Nederlands bij het College voor Toetsen en Examens (CvTE).

```{r include=FALSE}
# automatically create a bib database for R packages
require(lattice)
require(nnet)
require(MASS) # in Ch10, MASS::mvrnorm
require(hqmisc) 
knitr::write_bib( c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
