<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Hoofdstuk 16 Chi-kwadraat-toetsen | Kwantitatieve Methoden en Statistiek</title>
  <meta name="description" content="Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek 1 (TL2V17002), BA Taalwetenschap, Universiteit Utrecht." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Hoofdstuk 16 Chi-kwadraat-toetsen | Kwantitatieve Methoden en Statistiek" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek 1 (TL2V17002), BA Taalwetenschap, Universiteit Utrecht." />
  <meta name="github-repo" content="rstudio/KMS-NL" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Hoofdstuk 16 Chi-kwadraat-toetsen | Kwantitatieve Methoden en Statistiek" />
  
  <meta name="twitter:description" content="Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek 1 (TL2V17002), BA Taalwetenschap, Universiteit Utrecht." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch-variantieanalyse.html"/>
<link rel="next" href="ch-andere-nonpar-toetsen.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Kwantitatieve Methoden en Statistiek</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Voorwoord</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#in-english-please"><i class="fa fa-check"></i>In English please?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notatie"><i class="fa fa-check"></i>Notatie</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#licentie"><i class="fa fa-check"></i>Licentie</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citatie"><i class="fa fa-check"></i>Citatie</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#technische-details"><i class="fa fa-check"></i>Technische details</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#over-de-auteurs"><i class="fa fa-check"></i>Over de auteurs</a></li>
</ul></li>
<li class="part"><span><b>Deel I: Methodologie</b></span></li>
<li class="chapter" data-level="1" data-path="ch-inleiding.html"><a href="ch-inleiding.html"><i class="fa fa-check"></i><b>1</b> Inleiding</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:wetenschappelijk-onderzoek"><i class="fa fa-check"></i><b>1.1</b> Wetenschappelijk onderzoek</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:theorie"><i class="fa fa-check"></i><b>1.1.1</b> Theorie</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:paradigmata"><i class="fa fa-check"></i><b>1.2</b> Paradigmata</a></li>
<li class="chapter" data-level="1.3" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:instrumentatie-onderzoek"><i class="fa fa-check"></i><b>1.3</b> Instrumentatie-onderzoek</a></li>
<li class="chapter" data-level="1.4" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:beschrijvend-onderzoek"><i class="fa fa-check"></i><b>1.4</b> Beschrijvend onderzoek</a></li>
<li class="chapter" data-level="1.5" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:experimenteel-onderzoek"><i class="fa fa-check"></i><b>1.5</b> Experimenteel onderzoek</a></li>
<li class="chapter" data-level="1.6" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:vooruitblik"><i class="fa fa-check"></i><b>1.6</b> Vooruitblik</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html"><i class="fa fa-check"></i><b>2</b> Hypothese-toetsend onderzoek</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#inleiding"><i class="fa fa-check"></i><b>2.1</b> Inleiding</a></li>
<li class="chapter" data-level="2.2" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:variabelen"><i class="fa fa-check"></i><b>2.2</b> Variabelen</a></li>
<li class="chapter" data-level="2.3" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:onafhankelijkeafhankelijkevariabelen"><i class="fa fa-check"></i><b>2.3</b> Onafhankelijke en afhankelijke variabelen</a></li>
<li class="chapter" data-level="2.4" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:falsificatie"><i class="fa fa-check"></i><b>2.4</b> Falsificatie en nul-hypothese</a></li>
<li class="chapter" data-level="2.5" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:empirischecyclus"><i class="fa fa-check"></i><b>2.5</b> De empirische cyclus</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#observatie"><i class="fa fa-check"></i><b>2.5.1</b> observatie</a></li>
<li class="chapter" data-level="2.5.2" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#inductie"><i class="fa fa-check"></i><b>2.5.2</b> inductie</a></li>
<li class="chapter" data-level="2.5.3" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#deductie"><i class="fa fa-check"></i><b>2.5.3</b> deductie</a></li>
<li class="chapter" data-level="2.5.4" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#toetsing"><i class="fa fa-check"></i><b>2.5.4</b> toetsing</a></li>
<li class="chapter" data-level="2.5.5" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#evaluatie"><i class="fa fa-check"></i><b>2.5.5</b> evaluatie</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:keuzemomenten"><i class="fa fa-check"></i><b>2.6</b> Keuzemomenten</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch-integriteit.html"><a href="ch-integriteit.html"><i class="fa fa-check"></i><b>3</b> Integriteit</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch-integriteit.html"><a href="ch-integriteit.html#sec:integriteit-inleiding"><i class="fa fa-check"></i><b>3.1</b> Inleiding</a></li>
<li class="chapter" data-level="3.2" data-path="ch-integriteit.html"><a href="ch-integriteit.html#sec:ontwerp"><i class="fa fa-check"></i><b>3.2</b> Ontwerp</a></li>
<li class="chapter" data-level="3.3" data-path="ch-integriteit.html"><a href="ch-integriteit.html#proefpersonen-en-informanten"><i class="fa fa-check"></i><b>3.3</b> Proefpersonen en informanten</a></li>
<li class="chapter" data-level="3.4" data-path="ch-integriteit.html"><a href="ch-integriteit.html#gegevens"><i class="fa fa-check"></i><b>3.4</b> Gegevens</a></li>
<li class="chapter" data-level="3.5" data-path="ch-integriteit.html"><a href="ch-integriteit.html#teksten"><i class="fa fa-check"></i><b>3.5</b> Teksten</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html"><i class="fa fa-check"></i><b>4</b> Meetniveau</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html#inleiding-1"><i class="fa fa-check"></i><b>4.1</b> Inleiding</a></li>
<li class="chapter" data-level="4.2" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html#sec:nominaal"><i class="fa fa-check"></i><b>4.2</b> Nominaal</a></li>
<li class="chapter" data-level="4.3" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html#sec:ordinaal"><i class="fa fa-check"></i><b>4.3</b> Ordinaal</a></li>
<li class="chapter" data-level="4.4" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html#sec:interval"><i class="fa fa-check"></i><b>4.4</b> Interval</a></li>
<li class="chapter" data-level="4.5" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html#sec:ratio"><i class="fa fa-check"></i><b>4.5</b> Ratio</a></li>
<li class="chapter" data-level="4.6" data-path="ch-Meetniveau.html"><a href="ch-Meetniveau.html#sec:ordeningvanmeetniveaus"><i class="fa fa-check"></i><b>4.6</b> Ordening van meetniveaus</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch-validiteit.html"><a href="ch-validiteit.html"><i class="fa fa-check"></i><b>5</b> Validiteit</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch-validiteit.html"><a href="ch-validiteit.html#inleiding-2"><i class="fa fa-check"></i><b>5.1</b> Inleiding</a></li>
<li class="chapter" data-level="5.2" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:causaliteit"><i class="fa fa-check"></i><b>5.2</b> Causaliteit</a></li>
<li class="chapter" data-level="5.3" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:validiteit"><i class="fa fa-check"></i><b>5.3</b> Validiteit</a></li>
<li class="chapter" data-level="5.4" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:internevaliditeit"><i class="fa fa-check"></i><b>5.4</b> Interne validiteit</a></li>
<li class="chapter" data-level="5.5" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:constructvaliditeit"><i class="fa fa-check"></i><b>5.5</b> Constructvaliditeit</a></li>
<li class="chapter" data-level="5.6" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:externevaliditeit"><i class="fa fa-check"></i><b>5.6</b> Externe validiteit</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html"><i class="fa fa-check"></i><b>6</b> Ontwerp</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:ontwerp-inleiding"><i class="fa fa-check"></i><b>6.1</b> Inleiding</a></li>
<li class="chapter" data-level="6.2" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:tussenbinnenproefpersonen"><i class="fa fa-check"></i><b>6.2</b> Tussen of binnen ?</a></li>
<li class="chapter" data-level="6.3" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#het-one-shot-single-case-ontwerp"><i class="fa fa-check"></i><b>6.3</b> Het one-shot single-case-ontwerp</a></li>
<li class="chapter" data-level="6.4" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#het-één-groep-voormeting-nameting-ontwerp"><i class="fa fa-check"></i><b>6.4</b> Het één-groep-voormeting-nameting-ontwerp</a></li>
<li class="chapter" data-level="6.5" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:voormeting-nameting-controlegroep-ontwerp"><i class="fa fa-check"></i><b>6.5</b> Het voormeting-nameting-controlegroep-ontwerp</a></li>
<li class="chapter" data-level="6.6" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:solomon-vier-groepen-ontwerp"><i class="fa fa-check"></i><b>6.6</b> Het Solomon-vier-groepen-ontwerp</a></li>
<li class="chapter" data-level="6.7" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#het-nameting-controlegroep-ontwerp"><i class="fa fa-check"></i><b>6.7</b> Het nameting-controlegroep-ontwerp</a></li>
<li class="chapter" data-level="6.8" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:ontwerp-factorieel"><i class="fa fa-check"></i><b>6.8</b> Factoriële ontwerpen</a></li>
<li class="chapter" data-level="6.9" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:afhankelijkegroepen"><i class="fa fa-check"></i><b>6.9</b> Afhankelijke- en onafhankelijke-groepen-ontwerp</a></li>
<li class="chapter" data-level="6.10" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#onderzoek-ontwerpen"><i class="fa fa-check"></i><b>6.10</b> Onderzoek ontwerpen</a></li>
<li class="chapter" data-level="6.11" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#tenslotte"><i class="fa fa-check"></i><b>6.11</b> Tenslotte</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html"><i class="fa fa-check"></i><b>7</b> Steekproeven</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:gelegenheidssteekproef"><i class="fa fa-check"></i><b>7.1</b> Gelegenheidssteekproeven</a></li>
<li class="chapter" data-level="7.2" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:systematischesteekproef"><i class="fa fa-check"></i><b>7.2</b> Systematische steekproeven</a></li>
<li class="chapter" data-level="7.3" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:aselectesteekproef"><i class="fa fa-check"></i><b>7.3</b> Aselecte steekproeven</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#spss"><i class="fa fa-check"></i><b>7.3.1</b> SPSS</a></li>
<li class="chapter" data-level="7.3.2" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#jasp"><i class="fa fa-check"></i><b>7.3.2</b> JASP</a></li>
<li class="chapter" data-level="7.3.3" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#r"><i class="fa fa-check"></i><b>7.3.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:steekproefgrootte"><i class="fa fa-check"></i><b>7.4</b> Steekproefgrootte</a></li>
</ul></li>
<li class="part"><span><b>Deel II: Beschrijvende statistiek</b></span></li>
<li class="chapter" data-level="8" data-path="ch-frequenties.html"><a href="ch-frequenties.html"><i class="fa fa-check"></i><b>8</b> Frequenties</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch-frequenties.html"><a href="ch-frequenties.html#inleiding-3"><i class="fa fa-check"></i><b>8.1</b> Inleiding</a></li>
<li class="chapter" data-level="8.2" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:frequenties"><i class="fa fa-check"></i><b>8.2</b> Frequenties</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:intervallen"><i class="fa fa-check"></i><b>8.2.1</b> Intervallen</a></li>
<li class="chapter" data-level="8.2.2" data-path="ch-frequenties.html"><a href="ch-frequenties.html#spss-1"><i class="fa fa-check"></i><b>8.2.2</b> SPSS</a></li>
<li class="chapter" data-level="8.2.3" data-path="ch-frequenties.html"><a href="ch-frequenties.html#jasp-1"><i class="fa fa-check"></i><b>8.2.3</b> JASP</a></li>
<li class="chapter" data-level="8.2.4" data-path="ch-frequenties.html"><a href="ch-frequenties.html#r-1"><i class="fa fa-check"></i><b>8.2.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:staafdiagrammen"><i class="fa fa-check"></i><b>8.3</b> Staafdiagrammen</a></li>
<li class="chapter" data-level="8.4" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:histogrammen"><i class="fa fa-check"></i><b>8.4</b> Histogrammen</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="ch-frequenties.html"><a href="ch-frequenties.html#spss-2"><i class="fa fa-check"></i><b>8.4.1</b> SPSS</a></li>
<li class="chapter" data-level="8.4.2" data-path="ch-frequenties.html"><a href="ch-frequenties.html#jasp-2"><i class="fa fa-check"></i><b>8.4.2</b> JASP</a></li>
<li class="chapter" data-level="8.4.3" data-path="ch-frequenties.html"><a href="ch-frequenties.html#r-2"><i class="fa fa-check"></i><b>8.4.3</b> R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html"><i class="fa fa-check"></i><b>9</b> Centrum en spreiding</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#inleiding-4"><i class="fa fa-check"></i><b>9.1</b> Inleiding</a></li>
<li class="chapter" data-level="9.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#symbolen"><i class="fa fa-check"></i><b>9.2</b> Symbolen</a></li>
<li class="chapter" data-level="9.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#centrummaten"><i class="fa fa-check"></i><b>9.3</b> Centrummaten</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:gemiddelde"><i class="fa fa-check"></i><b>9.3.1</b> gemiddelde</a></li>
<li class="chapter" data-level="9.3.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:mediaan"><i class="fa fa-check"></i><b>9.3.2</b> mediaan</a></li>
<li class="chapter" data-level="9.3.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#modus"><i class="fa fa-check"></i><b>9.3.3</b> modus</a></li>
<li class="chapter" data-level="9.3.4" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:harmonischgemiddelde"><i class="fa fa-check"></i><b>9.3.4</b> harmonisch gemiddelde</a></li>
<li class="chapter" data-level="9.3.5" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#gewinsoriseerde-gemiddelde"><i class="fa fa-check"></i><b>9.3.5</b> gewinsoriseerde gemiddelde</a></li>
<li class="chapter" data-level="9.3.6" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#getrimde-gemiddelde"><i class="fa fa-check"></i><b>9.3.6</b> getrimde gemiddelde</a></li>
<li class="chapter" data-level="9.3.7" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#vergelijking-van-centrummaten"><i class="fa fa-check"></i><b>9.3.7</b> vergelijking van centrummaten</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:kwartielen-en-boxplots"><i class="fa fa-check"></i><b>9.4</b> Kwartielen en boxplots</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#kwartielen"><i class="fa fa-check"></i><b>9.4.1</b> Kwartielen</a></li>
<li class="chapter" data-level="9.4.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:uitbijters"><i class="fa fa-check"></i><b>9.4.2</b> Uitbijters</a></li>
<li class="chapter" data-level="9.4.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:boxplot"><i class="fa fa-check"></i><b>9.4.3</b> Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:spreidingsmaten"><i class="fa fa-check"></i><b>9.5</b> Spreidingsmaten</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:variantie"><i class="fa fa-check"></i><b>9.5.1</b> variantie</a></li>
<li class="chapter" data-level="9.5.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:standaarddeviatie"><i class="fa fa-check"></i><b>9.5.2</b> standaarddeviatie</a></li>
<li class="chapter" data-level="9.5.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#mad"><i class="fa fa-check"></i><b>9.5.3</b> MAD</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:significantecijfers"><i class="fa fa-check"></i><b>9.6</b> Over significante cijfers</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:significantecijfers-gemiddelde"><i class="fa fa-check"></i><b>9.6.1</b> Gemiddelde en standaarddeviatie</a></li>
<li class="chapter" data-level="9.6.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#percentages"><i class="fa fa-check"></i><b>9.6.2</b> Percentages</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:robuustefficient"><i class="fa fa-check"></i><b>9.7</b> Keuzemoment</a></li>
<li class="chapter" data-level="9.8" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:standaardscores"><i class="fa fa-check"></i><b>9.8</b> Standaardscores</a></li>
<li class="chapter" data-level="9.9" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#spss-3"><i class="fa fa-check"></i><b>9.9</b> SPSS</a></li>
<li class="chapter" data-level="9.10" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#jasp-3"><i class="fa fa-check"></i><b>9.10</b> JASP</a></li>
<li class="chapter" data-level="9.11" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#r-3"><i class="fa fa-check"></i><b>9.11</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html"><i class="fa fa-check"></i><b>10</b> Kansverdelingen</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:kansen"><i class="fa fa-check"></i><b>10.1</b> Kansen</a></li>
<li class="chapter" data-level="10.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:binomiaalverdeling"><i class="fa fa-check"></i><b>10.2</b> Binomiale kansverdeling</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#formules"><i class="fa fa-check"></i><b>10.2.1</b> formules</a></li>
<li class="chapter" data-level="10.2.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#jasp-4"><i class="fa fa-check"></i><b>10.2.2</b> JASP</a></li>
<li class="chapter" data-level="10.2.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#r-4"><i class="fa fa-check"></i><b>10.2.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:normaalverdeling"><i class="fa fa-check"></i><b>10.3</b> Normale kansverdeling</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#formules-1"><i class="fa fa-check"></i><b>10.3.1</b> formules</a></li>
<li class="chapter" data-level="10.3.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#jasp-5"><i class="fa fa-check"></i><b>10.3.2</b> JASP</a></li>
<li class="chapter" data-level="10.3.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#r-5"><i class="fa fa-check"></i><b>10.3.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:isvarnormaalverdeeld"><i class="fa fa-check"></i><b>10.4</b> Heeft mijn variabele een normale kansverdeling?</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#spss-4"><i class="fa fa-check"></i><b>10.4.1</b> SPSS</a></li>
<li class="chapter" data-level="10.4.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#jasp-6"><i class="fa fa-check"></i><b>10.4.2</b> JASP</a></li>
<li class="chapter" data-level="10.4.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#r-6"><i class="fa fa-check"></i><b>10.4.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:watalsnietnormaal"><i class="fa fa-check"></i><b>10.5</b> Wat als mijn variabele niet normaal verdeeld is?</a></li>
<li class="chapter" data-level="10.6" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:CentraalLimietTheorema"><i class="fa fa-check"></i><b>10.6</b> Kansverdeling van gemiddelde</a></li>
<li class="chapter" data-level="10.7" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:betrouwbaarheidsinterval-gemiddelde"><i class="fa fa-check"></i><b>10.7</b> Betrouwbaarheidsinterval van het gemiddelde</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#formules-2"><i class="fa fa-check"></i><b>10.7.1</b> formules</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch-samenhang.html"><a href="ch-samenhang.html"><i class="fa fa-check"></i><b>11</b> Samenhang</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#inleiding-5"><i class="fa fa-check"></i><b>11.1</b> Inleiding</a></li>
<li class="chapter" data-level="11.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:Pearson"><i class="fa fa-check"></i><b>11.2</b> Pearson product-moment-correlatie</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#formules-3"><i class="fa fa-check"></i><b>11.2.1</b> Formules</a></li>
<li class="chapter" data-level="11.2.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-5"><i class="fa fa-check"></i><b>11.2.2</b> SPSS</a></li>
<li class="chapter" data-level="11.2.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-7"><i class="fa fa-check"></i><b>11.2.3</b> JASP</a></li>
<li class="chapter" data-level="11.2.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-7"><i class="fa fa-check"></i><b>11.2.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:regressie"><i class="fa fa-check"></i><b>11.3</b> Regressie</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:regressie-formules"><i class="fa fa-check"></i><b>11.3.1</b> Formules</a></li>
<li class="chapter" data-level="11.3.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-6"><i class="fa fa-check"></i><b>11.3.2</b> SPSS</a></li>
<li class="chapter" data-level="11.3.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-8"><i class="fa fa-check"></i><b>11.3.3</b> JASP</a></li>
<li class="chapter" data-level="11.3.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-8"><i class="fa fa-check"></i><b>11.3.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#invloedrijke-observaties"><i class="fa fa-check"></i><b>11.4</b> Invloedrijke observaties</a></li>
<li class="chapter" data-level="11.5" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:Spearman"><i class="fa fa-check"></i><b>11.5</b> Spearmans rangorde-correlatie</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#formules-4"><i class="fa fa-check"></i><b>11.5.1</b> Formules</a></li>
<li class="chapter" data-level="11.5.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-7"><i class="fa fa-check"></i><b>11.5.2</b> SPSS</a></li>
<li class="chapter" data-level="11.5.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-9"><i class="fa fa-check"></i><b>11.5.3</b> JASP</a></li>
<li class="chapter" data-level="11.5.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-9"><i class="fa fa-check"></i><b>11.5.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:Phi"><i class="fa fa-check"></i><b>11.6</b> Phi</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#formules-5"><i class="fa fa-check"></i><b>11.6.1</b> Formules</a></li>
<li class="chapter" data-level="11.6.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-8"><i class="fa fa-check"></i><b>11.6.2</b> SPSS</a></li>
<li class="chapter" data-level="11.6.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-10"><i class="fa fa-check"></i><b>11.6.3</b> JASP</a></li>
<li class="chapter" data-level="11.6.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-10"><i class="fa fa-check"></i><b>11.6.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:correlationcausation"><i class="fa fa-check"></i><b>11.7</b> Tenslotte</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html"><i class="fa fa-check"></i><b>12</b> Betrouwbaarheid</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#inleiding-6"><i class="fa fa-check"></i><b>12.1</b> Inleiding</a></li>
<li class="chapter" data-level="12.2" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#wat-is-betrouwbaarheid"><i class="fa fa-check"></i><b>12.2</b> Wat is betrouwbaarheid?</a></li>
<li class="chapter" data-level="12.3" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#testtheorie"><i class="fa fa-check"></i><b>12.3</b> Testtheorie</a></li>
<li class="chapter" data-level="12.4" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#interpretaties"><i class="fa fa-check"></i><b>12.4</b> Interpretaties</a></li>
<li class="chapter" data-level="12.5" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#methoden-om-betrouwbaarheid-te-schatten"><i class="fa fa-check"></i><b>12.5</b> Methoden om betrouwbaarheid te schatten</a></li>
<li class="chapter" data-level="12.6" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#betrouwbaarheid-tussen-beoordelaars"><i class="fa fa-check"></i><b>12.6</b> Betrouwbaarheid tussen beoordelaars</a></li>
<li class="chapter" data-level="12.7" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#betrouwbaarheid-en-constructvaliditeit"><i class="fa fa-check"></i><b>12.7</b> Betrouwbaarheid en constructvaliditeit</a></li>
<li class="chapter" data-level="12.8" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#spss-9"><i class="fa fa-check"></i><b>12.8</b> SPSS</a></li>
<li class="chapter" data-level="12.9" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#jasp-11"><i class="fa fa-check"></i><b>12.9</b> JASP</a></li>
<li class="chapter" data-level="12.10" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#r-11"><i class="fa fa-check"></i><b>12.10</b> R</a></li>
</ul></li>
<li class="part"><span><b>Deel III: Toetsende statistiek</b></span></li>
<li class="chapter" data-level="13" data-path="ch-toetsing.html"><a href="ch-toetsing.html"><i class="fa fa-check"></i><b>13</b> Toetsing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:toetsing-inleiding"><i class="fa fa-check"></i><b>13.1</b> Inleiding</a></li>
<li class="chapter" data-level="13.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-onesample"><i class="fa fa-check"></i><b>13.2</b> <span class="math inline">\(t\)</span>-toets voor enkele steekproef</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-vrijheidsgraden"><i class="fa fa-check"></i><b>13.2.1</b> vrijheidsgraden</a></li>
<li class="chapter" data-level="13.2.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-1"><i class="fa fa-check"></i><b>13.2.2</b> formules</a></li>
<li class="chapter" data-level="13.2.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-aannames"><i class="fa fa-check"></i><b>13.2.3</b> aannames</a></li>
<li class="chapter" data-level="13.2.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#spss-10"><i class="fa fa-check"></i><b>13.2.4</b> SPSS</a></li>
<li class="chapter" data-level="13.2.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:jaspttoetsenkel"><i class="fa fa-check"></i><b>13.2.5</b> JASP</a></li>
<li class="chapter" data-level="13.2.6" data-path="ch-toetsing.html"><a href="ch-toetsing.html#r-12"><i class="fa fa-check"></i><b>13.2.6</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:pgroterdannul"><i class="fa fa-check"></i><b>13.3</b> Overschrijdingskans <span class="math inline">\(p\)</span> is altijd groter dan nul</a></li>
<li class="chapter" data-level="13.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-eenzijdigtweezijdig"><i class="fa fa-check"></i><b>13.4</b> Eenzijdige en tweezijdige toetsen</a></li>
<li class="chapter" data-level="13.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:t-betrouwbaarheidsinterval-gemiddelde"><i class="fa fa-check"></i><b>13.5</b> Betrouwbaarheidsinterval van het gemiddelde</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-2"><i class="fa fa-check"></i><b>13.5.1</b> formules</a></li>
<li class="chapter" data-level="13.5.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#spss-11"><i class="fa fa-check"></i><b>13.5.2</b> SPSS</a></li>
<li class="chapter" data-level="13.5.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#jasp-12"><i class="fa fa-check"></i><b>13.5.3</b> JASP</a></li>
<li class="chapter" data-level="13.5.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#r-13"><i class="fa fa-check"></i><b>13.5.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-onafh"><i class="fa fa-check"></i><b>13.6</b> <span class="math inline">\(t\)</span>-toets voor twee onafhankelijke steekproeven</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-ongepaard-aannames"><i class="fa fa-check"></i><b>13.6.1</b> aannames</a></li>
<li class="chapter" data-level="13.6.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-formules"><i class="fa fa-check"></i><b>13.6.2</b> formules</a></li>
<li class="chapter" data-level="13.6.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:SPSS-ttoets-ongepaard"><i class="fa fa-check"></i><b>13.6.3</b> SPSS</a></li>
<li class="chapter" data-level="13.6.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:jaspttoetsongepaard"><i class="fa fa-check"></i><b>13.6.4</b> JASP</a></li>
<li class="chapter" data-level="13.6.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:R-ttoets-ongepaard"><i class="fa fa-check"></i><b>13.6.5</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-gepaard"><i class="fa fa-check"></i><b>13.7</b> <span class="math inline">\(t\)</span>-toets voor gepaarde waarnemingen</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#aannames-1"><i class="fa fa-check"></i><b>13.7.1</b> aannames</a></li>
<li class="chapter" data-level="13.7.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-4"><i class="fa fa-check"></i><b>13.7.2</b> formules</a></li>
<li class="chapter" data-level="13.7.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:SPSS-ttoets-gepaard"><i class="fa fa-check"></i><b>13.7.3</b> SPSS</a></li>
<li class="chapter" data-level="13.7.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:jaspttoetsgepaard"><i class="fa fa-check"></i><b>13.7.4</b> JASP</a></li>
<li class="chapter" data-level="13.7.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:R-ttoets-gepaard"><i class="fa fa-check"></i><b>13.7.5</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-effectgrootte"><i class="fa fa-check"></i><b>13.8</b> Effectgrootte</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-5"><i class="fa fa-check"></i><b>13.8.1</b> formules</a></li>
<li class="chapter" data-level="13.8.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#spss-13-2"><i class="fa fa-check"></i><b>13.8.2</b> SPSS</a></li>
<li class="chapter" data-level="13.8.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#jasp-13"><i class="fa fa-check"></i><b>13.8.3</b> JASP</a></li>
<li class="chapter" data-level="13.8.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#r-14"><i class="fa fa-check"></i><b>13.8.4</b> R</a></li>
<li class="chapter" data-level="13.8.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:betrouwbaarheidsinterval-effectgrootte"><i class="fa fa-check"></i><b>13.8.5</b> Betrouwbaarheidsinterval van de effectgrootte</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch-power.html"><a href="ch-power.html"><i class="fa fa-check"></i><b>14</b> Power</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch-power.html"><a href="ch-power.html#sec:power-inleiding"><i class="fa fa-check"></i><b>14.1</b> Inleiding</a></li>
<li class="chapter" data-level="14.2" data-path="ch-power.html"><a href="ch-power.html#sec:effectgrootte-power"><i class="fa fa-check"></i><b>14.2</b> Verband tussen effectgrootte en power</a></li>
<li class="chapter" data-level="14.3" data-path="ch-power.html"><a href="ch-power.html#sec:steekproefgrootte-power"><i class="fa fa-check"></i><b>14.3</b> Verband tussen steekproefgrootte en power</a></li>
<li class="chapter" data-level="14.4" data-path="ch-power.html"><a href="ch-power.html#sec:significantieniveau-power"><i class="fa fa-check"></i><b>14.4</b> Verband tussen significantieniveau en power</a></li>
<li class="chapter" data-level="14.5" data-path="ch-power.html"><a href="ch-power.html#nadelen-van-onvoldoende-power"><i class="fa fa-check"></i><b>14.5</b> Nadelen van onvoldoende power</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html"><i class="fa fa-check"></i><b>15</b> Variantieanalyse</a>
<ul>
<li class="chapter" data-level="15.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:inleiding"><i class="fa fa-check"></i><b>15.1</b> Inleiding</a></li>
<li class="chapter" data-level="15.2" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-voorbeelden"><i class="fa fa-check"></i><b>15.2</b> Enkele voorbeelden</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#aannames"><i class="fa fa-check"></i><b>15.2.1</b> aannames</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#eén-weg-variantieanalyse"><i class="fa fa-check"></i><b>15.3</b> Eén-weg-variantieanalyse</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-uitleg"><i class="fa fa-check"></i><b>15.3.1</b> Een intuïtieve uitleg</a></li>
<li class="chapter" data-level="15.3.2" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-formeel"><i class="fa fa-check"></i><b>15.3.2</b> Een formele uitleg</a></li>
<li class="chapter" data-level="15.3.3" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-effectgrootte"><i class="fa fa-check"></i><b>15.3.3</b> Effectgrootte</a></li>
<li class="chapter" data-level="15.3.4" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-gericht"><i class="fa fa-check"></i><b>15.3.4</b> Gerichte vergelijkingen</a></li>
<li class="chapter" data-level="15.3.5" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-posthoc"><i class="fa fa-check"></i><b>15.3.5</b> Post-hoc vergelijkingen</a></li>
<li class="chapter" data-level="15.3.6" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#spss-12"><i class="fa fa-check"></i><b>15.3.6</b> SPSS</a></li>
<li class="chapter" data-level="15.3.7" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#jasp-14"><i class="fa fa-check"></i><b>15.3.7</b> JASP</a></li>
<li class="chapter" data-level="15.3.8" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#r-15"><i class="fa fa-check"></i><b>15.3.8</b> R</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#tweeweg-variantieanalyse"><i class="fa fa-check"></i><b>15.4</b> Tweeweg-variantieanalyse</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#een-intuïtieve-uitleg"><i class="fa fa-check"></i><b>15.4.1</b> Een intuïtieve uitleg</a></li>
<li class="chapter" data-level="15.4.2" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#een-formele-uitleg"><i class="fa fa-check"></i><b>15.4.2</b> Een formele uitleg</a></li>
<li class="chapter" data-level="15.4.3" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#spss-13"><i class="fa fa-check"></i><b>15.4.3</b> SPSS</a></li>
<li class="chapter" data-level="15.4.4" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#jasp-15"><i class="fa fa-check"></i><b>15.4.4</b> JASP</a></li>
<li class="chapter" data-level="15.4.5" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#r-16"><i class="fa fa-check"></i><b>15.4.5</b> R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html"><i class="fa fa-check"></i><b>16</b> Chi-kwadraat-toetsen</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#sec:h16inleiding"><i class="fa fa-check"></i><b>16.1</b> Inleiding</a></li>
<li class="chapter" data-level="16.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#sec:chi2gof"><i class="fa fa-check"></i><b>16.2</b> <span class="math inline">\(\chi^2\)</span>-toets voor “goodness of fit” in enkele steekproef</a></li>
<li class="chapter" data-level="16.3" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#chi2-toets-voor-homogeniteit-van-een-variabele-in-meerdere-steekproeven"><i class="fa fa-check"></i><b>16.3</b> <span class="math inline">\(\chi^2\)</span>-toets voor homogeniteit van een variabele in meerdere steekproeven</a></li>
<li class="chapter" data-level="16.4" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#chi2-toets-voor-verband-tussen-twee-variabelen-in-enkele-steekproef"><i class="fa fa-check"></i><b>16.4</b> <span class="math inline">\(\chi^2\)</span>-toets voor verband tussen twee variabelen in enkele steekproef</a></li>
<li class="chapter" data-level="16.5" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#sec:chi2toets-aannames"><i class="fa fa-check"></i><b>16.5</b> aannames</a></li>
<li class="chapter" data-level="16.6" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#formule"><i class="fa fa-check"></i><b>16.6</b> formule</a></li>
<li class="chapter" data-level="16.7" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#spss-14"><i class="fa fa-check"></i><b>16.7</b> SPSS</a>
<ul>
<li class="chapter" data-level="16.7.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-voorbereiding"><i class="fa fa-check"></i><b>16.7.1</b> goodness of fit: voorbereiding</a></li>
<li class="chapter" data-level="16.7.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-toetsing"><i class="fa fa-check"></i><b>16.7.2</b> goodness of fit: toetsing</a></li>
<li class="chapter" data-level="16.7.3" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-voorbereiding"><i class="fa fa-check"></i><b>16.7.3</b> kruistabellen: voorbereiding</a></li>
<li class="chapter" data-level="16.7.4" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-toetsing"><i class="fa fa-check"></i><b>16.7.4</b> kruistabellen: toetsing</a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#jasp-16"><i class="fa fa-check"></i><b>16.8</b> JASP</a>
<ul>
<li class="chapter" data-level="16.8.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-voorbereiding-1"><i class="fa fa-check"></i><b>16.8.1</b> goodness of fit: voorbereiding</a></li>
<li class="chapter" data-level="16.8.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-toetsing-1"><i class="fa fa-check"></i><b>16.8.2</b> goodness of fit: toetsing</a></li>
<li class="chapter" data-level="16.8.3" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-voorbereiding-1"><i class="fa fa-check"></i><b>16.8.3</b> kruistabellen: voorbereiding</a></li>
<li class="chapter" data-level="16.8.4" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-toetsing-1"><i class="fa fa-check"></i><b>16.8.4</b> kruistabellen: toetsing</a></li>
</ul></li>
<li class="chapter" data-level="16.9" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#r-17"><i class="fa fa-check"></i><b>16.9</b> R</a>
<ul>
<li class="chapter" data-level="16.9.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-toetsing-2"><i class="fa fa-check"></i><b>16.9.1</b> goodness of fit: toetsing</a></li>
<li class="chapter" data-level="16.9.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-voorbereiding-en-toetsing"><i class="fa fa-check"></i><b>16.9.2</b> kruistabellen: voorbereiding en toetsing</a></li>
</ul></li>
<li class="chapter" data-level="16.10" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#effectgrootte-odds-ratio"><i class="fa fa-check"></i><b>16.10</b> Effectgrootte: odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html"><i class="fa fa-check"></i><b>17</b> Andere nonparametrische toetsen</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:h17inleiding"><i class="fa fa-check"></i><b>17.1</b> Inleiding</a></li>
<li class="chapter" data-level="17.2" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#gepaarde-observaties-enkele-steekproef"><i class="fa fa-check"></i><b>17.2</b> Gepaarde observaties, enkele steekproef</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:tekentoets"><i class="fa fa-check"></i><b>17.2.1</b> Tekentoets</a></li>
<li class="chapter" data-level="17.2.2" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:Wilcoxon-signed-rank"><i class="fa fa-check"></i><b>17.2.2</b> Wilcoxon signed-ranks test</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#onafhankelijke-observaties-meerdere-steekproeven"><i class="fa fa-check"></i><b>17.3</b> Onafhankelijke observaties, meerdere steekproeven</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#mediaantoets"><i class="fa fa-check"></i><b>17.3.1</b> Mediaantoets</a></li>
<li class="chapter" data-level="17.3.2" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:wilcoxon-rank-sum"><i class="fa fa-check"></i><b>17.3.2</b> Wilcoxon rank sum test, ofwel Mann-Whitney U test</a></li>
<li class="chapter" data-level="17.3.3" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#kruskall-wallis-h-test"><i class="fa fa-check"></i><b>17.3.3</b> Kruskall-Wallis H test</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Bijlagen</b></span></li>
<li class="chapter" data-level="A" data-path="app-randomgetallen.html"><a href="app-randomgetallen.html"><i class="fa fa-check"></i><b>A</b> Willekeurige getallen</a></li>
<li class="chapter" data-level="B" data-path="app-kritiekeZwaarden.html"><a href="app-kritiekeZwaarden.html"><i class="fa fa-check"></i><b>B</b> Standaard-normale kansverdeling</a></li>
<li class="chapter" data-level="C" data-path="app-kritieketwaarden.html"><a href="app-kritieketwaarden.html"><i class="fa fa-check"></i><b>C</b> Kritieke waarden van <span class="math inline">\(t\)</span>-verdeling</a></li>
<li class="chapter" data-level="D" data-path="app-kritiekechi2waarden.html"><a href="app-kritiekechi2waarden.html"><i class="fa fa-check"></i><b>D</b> Kritieke waarden van <span class="math inline">\(\chi^2\)</span>-verdeling</a></li>
<li class="chapter" data-level="" data-path="referenties.html"><a href="referenties.html"><i class="fa fa-check"></i>Referenties</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Gemaakt met bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Kwantitatieve Methoden en Statistiek</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch:chi-kwadraat-toetsen" class="section level1" number="16">
<h1><span class="header-section-number">Hoofdstuk 16</span> Chi-kwadraat-toetsen</h1>
<div id="sec:h16inleiding" class="section level2" number="16.1">
<h2><span class="header-section-number">16.1</span> Inleiding</h2>
<p>We zagen al eerder dat we niet altijd gebruik kunnen maken van een
parametrische toets zoals de <span class="math inline">\(t\)</span>-toets of variantie-analyse, omdat de verzamelde
gegevens niet voldoen aan de aannames. Als de verzamelde gegevens niet
op interval-niveau gemeten zijn (zie hoofdstuk
<a href="ch-Meetniveau.html#ch:Meetniveau">4</a>), of als de kansverdeling van de gegevens
verre van normaal is (zie
§<a href="ch-kansverdelingen.html#sec:watalsnietnormaal">10.5</a>), dan verdient een non-parametrische
toets de voorkeur boven zo’n parametrische toets. Als de verzamelde
gegevens wèl voldoen aan de aannames voor een parametrische toets, dan
is een non-parametrische toets minder gevoelig (conservatiever) dan een
parametrische toets, d.w.z. dat de non-parametrische toets een groter
effect vereist en/of een grotere steekproef vereist, en in het algemeen
minder power heeft dan een parametrische toets bij het opsporen van een
effect (zie hoofdstuk <a href="ch-power.html#ch:power">14</a>).</p>
<p>In dit hoofdstuk bespreken we de meest gebruikte non-parametrische
toets: de <span class="math inline">\(\chi^2\)</span>-toets.</p>
</div>
<div id="sec:chi2gof" class="section level2" number="16.2">
<h2><span class="header-section-number">16.2</span> <span class="math inline">\(\chi^2\)</span>-toets voor “goodness of fit” in enkele steekproef</h2>
<p>Gegevens van het nominale meetniveau worden vaak geanalyseerd met de
zgn. <span class="math inline">\(\chi^2\)</span>-toets (met de Griekse letter “chi”). Het aantal ogen op een dobbelsteen
is een voorbeeld van een afhankelijke variabele van nominaal meetniveau:
er is geen ordening tussen de zes zijden, en elke zijde van een
dobbelsteen heeft een even grote kans om als bovenzijde te verschijnen.
Stel, we gooien <span class="math inline">\(60\times\)</span> met een dobbelsteen, en vinden de volgende
frequenties van de zes mogelijke uitkomsten: <span class="math inline">\(14, 9, 11, 10, 15, 1\)</span>. Dit
is te beschouwen als een steekproef van <span class="math inline">\(n=60\)</span> worpen uit een oneindige
populatie van mogelijke worpen, en de hier gerapporteerde frequenties
van uitkomsten zijn te beschouwen als een kruistabel van 1 rij en 6
kolommen (d.i. 6 cellen). Hoe groot is de kans op deze verdeling van
uitkomsten? Is de dobbelsteen wel eerlijk?</p>
<p>De <span class="math inline">\(\chi^2\)</span>-toets is gebaseerd op de verschillen tussen de verwachte en geobserveerde
frequenties. Volgens de nul-hypothese (de dobbelsteen is eerlijk)
verwachten we 10 uitkomsten in iedere cel (<span class="math inline">\(60/6=10\)</span>), m.a.w. de
verwachte frequentie is identiek voor iedere cel (dat wordt een <em>uniforme</em> verdeling genoemd).
De geobserveerde
uitkomsten wijken af van de verwachte frequenties van uitkomsten, met
name omdat de uitkomst “zes” nauwelijks voorkomt in deze steekproef. Dat
zou natuurlijk ook toeval kunnen zijn. De <span class="math inline">\(\chi^2\)</span>-toets geeft aan hoe groot de kans is
op deze “scheve” verdeling van uitkomsten (of een nog schevere verdeling), als H0 waar is.
De verwachte
uitkomsten worden dus afgeleid uit een verdeling van de uitkomsten
volgens H0, en we onderzoeken hoe goed de geobserveerde uitkomsten
passen bij de verwachte uitkomsten. Deze vorm van de wordt daarom ook
aangeduid als een toets van de ‘goodness of fit’.</p>
<p>Voor dit voorbeeld vinden we als uitkomst van de toetsing <span class="math inline">\(\chi^2=12.44\)</span>
met 5 vrijheidsgraden (zie
§<a href="ch-toetsing.html#sec:ttoets-vrijheidsgraden">13.2.1</a> voor uitleg over
vrijheidsgraden), met <span class="math inline">\(p=.0297\)</span>. We laten deze kanswaarde meestal door de
computer uitrekenen, maar we kunnen die kans ook schatten via een tabel met kritieke <span class="math inline">\(\chi^2\)</span>-waarden, zie Bijlage <a href="app-kritiekechi2waarden.html#app:kritiekechi2waarden">D</a>, en voetnoot<a href="#fn35" class="footnote-ref" id="fnref35"><sup>35</sup></a>).
Als H0 waar is, dan hebben we slechts 3% kans om
deze uitslag te vinden (of een nog extremere verdeling van uitkomsten).
Deze gevonden significantie <span class="math inline">\(p\)</span> is kleiner dan <span class="math inline">\(\alpha=.05\)</span>, en dus
verwerpen we H0. We concluderen dat deze dobbelsteen niet eerlijk is: de
gevonden verdeling van uitkomsten wijkt significant af van de verwachte
verdeling volgens H0.</p>
</div>
<div id="chi2-toets-voor-homogeniteit-van-een-variabele-in-meerdere-steekproeven" class="section level2" number="16.3">
<h2><span class="header-section-number">16.3</span> <span class="math inline">\(\chi^2\)</span>-toets voor homogeniteit van een variabele in meerdere steekproeven</h2>
<p>De <span class="math inline">\(\chi^2\)</span>-toets is ook goed bruikbaar bij een onderzoeksontwerp met <em>een</em> nominale
variabele, die we geobserveerd hebben in twee of meer steekproeven. De
vraag is dan of de verdeling van de observaties over de categorieën
gelijk is voor de verschillende steekproeven. Deze toets is
vergelijkbaar met <span class="math inline">\(t\)</span>-toets de voor twee onafhankelijke steekproeven
(§<a href="ch-toetsing.html#sec:ttoets-onafh">13.6</a>). De aantallen observaties vatten we dan
doorgaans samen in een kruistabel met meerdere rijen voor de
verschillende steekproeven, en meerdere kolommen voor de categorieën van
de nominale afhankelijke variabele (zie ook
tabel <a href="ch-samenhang.html#tab:cito-kruis">11.3</a>).</p>
<p>De <span class="math inline">\(\chi^2\)</span>-toets is weer gebaseerd op de verschillen tussen de verwachte en
geobserveerde frequenties. Volgens de nul-hypothese (er is géén verschil
in verdeling tussen de twee steekproeven) zou de verdeling van
observaties over de kolommen ongeveer gelijk moeten zijn voor alle rijen
(en vice versa).</p>
</div>
<div id="chi2-toets-voor-verband-tussen-twee-variabelen-in-enkele-steekproef" class="section level2" number="16.4">
<h2><span class="header-section-number">16.4</span> <span class="math inline">\(\chi^2\)</span>-toets voor verband tussen twee variabelen in enkele steekproef</h2>
<p>Tenslotte is de <span class="math inline">\(\chi^2\)</span>-toets eveneens goed bruikbaar bij een onderzoeksontwerp met
<em>twee</em> nominale variabelen, die we geobserveerd hebben in een enkele
steekproef. De vraag is dan of de verdeling van observaties over
categorieën van de tweede variabele gelijk is voor de verschillende
categorieën van de eerste variabele (en vice versa). De aantallen
observaties vatten we wederom samen in een kruistabel met meerdere rijen
voor de categorieën van de eerste nominale variabele, en meerdere
kolommen voor de categorieën van de tweede nominale variabele.</p>
<p>De <span class="math inline">\(\chi^2\)</span>-toets is ook hier gebaseerd op de verschillen tussen de verwachte en
geobserveerde frequenties. Volgens de nul-hypothese (er is géén verband
tussen de twee nominale variabelen) zou de verdeling van observaties
over de rijen ongeveer gelijk moeten zijn voor alle kolommen, en vice
versa. Dat betekent echter <em>niet</em> dat we voor alle cellen dezelfde
frequentie verwachten. Dat wordt geïllusteerd in het volgende voorbeeld.</p>
<hr />
<blockquote>
<p><em>Voorbeeld 16.1</em>: In de vroege ochtend
van 15 april 1912 zonk de <em>Titanic</em> in de Atlantische Oceaan. Veel
opvarenden verloren het leven. De opvarenden waren te onderscheiden in
vier klassen (1st/2nd/3rd class passagiers, en crew). Was de uitkomst
van de ramp (opvarende heeft de ramp niet of wel overleefd) ongeveer gelijk voor personen van
deze vier klassen? De kruistabel <a href="ch-chi-kwadraat-toetsen.html#tab:titanic">16.1</a> geeft de verdelingen van uitkomsten.</p>
</blockquote>
<table>
<caption><span id="tab:titanic">Tabel 16.1: </span> Verdeling van opvarenden van de <em>Titanic</em> (<span class="math inline">\(N=2201\)</span>), naar klasse van overtocht en naar status als (niet/wel) overlevende. Gegevens ontleend aan dataset <code>Titanic</code> in R.</caption>
<thead>
<tr class="header">
<th align="left">klasse</th>
<th align="right">niet</th>
<th align="right">wel</th>
<th align="right">totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1st</td>
<td align="right">122</td>
<td align="right">203</td>
<td align="right">325</td>
</tr>
<tr class="even">
<td align="left">2nd</td>
<td align="right">167</td>
<td align="right">118</td>
<td align="right">285</td>
</tr>
<tr class="odd">
<td align="left">3rd</td>
<td align="right">528</td>
<td align="right">178</td>
<td align="right">706</td>
</tr>
<tr class="even">
<td align="left">crew</td>
<td align="right">673</td>
<td align="right">212</td>
<td align="right">885</td>
</tr>
<tr class="odd">
<td align="left">totaal</td>
<td align="right">1490</td>
<td align="right">711</td>
<td align="right">2201</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Bij de verwachte frequenties moeten we rekening houden met de
verschillende aantallen opvarenden in de verschillende klassen, en met
de ongelijke verdeling van uitkomsten (1490 niet-overlevenden en 711
wel-overlevenden). Als er geen verband zou zijn tussen de klasse en de
overlevingsstatus, dan zouden we voor de eerste-klasse-passagiers
verwachten dat er 220 niet-overlevenden zouden zijn
[<span class="math inline">\((1490/2201) \times 325 = (325 \times 1490) / 2201 = 220\)</span>] en 105
wel-overlevenden [<span class="math inline">\((711/2201) \times 325 = (325 \times 711) / 2201\)</span> =
105]. Op deze manier kunnen we de verwachte frequenties voor iedere cel
bepalen, rekening houdend met de randtotalen. Met behulp van die
verwachte frequenties berekenen we dan <span class="math inline">\(\chi^2=190.4\)</span>, hier met 3 d.f.,
<span class="math inline">\(p&lt;.001\)</span>. De gevonden significantie <span class="math inline">\(p\)</span> is kleiner dan <span class="math inline">\(\alpha=.001\)</span>, en
dus verwerpen we H0. We concluderen dat de uitkomst van de scheepsramp
(wel/niet overlevende) <em>ongelijk</em> verdeeld was voor de vier klassen van
opvarenden van de <em>Titanic</em>.</p>
</blockquote>
<hr />
<p>Voor de analyse van kruistabellen bestaande uit precies <span class="math inline">\(2\times2\)</span>
cellen is de Phi coefficiënt een bruikbaar alternatief (zie
§<a href="ch-samenhang.html#sec:Phi">11.6</a>).</p>
<p>Herlees en onthoud de waarschuwingen over correlatie en causaliteit (§<a href="ch-samenhang.html#sec:correlationcausation">11.7</a>)
— die zijn ook hier van toepassing.</p>
</div>
<div id="sec:chi2toets-aannames" class="section level2" number="16.5">
<h2><span class="header-section-number">16.5</span> aannames</h2>
<p>De <span class="math inline">\(\chi^2\)</span>-toets vereist drie aannames (assumpties) waaraan voldaan moet zijn, om de
toets te mogen gebruiken.</p>
<ul>
<li><p>De gegevens moeten gemeten zijn op nominaal niveau, of moeten
zijn versimpeld tot nominaal niveau (zie hoofdstuk <a href="ch-Meetniveau.html#ch:Meetniveau">4</a>).</p></li>
<li><p>Alle observaties moeten onafhankelijk van elkaar zijn, en
gebaseerd op (een) aselecte steekproef(/ven) uit de populatie(s) (zie
§<a href="ch-steekproeftrekking.html#sec:aselectesteekproef">7.3</a>), of op aselecte toewijzing van de
elementen uit een steekproef aan onderzoekscondities (randomisatie, zie §<a href="ch-validiteit.html#sec:internevaliditeit">5.4</a>, punt 5). Ieder element uit de steekproef mag dus maar één observatie aan één
cel bijdragen<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a>.</p></li>
<li><p>De steekproef is zodanig groot dat de verwachte frequentie
(<span class="math inline">\(E\)</span>) voor elke cel tenminste 5 is. Als de verwachte frequentie(s) in
één of meerdere cellen minder dan 5 is/zijn, reduceer dan het aantal
cellen door aangrenzende cellen samen te voegen, en de verwachte
frequenties opnieuw te bepalen.</p></li>
</ul>
</div>
<div id="formule" class="section level2" number="16.6">
<h2><span class="header-section-number">16.6</span> formule</h2>
<p>De toetsingsgrootheid <span class="math inline">\(\chi^2\)</span> is gedefinieerd als
<span class="math display" id="eq:chikwadraat">\[\begin{equation}
  \tag{16.1}
    \chi^2 = \sum \frac{(O-E)^2}{E}
\end{equation}\]</span>
waarbij <span class="math inline">\(O\)</span> en <span class="math inline">\(E\)</span> de
geobserveerde (Observed) en verwachte (Expected) aantallen observaties
aangeven voor iedere cel van de frequentietabel <span class="citation">(Ferguson and Takane <a href="#ref-Ferg89" role="doc-biblioref">1989</a>)</span>. De verwachte
aantallen kunnen ook gebroken getallen zijn (bijv. <span class="math inline">\(45/6\)</span> voor de 6
mogelijke uitkomsten van een eerlijke dobbelsteen, als we <span class="math inline">\(45\times\)</span>
gooien). Naarmate het verschil <span class="math inline">\((O-E)\)</span> in een of meerdere cellen groter
is, zal <span class="math inline">\(\chi^2\)</span> ook groter zijn. Door het kwadrateren is de
toetsingsgrootheid <span class="math inline">\(\chi^2\)</span> altijd nul of positief, en nooit negatief
<span class="citation">(Ferguson and Takane <a href="#ref-Ferg89" role="doc-biblioref">1989</a>)</span>.</p>
<p>De kansverdeling van de toetsingsgrootheid <span class="math inline">\(\chi^2\)</span> wordt bepaald door
het aantal vrijheidsgraden (zie
§<a href="ch-toetsing.html#sec:ttoets-vrijheidsgraden">13.2.1</a> voor uitleg van dit concept).
Bij een <span class="math inline">\(\chi^2\)</span>-toets met één nominale variabele (“goodness of fit”) is het aantal
vrijheidsgraden gelijk aan het aantal cellen minus 1. Bij een <span class="math inline">\(\chi^2\)</span>-toets met
meerdere steekproeven (homogeniteit) en/of met twee variabelen
(verband), met respectievelijk <span class="math inline">\(k\)</span> en <span class="math inline">\(m\)</span> categorieën, is het aantal
vrijheidsgraden gelijk aan <span class="math inline">\((k-1)\times(m-1)\)</span>.</p>
</div>
<div id="spss-14" class="section level2" number="16.7">
<h2><span class="header-section-number">16.7</span> SPSS</h2>
<div id="goodness-of-fit-voorbereiding" class="section level3" number="16.7.1">
<h3><span class="header-section-number">16.7.1</span> goodness of fit: voorbereiding</h3>
<p>Als we een nominale variabele willen onderzoeken, dan moet die uiteraard
als kolom in het SPSS databestand zijn aangemerkt. Iedere observatie
vormt een aparte regel in het databestand, en de nominale afhankelijke
variabele is een kolom in het databestand.</p>
<p>Soms beschikken we niet over de afzonderlijke observaties (regels) maar
wel over de tabel van aantallen observaties per categorie van de
nominale variabele. We kunnen daarmee ook verder werken. Stel je voor
dat we twee kolommen hebben, genaamd <code>uitkomst</code> en <code>aantal</code>, als volgt
(zie §<a href="ch-chi-kwadraat-toetsen.html#sec:chi2gof">16.2</a>):</p>
<pre><code>uitkomst aantal
 1        14
 2         9
 3        11
 4        10
 5        15
 6         1</code></pre>
<p>Vervolgens moet iedere cel (regel) een gewicht krijgen dat even groot is
als het <code>aantal</code> observaties, dat hier genoemd is in de tweede kolom: de
eerste cel (regel) weegt <span class="math inline">\(14\times\)</span> mee, de tweede cel (regel) weegt
<span class="math inline">\(9\times\)</span> mee, enz. Met deze truc hoeven we niet <span class="math inline">\(N=60\)</span> regels in te
vullen (voor elke observatie een regel), maar slechts 6 regels (voor
elke cel een regel).</p>
<pre><code>Data &gt; Weigh Cases... </code></pre>
<p>Kies <code>Weigh cases by...</code> en selecteer de variabele <code>aantal</code> in
het invulveld. Bevestig met <code>OK</code>.</p>
</div>
<div id="goodness-of-fit-toetsing" class="section level3" number="16.7.2">
<h3><span class="header-section-number">16.7.2</span> goodness of fit: toetsing</h3>
<pre><code>Analyze &gt; Nonparametric tests &gt; Legacy Dialogs &gt; Chi-square...</code></pre>
<p>Selecteer de variabelen <code>uitkomst</code> (in “Test variable list” paneel) en
geef aan dat we <em>gelijke</em> aantallen observaties verwachten in elke cel.
(Het is ook mogelijk om hier andere verwachte frequenties in te voeren,
als er volgens H0 andere, ongelijke frequenties verwacht worden.)
Bevestig met <code>OK</code>.</p>
</div>
<div id="kruistabellen-voorbereiding" class="section level3" number="16.7.3">
<h3><span class="header-section-number">16.7.3</span> kruistabellen: voorbereiding</h3>
<p>Als we twee nominale variabelen willen onderzoeken, dan moeten die
allebei als kolommen in het SPSS databestand zijn aangemerkt. Iedere
observatie vormt een aparte regel in het databestand, en de nominale
variabelen zijn kolommen in het databestand. Voor het
voorbeeld 16.1 hierboven zouden we dan een “lang” databestand
gebruiken dat bestaat uit <span class="math inline">\(N=2201\)</span> regels, voor elke opvarende een
aparte regel, met tenminste twee kolommen, voor <code>klasse</code> en
<code>overlevende</code>.</p>
<p>Soms beschikken we niet over de afzonderlijke observaties (regels) maar
wel over de kruistabel van aantallen observaties voor iedere combinatie
van categorieën van de de nominale variabelen. We kunnen daarmee ook
verder werken. Stel je voor dat we drie kolommen hebben, genaamd
<code>klasse</code>, <code>overlevende</code> en <code>aantal</code>, als volgt:</p>
<pre><code>klasse overlevende aantal
1st     niet       122
1st     wel        203
2nd     niet       167
2nd     wel        118
3rd     niet       528
3rd     wel        178
crew    niet       673
crew    wel        212</code></pre>
<p>Vervolgens moet iedere cel (regel) een gewicht krijgen dat even groot is
als het <code>aantal</code> observaties, dat genoemd is in de derde kolom: de
eerste cel (regel) weegt <span class="math inline">\(122\times\)</span> mee, de tweede cel (regel) weegt
<span class="math inline">\(203\times\)</span> mee, enz. Met deze truc hoeven we niet <span class="math inline">\(N=2201\)</span> regels in te
vullen (voor elke observatie een regel), maar slechts 8 regels (voor
elke cel een regel).</p>
<pre><code>Data &gt; Weigh Cases... </code></pre>
<p>Kies <code>Weigh cases by...</code> en selecteer de variabele <code>aantal</code> in
het invulveld. Bevestig met <code>OK</code>.</p>
</div>
<div id="kruistabellen-toetsing" class="section level3" number="16.7.4">
<h3><span class="header-section-number">16.7.4</span> kruistabellen: toetsing</h3>
<p>De toetsing verloopt op dezelfde wijze als beschreven in
§<a href="ch-samenhang.html#sec:Phi">11.6</a> voor
de samenhang tussen twee nominale variabelen.</p>
<pre><code>Analyze &gt; Descriptives &gt; Crosstabs...</code></pre>
<p>Selecteer de variabelen <code>klasse</code> (in “Rows” paneel) en <code>overlevende</code> (in
“Columns” paneel) voor
kruistabel <a href="ch-chi-kwadraat-toetsen.html#tab:titanic">16.1</a>.<br />
Kies <code>Statistics…</code> en vink de optie <code>Chi-square</code> aan. Bevestig eerst met
<code>Continue</code> en daarna nogmaals met <code>OK</code>.</p>
</div>
</div>
<div id="jasp-16" class="section level2" number="16.8">
<h2><span class="header-section-number">16.8</span> JASP</h2>
<div id="goodness-of-fit-voorbereiding-1" class="section level3" number="16.8.1">
<h3><span class="header-section-number">16.8.1</span> goodness of fit: voorbereiding</h3>
<p>Als we een nominale variabele willen onderzoeken, dan moet die uiteraard
als kolom in het databestand zijn aangemerkt. Het is gebruikelijk dat iedere observatie dan een aparte regel vormt in dit databestand. Voor de “goodness of fit” <span class="math inline">\(\chi^2\)</span>-toets moet de data echter net iets anders worden ingevoerd. Niet alle afzonderlijke observaties moeten worden ingevoerd, maar de aantallen (ook wel ‘frequenties’ of ‘counts’) observaties per categorie van de nominale variabele. Hierdoor hoeven we niet <span class="math inline">\(N=60\)</span> regels in te vullen (voor elke observatie een regel), maar slechts 6 regels (voor elke categorie een regel). Voor het voorbeeld uit §<a href="ch-chi-kwadraat-toetsen.html#sec:chi2gof">16.2</a> ziet dit er als volgt uit:</p>
<pre><code>uitkomst aantal
 1        14
 2         9
 3        11
 4        10
 5        15
 6         1</code></pre>
<p>Om deze data in JASP te krijgen maak je een Excel-bestand aan waar je de data invoert (precies zoals hierboven weergegeven, met de variabele-namen erbij).
Sla dit bestand op als CSV-bestand (.csv, dus niet .xlsx), en open het in JASP.</p>
</div>
<div id="goodness-of-fit-toetsing-1" class="section level3" number="16.8.2">
<h3><span class="header-section-number">16.8.2</span> goodness of fit: toetsing</h3>
<p>Klik in de bovenbalk op:</p>
<pre><code>Frequencies &gt; Multinomial Test (onder &#39;Classical&#39;)</code></pre>
<p>Selecteer de variabele <code>uitkomst</code> en plaats deze in het veld “Factor”. Plaats de variabele <code>aantal</code> in het veld “Count”.<br />
</p>
<p>Onder “Test Values” kun je kiezen voor <code>Equal proportions (multinomial test)</code> en <code>Expected proportions (chi-square test)</code>.<br />
De multinomial test is een speciale versie van een <span class="math inline">\(\chi^2\)</span>-toets waarbij de nul-hypothese wordt getoetst dat de aantallen gelijk zijn, m.a.w. de verwachte frequentie is identiek voor iedere cel (dat wordt een uniforme verdeling genoemd). Dat betekent in dit voorbeeld dat de dobbelsteen eerlijk is, en dat is ook wat we willen toetsen. Je kan in dit geval dus <code>Equal proportions (multinomial test)</code> kiezen.<br />
Als je <code>Expected proportions (chi-square test)</code> kiest, kun je de verwachte aantallen observaties in elke cel aanpassen. Als er volgens H0 andere, ongelijke frequenties verwacht worden, kies je dus deze optie en vul je de verwachting in onder <em>H0</em> in de tabel die verschijnt (je geeft de cellen een ander ‘gewicht’, d.w.z. hoe vaak ze meetellen). De waardes onder <em>H0</em> voor elke cel staan echter standaard op 1, waarmee je gelijke frequenties test. Je krijgt dan dezelfde resultaten als met de multinomial test, dus voor ons voorbeeld maakt het niet zoveel uit welke van de twee opties je kiest.</p>
<p>Je kunt ook nog <code>Descriptives</code> en <code>Confidence interval</code> aanvinken onder “Additional Statistics” en <code>Descriptives plot</code> onder “Plots” om meer inzicht te krijgen in wat je toetst.</p>
</div>
<div id="kruistabellen-voorbereiding-1" class="section level3" number="16.8.3">
<h3><span class="header-section-number">16.8.3</span> kruistabellen: voorbereiding</h3>
<p>Als we twee nominale variabelen willen onderzoeken, dan moeten die allebei als kolommen in het databestand zijn aangemerkt.
Het is gebruikelijk dat iedere observatie dan een aparte regel vormt in dit databestand. Voor de <span class="math inline">\(\chi^2\)</span>-toets met twee nominale variabelen kan zo’n “lang” databestand ook worden gebruikt in JASP. Voor het voorbeeld 16.1 hierboven zouden we dan <span class="math inline">\(N=2201\)</span> regels hebben: voor elke opvarende een aparte regel, met tenminste twee kolommen, voor <code>klasse</code> en <code>overlevende</code>.<br />
</p>
<p>Soms beschikken we niet over de afzonderlijke observaties (regels) maar
wel over de kruistabel van aantallen observaties voor iedere combinatie
van categorieën van de de nominale variabelen. We kunnen daarmee ook
verder werken in JASP. Hierdoor hoeven we niet <span class="math inline">\(N=2201\)</span> regels in te vullen (voor elke observatie een regel), maar slechts 8 regels (voor elke cel een regel).
Voor voorbeeld 16.1 ziet dit er als volgt uit:</p>
<pre><code>klasse overlevende aantal
1st     niet       122
1st     wel        203
2nd     niet       167
2nd     wel        118
3rd     niet       528
3rd     wel        178
crew    niet       673
crew    wel        212</code></pre>
<p>Om deze data in JASP te krijgen maak je een Excel-bestand aan waar je de data invoert (precies zoals hierboven weergegeven, met de variabele-namen erbij).
Sla dit bestand op als CSV-bestand (.csv, dus niet .xlsx), en open het in JASP.</p>
</div>
<div id="kruistabellen-toetsing-1" class="section level3" number="16.8.4">
<h3><span class="header-section-number">16.8.4</span> kruistabellen: toetsing</h3>
<p>De toetsing verloopt op dezelfde wijze als beschreven in
§<a href="ch-samenhang.html#sec:Phi">11.6</a> voor de samenhang tussen twee nominale variabelen.</p>
<p>Klik in de bovenbalk op:</p>
<pre><code>Frequencies &gt; Contingency Tables (onder &#39;Classical&#39;)</code></pre>
<p>Selecteer de variabele <code>klasse</code> in het “Rows” paneel, de variabele <code>overlevende</code> in het “Columns” paneel en variabele <code>aantal</code> in het “Counts” paneel voor kruistabel <a href="ch-chi-kwadraat-toetsen.html#tab:titanic">16.1</a>. Open de <code>Statistics</code> balk
en zorg dat <code>Chi-square</code> (<span class="math inline">\(\chi^2\)</span>) is aangevinkt. De waarde voor <span class="math inline">\(\chi^2\)</span> verschijnt dan in de uitvoer in de tabel getiteld <em>Chi-Squared Tests</em>.</p>
<p>Mocht je toch een “lang” databestand hebben, waarbij elke regel een aparte observatie is, dan hoef je alleen de variabele <code>klasse</code> in het “Rows” paneel en de variabele <code>overlevende</code> in het “Columns” paneel te selecteren.</p>
</div>
</div>
<div id="r-17" class="section level2" number="16.9">
<h2><span class="header-section-number">16.9</span> R</h2>
<div id="goodness-of-fit-toetsing-2" class="section level3" number="16.9.1">
<h3><span class="header-section-number">16.9.1</span> goodness of fit: toetsing</h3>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="ch-chi-kwadraat-toetsen.html#cb174-1" aria-hidden="true"></a><span class="kw">chisq.test</span>( <span class="kw">c</span>( <span class="dv">14</span>, <span class="dv">9</span>, <span class="dv">11</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">1</span> ) ) <span class="co"># dobbelsteen §16.1</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(14, 9, 11, 10, 15, 1)
## X-squared = 12.4, df = 5, p-value = 0.0297</code></pre>
</div>
<div id="kruistabellen-voorbereiding-en-toetsing" class="section level3" number="16.9.2">
<h3><span class="header-section-number">16.9.2</span> kruistabellen: voorbereiding en toetsing</h3>
<p>In R is de dataset <code>Titanic</code> gegeven als een multidimensionele matrix. We tellen de observaties op en maken een kruistabel van de eerste dimensie (klasse) en de vierde dimensie (uitkomst).</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="ch-chi-kwadraat-toetsen.html#cb176-1" aria-hidden="true"></a><span class="kw">apply</span>( Titanic, <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">4</span>), sum ) -&gt;<span class="st"> </span>Titanic.klasseuitkomst</span></code></pre></div>
<p>Vervolgens gebruiken we deze kruistabel weer als invoer voor een <code>chisq.test</code>.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="ch-chi-kwadraat-toetsen.html#cb177-1" aria-hidden="true"></a><span class="kw">chisq.test</span>( Titanic.klasseuitkomst )  <span class="co"># p&lt;.0001</span></span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  Titanic.klasseuitkomst
## X-squared = 190.4, df = 3, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="effectgrootte-odds-ratio" class="section level2" number="16.10">
<h2><span class="header-section-number">16.10</span> Effectgrootte: odds ratio</h2>
<p>Bij het gebruik van de <span class="math inline">\(\chi^2\)</span>-toets kan de effectgrootte worden gerapporteerd in de
vorm van de zgn. “odds ratio”. De ‘odds ratio’ wordt afgeleid van de
kruistabel met frequenties per cel. We leggen een en ander uit aan de
hand van het volgende voorbeeld.</p>
<hr />
<blockquote>
<p><em>Voorbeeld 16.2</em>:
<span class="citation">Doll and Hill (<a href="#ref-DollHill1956" role="doc-biblioref">1956</a>)</span> onderzochten de relatie tussen roken en
longkanker. Eerst enqueteerden zij alle Britse artsen over hun leeftijd
en rookgedrag. Vervolgens hielden deze onderzoekers jarenlang de
overlijdensberichten en de doodsoorzaak bij van alle geënqueteerden. De
eerste uitkomsten, na ruim vier jaar, zijn samengevat in
tabel <a href="ch-chi-kwadraat-toetsen.html#tab:dollhill">16.2</a>.</p>
</blockquote>
<table>
<caption><span id="tab:dollhill">Tabel 16.2: </span> Kruistabel van <span class="math inline">\(N=24354\)</span> Britse artsen van 35 jaar en ouder bij de eerste enquete, onderverdeeld naar rookgedrag (rijen: wel/niet rokend resp. gerookt hebbend) en naar sterfte door longkanker in de afgelopen 4 jaar (kolommen), met letter-aanduiding voor de aantallen observaties.</caption>
<thead>
<tr class="header">
<th align="left">rokend</th>
<th align="right">niet longkanker</th>
<th></th>
<th align="right">wel longkanker</th>
<th></th>
<th align="right">totaal</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">niet (0)</td>
<td align="right">3092</td>
<td>(A)</td>
<td align="right">1</td>
<td>(B)</td>
<td align="right">3093</td>
<td>(A+B)</td>
</tr>
<tr class="even">
<td align="left">wel (1)</td>
<td align="right">21178</td>
<td>(C)</td>
<td align="right">83</td>
<td>(D)</td>
<td align="right">21261</td>
<td>(C+D)</td>
</tr>
<tr class="odd">
<td align="left">totaal</td>
<td align="right">24270</td>
<td>(A+C)</td>
<td align="right">84</td>
<td>(B+D)</td>
<td align="right">24354</td>
<td>(A+B+C+D)</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Op de gebruikelijke wijze vinden we <span class="math inline">\(\chi^2=10.35\)</span>, df=1, <span class="math inline">\(p&lt;.01\)</span>. We
concluderen dat er een verband is tussen rookgedrag en de sterfte door
longkanker.</p>
</blockquote>
<hr />
<p>Voor de effectgrootte berekenen we eerst de ‘odds’ van sterfte door
longkanker voor de rokers: D/C= <span class="math inline">\(83/21178 =0.00392\)</span>. Onder de rokers
staan er 83 sterfgevallen-door-longkanker tegenover 21178
niet-sterfgevallen-door-longkanker (de ‘odds’ om te overlijden aan
longkanker zijn 1 op de 0.00392). Voor de niet-rokers: B/A=
<span class="math inline">\(1/3092 =0.00032\)</span> (de ‘odds’ zijn 1 op de 0.00032).</p>
<p>De <em>verhouding</em> van deze beide ‘odds’ voor de beide groepen noemen we de
‘odds ratio’ (afgekort OR). In dit voorbeeld vinden we (D/C) / (B/A) =
AD/BC =
<span class="math inline">\((3092 \times 83) / (1 \times 2178) = (0.00392)/(0.00032) = 12.1\)</span>. De
‘odds’ om te sterven aan longkanker zijn dus ruim <span class="math inline">\(12\times\)</span> zo groot
voor de rokers dan voor de niet-rokers. We rapporteren dat als volgt:</p>
<blockquote>
<p><span class="citation">Doll and Hill (<a href="#ref-DollHill1956" role="doc-biblioref">1956</a>)</span> vonden een significant verband tussen
rookgedrag en sterfte door longkanker,
<span class="math inline">\(\chi^2(1)=10.35, p&lt;.01, \textrm{OR}=12.1\)</span>. De ‘odds’ om te overlijden
door longkanker bleken ruim <span class="math inline">\(12\times\)</span> zo groot voor rokers als voor
niet-rokers.</p>
</blockquote>

</div>
</div>
<h3>Referenties</h3>
<div id="refs" class="references">
<div id="ref-DollHill1956">
<p>Doll, Richard, and A. Bradford Hill. 1956. “Lung Cancer and Other Causes of Death in Relation to Smoking: A Second Report on the Mortality of British Doctors.” <em>British Medical Journal</em>, 1071–81. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2035864/">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2035864/</a>.</p>
</div>
<div id="ref-Ferg89">
<p>Ferguson, George A., and Yoshio Takane. 1989. <em>Statistical Analysis in Psychology and Education</em>. 6e ed. New York: McGraw-Hill.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="35">
<li id="fn35"><p>De gevonden waarde <span class="math inline">\(\chi^2=12.44\)</span> ligt iets onder de kritieke waarde voor 5 d.f. en <span class="math inline">\(p=.025\)</span>, (daar staat <span class="math inline">\((\chi^2)^*=12.83\)</span>), dus de bijbehorende kans op deze waarde of een grotere waarde is iets groter dan <span class="math inline">\(0.025\)</span>.<a href="ch-chi-kwadraat-toetsen.html#fnref35" class="footnote-back">↩︎</a></p></li>
<li id="fn36"><p>Als de observaties van één variabele niet onafhankelijk maar gepaard zijn (bijv. voor/na behandeling, wel/niet geslaagd, enz), dan biedt de McNemar test een bruikbaar alternatief.<a href="ch-chi-kwadraat-toetsen.html#fnref36" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch-variantieanalyse.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch-andere-nonpar-toetsen.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/h16chikwadraat.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["KMS-NL.pdf", "KMS-NL.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
