<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Hoofdstuk 10 Kansverdelingen | Kwantitatieve Methoden en Statistiek</title>
  <meta name="description" content="Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek (TL3V24001, TL2V23004, TW2V19002, TL2V17002), Dept Talen Literatuur en Communicatie, Universiteit Utrecht." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Hoofdstuk 10 Kansverdelingen | Kwantitatieve Methoden en Statistiek" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek (TL3V24001, TL2V23004, TW2V19002, TL2V17002), Dept Talen Literatuur en Communicatie, Universiteit Utrecht." />
  <meta name="github-repo" content="rstudio/KMS-NL" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Hoofdstuk 10 Kansverdelingen | Kwantitatieve Methoden en Statistiek" />
  
  <meta name="twitter:description" content="Tekstboek over Kwantitatieve Methoden en Statistiek, o.a. gebruikt in cursus Methoden en Statistiek (TL3V24001, TL2V23004, TW2V19002, TL2V17002), Dept Talen Literatuur en Communicatie, Universiteit Utrecht." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch-centrumenspreiding.html"/>
<link rel="next" href="ch-samenhang.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Kwantitatieve Methoden en Statistiek</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Voorwoord</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#in-english-please"><i class="fa fa-check"></i>In English please?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notatie"><i class="fa fa-check"></i>Notatie</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#licentie"><i class="fa fa-check"></i>Licentie</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citatie"><i class="fa fa-check"></i>Citatie</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#technische-details"><i class="fa fa-check"></i>Technische details</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#over-de-auteurs"><i class="fa fa-check"></i>Over de auteurs</a></li>
</ul></li>
<li class="part"><span><b>Deel I: Methodologie</b></span></li>
<li class="chapter" data-level="1" data-path="ch-inleiding.html"><a href="ch-inleiding.html"><i class="fa fa-check"></i><b>1</b> Inleiding</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:wetenschappelijk-onderzoek"><i class="fa fa-check"></i><b>1.1</b> Wetenschappelijk onderzoek</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:theorie"><i class="fa fa-check"></i><b>1.1.1</b> Theorie</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:paradigmata"><i class="fa fa-check"></i><b>1.2</b> Paradigmata</a></li>
<li class="chapter" data-level="1.3" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:instrumentatie-onderzoek"><i class="fa fa-check"></i><b>1.3</b> Instrumentatie-onderzoek</a></li>
<li class="chapter" data-level="1.4" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:beschrijvend-onderzoek"><i class="fa fa-check"></i><b>1.4</b> Beschrijvend onderzoek</a></li>
<li class="chapter" data-level="1.5" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:experimenteel-onderzoek"><i class="fa fa-check"></i><b>1.5</b> Experimenteel onderzoek</a></li>
<li class="chapter" data-level="1.6" data-path="ch-inleiding.html"><a href="ch-inleiding.html#sec:vooruitblik"><i class="fa fa-check"></i><b>1.6</b> Vooruitblik</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html"><i class="fa fa-check"></i><b>2</b> Hypothese-toetsend onderzoek</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#inleiding"><i class="fa fa-check"></i><b>2.1</b> Inleiding</a></li>
<li class="chapter" data-level="2.2" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:variabelen"><i class="fa fa-check"></i><b>2.2</b> Variabelen</a></li>
<li class="chapter" data-level="2.3" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:onafhankelijkeafhankelijkevariabelen"><i class="fa fa-check"></i><b>2.3</b> Onafhankelijke en afhankelijke variabelen</a></li>
<li class="chapter" data-level="2.4" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:falsificatie"><i class="fa fa-check"></i><b>2.4</b> Falsificatie en nul-hypothese</a></li>
<li class="chapter" data-level="2.5" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:empirischecyclus"><i class="fa fa-check"></i><b>2.5</b> De empirische cyclus</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#observatie"><i class="fa fa-check"></i><b>2.5.1</b> observatie</a></li>
<li class="chapter" data-level="2.5.2" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#inductie"><i class="fa fa-check"></i><b>2.5.2</b> inductie</a></li>
<li class="chapter" data-level="2.5.3" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#deductie"><i class="fa fa-check"></i><b>2.5.3</b> deductie</a></li>
<li class="chapter" data-level="2.5.4" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#toetsing"><i class="fa fa-check"></i><b>2.5.4</b> toetsing</a></li>
<li class="chapter" data-level="2.5.5" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#evaluatie"><i class="fa fa-check"></i><b>2.5.5</b> evaluatie</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="ch-onderzoek.html"><a href="ch-onderzoek.html#sec:keuzemomenten"><i class="fa fa-check"></i><b>2.6</b> Keuzemomenten</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch-integriteit.html"><a href="ch-integriteit.html"><i class="fa fa-check"></i><b>3</b> Integriteit</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch-integriteit.html"><a href="ch-integriteit.html#sec:integriteit-inleiding"><i class="fa fa-check"></i><b>3.1</b> Inleiding</a></li>
<li class="chapter" data-level="3.2" data-path="ch-integriteit.html"><a href="ch-integriteit.html#sec:ontwerp"><i class="fa fa-check"></i><b>3.2</b> Ontwerp</a></li>
<li class="chapter" data-level="3.3" data-path="ch-integriteit.html"><a href="ch-integriteit.html#proefpersonen-en-informanten"><i class="fa fa-check"></i><b>3.3</b> Proefpersonen en informanten</a></li>
<li class="chapter" data-level="3.4" data-path="ch-integriteit.html"><a href="ch-integriteit.html#gegevens"><i class="fa fa-check"></i><b>3.4</b> Gegevens</a></li>
<li class="chapter" data-level="3.5" data-path="ch-integriteit.html"><a href="ch-integriteit.html#teksten"><i class="fa fa-check"></i><b>3.5</b> Teksten</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html"><i class="fa fa-check"></i><b>4</b> Meetniveau</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html#inleiding-1"><i class="fa fa-check"></i><b>4.1</b> Inleiding</a></li>
<li class="chapter" data-level="4.2" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html#sec:nominaal"><i class="fa fa-check"></i><b>4.2</b> Nominaal</a></li>
<li class="chapter" data-level="4.3" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html#sec:ordinaal"><i class="fa fa-check"></i><b>4.3</b> Ordinaal</a></li>
<li class="chapter" data-level="4.4" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html#sec:interval"><i class="fa fa-check"></i><b>4.4</b> Interval</a></li>
<li class="chapter" data-level="4.5" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html#sec:ratio"><i class="fa fa-check"></i><b>4.5</b> Ratio</a></li>
<li class="chapter" data-level="4.6" data-path="ch-meetniveau.html"><a href="ch-meetniveau.html#sec:ordeningvanmeetniveaus"><i class="fa fa-check"></i><b>4.6</b> Ordening van meetniveaus</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch-validiteit.html"><a href="ch-validiteit.html"><i class="fa fa-check"></i><b>5</b> Validiteit</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch-validiteit.html"><a href="ch-validiteit.html#inleiding-2"><i class="fa fa-check"></i><b>5.1</b> Inleiding</a></li>
<li class="chapter" data-level="5.2" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:causaliteit"><i class="fa fa-check"></i><b>5.2</b> Causaliteit</a></li>
<li class="chapter" data-level="5.3" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:validiteit"><i class="fa fa-check"></i><b>5.3</b> Validiteit</a></li>
<li class="chapter" data-level="5.4" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:internevaliditeit"><i class="fa fa-check"></i><b>5.4</b> Interne validiteit</a></li>
<li class="chapter" data-level="5.5" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:constructvaliditeit"><i class="fa fa-check"></i><b>5.5</b> Constructvaliditeit</a></li>
<li class="chapter" data-level="5.6" data-path="ch-validiteit.html"><a href="ch-validiteit.html#sec:externevaliditeit"><i class="fa fa-check"></i><b>5.6</b> Externe validiteit</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html"><i class="fa fa-check"></i><b>6</b> Ontwerp</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:ontwerp-inleiding"><i class="fa fa-check"></i><b>6.1</b> Inleiding</a></li>
<li class="chapter" data-level="6.2" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:tussenbinnenproefpersonen"><i class="fa fa-check"></i><b>6.2</b> Tussen of binnen ?</a></li>
<li class="chapter" data-level="6.3" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:oneshotsinglecase"><i class="fa fa-check"></i><b>6.3</b> Het one-shot single-case-ontwerp</a></li>
<li class="chapter" data-level="6.4" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:eengroepvoorna"><i class="fa fa-check"></i><b>6.4</b> Het één-groep-voormeting-nameting-ontwerp</a></li>
<li class="chapter" data-level="6.5" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:voormeting-nameting-controlegroep-ontwerp"><i class="fa fa-check"></i><b>6.5</b> Het voormeting-nameting-controlegroep-ontwerp</a></li>
<li class="chapter" data-level="6.6" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:solomon-vier-groepen-ontwerp"><i class="fa fa-check"></i><b>6.6</b> Het Solomon-vier-groepen-ontwerp</a></li>
<li class="chapter" data-level="6.7" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:nameting-controlegroep"><i class="fa fa-check"></i><b>6.7</b> Het nameting-controlegroep-ontwerp</a></li>
<li class="chapter" data-level="6.8" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:ontwerp-factorieel"><i class="fa fa-check"></i><b>6.8</b> Factoriële ontwerpen</a></li>
<li class="chapter" data-level="6.9" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#sec:afhankelijkegroepen"><i class="fa fa-check"></i><b>6.9</b> Afhankelijke- en onafhankelijke-groepen-ontwerp</a></li>
<li class="chapter" data-level="6.10" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#onderzoek-ontwerpen"><i class="fa fa-check"></i><b>6.10</b> Onderzoek ontwerpen</a></li>
<li class="chapter" data-level="6.11" data-path="ch-ontwerp.html"><a href="ch-ontwerp.html#tenslotte"><i class="fa fa-check"></i><b>6.11</b> Tenslotte</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html"><i class="fa fa-check"></i><b>7</b> Steekproeven</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:gelegenheidssteekproef"><i class="fa fa-check"></i><b>7.1</b> Gelegenheidssteekproeven</a></li>
<li class="chapter" data-level="7.2" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:systematischesteekproef"><i class="fa fa-check"></i><b>7.2</b> Systematische steekproeven</a></li>
<li class="chapter" data-level="7.3" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:aselectesteekproef"><i class="fa fa-check"></i><b>7.3</b> Aselecte steekproeven</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#spss"><i class="fa fa-check"></i><b>7.3.1</b> SPSS</a></li>
<li class="chapter" data-level="7.3.2" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#jasp"><i class="fa fa-check"></i><b>7.3.2</b> JASP</a></li>
<li class="chapter" data-level="7.3.3" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#r"><i class="fa fa-check"></i><b>7.3.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch-steekproeftrekking.html"><a href="ch-steekproeftrekking.html#sec:steekproefgrootte"><i class="fa fa-check"></i><b>7.4</b> Steekproefgrootte</a></li>
</ul></li>
<li class="part"><span><b>Deel II: Beschrijvende statistiek</b></span></li>
<li class="chapter" data-level="8" data-path="ch-frequenties.html"><a href="ch-frequenties.html"><i class="fa fa-check"></i><b>8</b> Frequenties</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch-frequenties.html"><a href="ch-frequenties.html#inleiding-3"><i class="fa fa-check"></i><b>8.1</b> Inleiding</a></li>
<li class="chapter" data-level="8.2" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:frequenties"><i class="fa fa-check"></i><b>8.2</b> Frequenties</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:intervallen"><i class="fa fa-check"></i><b>8.2.1</b> Intervallen</a></li>
<li class="chapter" data-level="8.2.2" data-path="ch-frequenties.html"><a href="ch-frequenties.html#spss-1"><i class="fa fa-check"></i><b>8.2.2</b> SPSS</a></li>
<li class="chapter" data-level="8.2.3" data-path="ch-frequenties.html"><a href="ch-frequenties.html#jasp-1"><i class="fa fa-check"></i><b>8.2.3</b> JASP</a></li>
<li class="chapter" data-level="8.2.4" data-path="ch-frequenties.html"><a href="ch-frequenties.html#r-1"><i class="fa fa-check"></i><b>8.2.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:staafdiagrammen"><i class="fa fa-check"></i><b>8.3</b> Staafdiagrammen</a></li>
<li class="chapter" data-level="8.4" data-path="ch-frequenties.html"><a href="ch-frequenties.html#sec:histogrammen"><i class="fa fa-check"></i><b>8.4</b> Histogrammen</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="ch-frequenties.html"><a href="ch-frequenties.html#spss-2"><i class="fa fa-check"></i><b>8.4.1</b> SPSS</a></li>
<li class="chapter" data-level="8.4.2" data-path="ch-frequenties.html"><a href="ch-frequenties.html#jasp-2"><i class="fa fa-check"></i><b>8.4.2</b> JASP</a></li>
<li class="chapter" data-level="8.4.3" data-path="ch-frequenties.html"><a href="ch-frequenties.html#r-2"><i class="fa fa-check"></i><b>8.4.3</b> R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html"><i class="fa fa-check"></i><b>9</b> Centrum en spreiding</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#inleiding-4"><i class="fa fa-check"></i><b>9.1</b> Inleiding</a></li>
<li class="chapter" data-level="9.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#symbolen"><i class="fa fa-check"></i><b>9.2</b> Symbolen</a></li>
<li class="chapter" data-level="9.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#centrummaten"><i class="fa fa-check"></i><b>9.3</b> Centrummaten</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:gemiddelde"><i class="fa fa-check"></i><b>9.3.1</b> gemiddelde</a></li>
<li class="chapter" data-level="9.3.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:mediaan"><i class="fa fa-check"></i><b>9.3.2</b> mediaan</a></li>
<li class="chapter" data-level="9.3.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#modus"><i class="fa fa-check"></i><b>9.3.3</b> modus</a></li>
<li class="chapter" data-level="9.3.4" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:harmonischgemiddelde"><i class="fa fa-check"></i><b>9.3.4</b> harmonisch gemiddelde</a></li>
<li class="chapter" data-level="9.3.5" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#gewinsoriseerde-gemiddelde"><i class="fa fa-check"></i><b>9.3.5</b> gewinsoriseerde gemiddelde</a></li>
<li class="chapter" data-level="9.3.6" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#getrimde-gemiddelde"><i class="fa fa-check"></i><b>9.3.6</b> getrimde gemiddelde</a></li>
<li class="chapter" data-level="9.3.7" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#vergelijking-van-centrummaten"><i class="fa fa-check"></i><b>9.3.7</b> vergelijking van centrummaten</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:kwartielen-en-boxplots"><i class="fa fa-check"></i><b>9.4</b> Kwartielen en boxplots</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#kwartielen"><i class="fa fa-check"></i><b>9.4.1</b> Kwartielen</a></li>
<li class="chapter" data-level="9.4.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:uitbijters"><i class="fa fa-check"></i><b>9.4.2</b> Uitbijters</a></li>
<li class="chapter" data-level="9.4.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:boxplot"><i class="fa fa-check"></i><b>9.4.3</b> Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:spreidingsmaten"><i class="fa fa-check"></i><b>9.5</b> Spreidingsmaten</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:variantie"><i class="fa fa-check"></i><b>9.5.1</b> variantie</a></li>
<li class="chapter" data-level="9.5.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:standaarddeviatie"><i class="fa fa-check"></i><b>9.5.2</b> standaarddeviatie</a></li>
<li class="chapter" data-level="9.5.3" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#mad"><i class="fa fa-check"></i><b>9.5.3</b> MAD</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:significantecijfers"><i class="fa fa-check"></i><b>9.6</b> Over significante cijfers</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:significantecijfers-gemiddelde"><i class="fa fa-check"></i><b>9.6.1</b> Gemiddelde en standaarddeviatie</a></li>
<li class="chapter" data-level="9.6.2" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#percentages"><i class="fa fa-check"></i><b>9.6.2</b> Percentages</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:robuustefficient"><i class="fa fa-check"></i><b>9.7</b> Keuzemoment</a></li>
<li class="chapter" data-level="9.8" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#sec:standaardscores"><i class="fa fa-check"></i><b>9.8</b> Standaardscores</a></li>
<li class="chapter" data-level="9.9" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#spss-3"><i class="fa fa-check"></i><b>9.9</b> SPSS</a></li>
<li class="chapter" data-level="9.10" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#jasp-3"><i class="fa fa-check"></i><b>9.10</b> JASP</a></li>
<li class="chapter" data-level="9.11" data-path="ch-centrumenspreiding.html"><a href="ch-centrumenspreiding.html#r-3"><i class="fa fa-check"></i><b>9.11</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html"><i class="fa fa-check"></i><b>10</b> Kansverdelingen</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:kansen"><i class="fa fa-check"></i><b>10.1</b> Kansen</a></li>
<li class="chapter" data-level="10.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:binomiaalverdeling"><i class="fa fa-check"></i><b>10.2</b> Binomiale kansverdeling</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#formules"><i class="fa fa-check"></i><b>10.2.1</b> formules</a></li>
<li class="chapter" data-level="10.2.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#jasp-4"><i class="fa fa-check"></i><b>10.2.2</b> JASP</a></li>
<li class="chapter" data-level="10.2.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#r-4"><i class="fa fa-check"></i><b>10.2.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:normaalverdeling"><i class="fa fa-check"></i><b>10.3</b> Normale kansverdeling</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#formules-1"><i class="fa fa-check"></i><b>10.3.1</b> formules</a></li>
<li class="chapter" data-level="10.3.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#jasp-5"><i class="fa fa-check"></i><b>10.3.2</b> JASP</a></li>
<li class="chapter" data-level="10.3.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#r-5"><i class="fa fa-check"></i><b>10.3.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:isvarnormaalverdeeld"><i class="fa fa-check"></i><b>10.4</b> Heeft mijn variabele een normale kansverdeling?</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#spss-4"><i class="fa fa-check"></i><b>10.4.1</b> SPSS</a></li>
<li class="chapter" data-level="10.4.2" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#jasp-6"><i class="fa fa-check"></i><b>10.4.2</b> JASP</a></li>
<li class="chapter" data-level="10.4.3" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#r-6"><i class="fa fa-check"></i><b>10.4.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:watalsnietnormaal"><i class="fa fa-check"></i><b>10.5</b> Wat als mijn variabele niet normaal verdeeld is?</a></li>
<li class="chapter" data-level="10.6" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:CentraalLimietTheorema"><i class="fa fa-check"></i><b>10.6</b> Kansverdeling van gemiddelde</a></li>
<li class="chapter" data-level="10.7" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#sec:betrouwbaarheidsinterval-gemiddelde"><i class="fa fa-check"></i><b>10.7</b> Betrouwbaarheidsinterval van het gemiddelde</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="ch-kansverdelingen.html"><a href="ch-kansverdelingen.html#formules-2"><i class="fa fa-check"></i><b>10.7.1</b> formules</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch-samenhang.html"><a href="ch-samenhang.html"><i class="fa fa-check"></i><b>11</b> Samenhang</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#inleiding-5"><i class="fa fa-check"></i><b>11.1</b> Inleiding</a></li>
<li class="chapter" data-level="11.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:Pearson"><i class="fa fa-check"></i><b>11.2</b> Pearson product-moment-correlatie</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#formules-3"><i class="fa fa-check"></i><b>11.2.1</b> Formules</a></li>
<li class="chapter" data-level="11.2.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-5"><i class="fa fa-check"></i><b>11.2.2</b> SPSS</a></li>
<li class="chapter" data-level="11.2.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-7"><i class="fa fa-check"></i><b>11.2.3</b> JASP</a></li>
<li class="chapter" data-level="11.2.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-7"><i class="fa fa-check"></i><b>11.2.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:regressie"><i class="fa fa-check"></i><b>11.3</b> Regressie</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:regressie-formules"><i class="fa fa-check"></i><b>11.3.1</b> Formules</a></li>
<li class="chapter" data-level="11.3.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-6"><i class="fa fa-check"></i><b>11.3.2</b> SPSS</a></li>
<li class="chapter" data-level="11.3.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-8"><i class="fa fa-check"></i><b>11.3.3</b> JASP</a></li>
<li class="chapter" data-level="11.3.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-8"><i class="fa fa-check"></i><b>11.3.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#invloedrijke-observaties"><i class="fa fa-check"></i><b>11.4</b> Invloedrijke observaties</a></li>
<li class="chapter" data-level="11.5" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:Spearman"><i class="fa fa-check"></i><b>11.5</b> Spearmans rangorde-correlatie</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#formules-4"><i class="fa fa-check"></i><b>11.5.1</b> Formules</a></li>
<li class="chapter" data-level="11.5.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-7"><i class="fa fa-check"></i><b>11.5.2</b> SPSS</a></li>
<li class="chapter" data-level="11.5.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-9"><i class="fa fa-check"></i><b>11.5.3</b> JASP</a></li>
<li class="chapter" data-level="11.5.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-9"><i class="fa fa-check"></i><b>11.5.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:Phi"><i class="fa fa-check"></i><b>11.6</b> Phi</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="ch-samenhang.html"><a href="ch-samenhang.html#formules-5"><i class="fa fa-check"></i><b>11.6.1</b> Formules</a></li>
<li class="chapter" data-level="11.6.2" data-path="ch-samenhang.html"><a href="ch-samenhang.html#spss-8"><i class="fa fa-check"></i><b>11.6.2</b> SPSS</a></li>
<li class="chapter" data-level="11.6.3" data-path="ch-samenhang.html"><a href="ch-samenhang.html#jasp-10"><i class="fa fa-check"></i><b>11.6.3</b> JASP</a></li>
<li class="chapter" data-level="11.6.4" data-path="ch-samenhang.html"><a href="ch-samenhang.html#r-10"><i class="fa fa-check"></i><b>11.6.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="ch-samenhang.html"><a href="ch-samenhang.html#sec:correlationcausation"><i class="fa fa-check"></i><b>11.7</b> Tenslotte</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html"><i class="fa fa-check"></i><b>12</b> Betrouwbaarheid</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#inleiding-6"><i class="fa fa-check"></i><b>12.1</b> Inleiding</a></li>
<li class="chapter" data-level="12.2" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#wat-is-betrouwbaarheid"><i class="fa fa-check"></i><b>12.2</b> Wat is betrouwbaarheid?</a></li>
<li class="chapter" data-level="12.3" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#testtheorie"><i class="fa fa-check"></i><b>12.3</b> Testtheorie</a></li>
<li class="chapter" data-level="12.4" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#interpretaties"><i class="fa fa-check"></i><b>12.4</b> Interpretaties</a></li>
<li class="chapter" data-level="12.5" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#methoden-om-betrouwbaarheid-te-schatten"><i class="fa fa-check"></i><b>12.5</b> Methoden om betrouwbaarheid te schatten</a></li>
<li class="chapter" data-level="12.6" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#betrouwbaarheid-tussen-beoordelaars"><i class="fa fa-check"></i><b>12.6</b> Betrouwbaarheid tussen beoordelaars</a></li>
<li class="chapter" data-level="12.7" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#betrouwbaarheid-en-constructvaliditeit"><i class="fa fa-check"></i><b>12.7</b> Betrouwbaarheid en constructvaliditeit</a></li>
<li class="chapter" data-level="12.8" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#spss-9"><i class="fa fa-check"></i><b>12.8</b> SPSS</a></li>
<li class="chapter" data-level="12.9" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#jasp-11"><i class="fa fa-check"></i><b>12.9</b> JASP</a></li>
<li class="chapter" data-level="12.10" data-path="ch-betrouwbaarheid.html"><a href="ch-betrouwbaarheid.html#r-11"><i class="fa fa-check"></i><b>12.10</b> R</a></li>
</ul></li>
<li class="part"><span><b>Deel III: Toetsende statistiek</b></span></li>
<li class="chapter" data-level="13" data-path="ch-toetsing.html"><a href="ch-toetsing.html"><i class="fa fa-check"></i><b>13</b> Toetsing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:toetsing-inleiding"><i class="fa fa-check"></i><b>13.1</b> Inleiding</a></li>
<li class="chapter" data-level="13.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-onesample"><i class="fa fa-check"></i><b>13.2</b> <span class="math inline">\(t\)</span>-toets voor enkele steekproef</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-vrijheidsgraden"><i class="fa fa-check"></i><b>13.2.1</b> vrijheidsgraden</a></li>
<li class="chapter" data-level="13.2.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-1"><i class="fa fa-check"></i><b>13.2.2</b> formules</a></li>
<li class="chapter" data-level="13.2.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-aannames"><i class="fa fa-check"></i><b>13.2.3</b> aannames</a></li>
<li class="chapter" data-level="13.2.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#spss-10"><i class="fa fa-check"></i><b>13.2.4</b> SPSS</a></li>
<li class="chapter" data-level="13.2.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:jaspttoetsenkel"><i class="fa fa-check"></i><b>13.2.5</b> JASP</a></li>
<li class="chapter" data-level="13.2.6" data-path="ch-toetsing.html"><a href="ch-toetsing.html#r-12"><i class="fa fa-check"></i><b>13.2.6</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:pgroterdannul"><i class="fa fa-check"></i><b>13.3</b> Overschrijdingskans <span class="math inline">\(p\)</span> is altijd groter dan nul</a></li>
<li class="chapter" data-level="13.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-eenzijdigtweezijdig"><i class="fa fa-check"></i><b>13.4</b> Eenzijdige en tweezijdige toetsen</a></li>
<li class="chapter" data-level="13.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:t-betrouwbaarheidsinterval-gemiddelde"><i class="fa fa-check"></i><b>13.5</b> Betrouwbaarheidsinterval van het gemiddelde</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-2"><i class="fa fa-check"></i><b>13.5.1</b> formules</a></li>
<li class="chapter" data-level="13.5.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#spss-11"><i class="fa fa-check"></i><b>13.5.2</b> SPSS</a></li>
<li class="chapter" data-level="13.5.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#jasp-12"><i class="fa fa-check"></i><b>13.5.3</b> JASP</a></li>
<li class="chapter" data-level="13.5.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#r-13"><i class="fa fa-check"></i><b>13.5.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-onafh"><i class="fa fa-check"></i><b>13.6</b> <span class="math inline">\(t\)</span>-toets voor twee onafhankelijke steekproeven</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-ongepaard-aannames"><i class="fa fa-check"></i><b>13.6.1</b> aannames</a></li>
<li class="chapter" data-level="13.6.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-formules"><i class="fa fa-check"></i><b>13.6.2</b> formules</a></li>
<li class="chapter" data-level="13.6.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:SPSS-ttoets-ongepaard"><i class="fa fa-check"></i><b>13.6.3</b> SPSS</a></li>
<li class="chapter" data-level="13.6.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:jaspttoetsongepaard"><i class="fa fa-check"></i><b>13.6.4</b> JASP</a></li>
<li class="chapter" data-level="13.6.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:R-ttoets-ongepaard"><i class="fa fa-check"></i><b>13.6.5</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-gepaard"><i class="fa fa-check"></i><b>13.7</b> <span class="math inline">\(t\)</span>-toets voor gepaarde waarnemingen</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#aannames-1"><i class="fa fa-check"></i><b>13.7.1</b> aannames</a></li>
<li class="chapter" data-level="13.7.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-4"><i class="fa fa-check"></i><b>13.7.2</b> formules</a></li>
<li class="chapter" data-level="13.7.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:SPSS-ttoets-gepaard"><i class="fa fa-check"></i><b>13.7.3</b> SPSS</a></li>
<li class="chapter" data-level="13.7.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:jaspttoetsgepaard"><i class="fa fa-check"></i><b>13.7.4</b> JASP</a></li>
<li class="chapter" data-level="13.7.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:R-ttoets-gepaard"><i class="fa fa-check"></i><b>13.7.5</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:ttoets-effectgrootte"><i class="fa fa-check"></i><b>13.8</b> Effectgrootte</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:formules13-5"><i class="fa fa-check"></i><b>13.8.1</b> formules</a></li>
<li class="chapter" data-level="13.8.2" data-path="ch-toetsing.html"><a href="ch-toetsing.html#spss-13-2"><i class="fa fa-check"></i><b>13.8.2</b> SPSS</a></li>
<li class="chapter" data-level="13.8.3" data-path="ch-toetsing.html"><a href="ch-toetsing.html#jasp-13"><i class="fa fa-check"></i><b>13.8.3</b> JASP</a></li>
<li class="chapter" data-level="13.8.4" data-path="ch-toetsing.html"><a href="ch-toetsing.html#r-14"><i class="fa fa-check"></i><b>13.8.4</b> R</a></li>
<li class="chapter" data-level="13.8.5" data-path="ch-toetsing.html"><a href="ch-toetsing.html#sec:betrouwbaarheidsinterval-effectgrootte"><i class="fa fa-check"></i><b>13.8.5</b> Betrouwbaarheidsinterval van de effectgrootte</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch-power.html"><a href="ch-power.html"><i class="fa fa-check"></i><b>14</b> Power</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch-power.html"><a href="ch-power.html#sec:power-inleiding"><i class="fa fa-check"></i><b>14.1</b> Inleiding</a></li>
<li class="chapter" data-level="14.2" data-path="ch-power.html"><a href="ch-power.html#sec:effectgrootte-power"><i class="fa fa-check"></i><b>14.2</b> Verband tussen effectgrootte en power</a></li>
<li class="chapter" data-level="14.3" data-path="ch-power.html"><a href="ch-power.html#sec:steekproefgrootte-power"><i class="fa fa-check"></i><b>14.3</b> Verband tussen steekproefgrootte en power</a></li>
<li class="chapter" data-level="14.4" data-path="ch-power.html"><a href="ch-power.html#sec:significantieniveau-power"><i class="fa fa-check"></i><b>14.4</b> Verband tussen significantieniveau en power</a></li>
<li class="chapter" data-level="14.5" data-path="ch-power.html"><a href="ch-power.html#nadelen-van-onvoldoende-power"><i class="fa fa-check"></i><b>14.5</b> Nadelen van onvoldoende power</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html"><i class="fa fa-check"></i><b>15</b> Variantieanalyse</a>
<ul>
<li class="chapter" data-level="15.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:inleiding"><i class="fa fa-check"></i><b>15.1</b> Inleiding</a></li>
<li class="chapter" data-level="15.2" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-voorbeelden"><i class="fa fa-check"></i><b>15.2</b> Enkele voorbeelden</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#aannames"><i class="fa fa-check"></i><b>15.2.1</b> aannames</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#eén-weg-variantieanalyse"><i class="fa fa-check"></i><b>15.3</b> Eén-weg-variantieanalyse</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-uitleg"><i class="fa fa-check"></i><b>15.3.1</b> Een intuïtieve uitleg</a></li>
<li class="chapter" data-level="15.3.2" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-formeel"><i class="fa fa-check"></i><b>15.3.2</b> Een formele uitleg</a></li>
<li class="chapter" data-level="15.3.3" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-effectgrootte"><i class="fa fa-check"></i><b>15.3.3</b> Effectgrootte</a></li>
<li class="chapter" data-level="15.3.4" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-gericht"><i class="fa fa-check"></i><b>15.3.4</b> Gerichte vergelijkingen</a></li>
<li class="chapter" data-level="15.3.5" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-oneway-posthoc"><i class="fa fa-check"></i><b>15.3.5</b> Post-hoc vergelijkingen</a></li>
<li class="chapter" data-level="15.3.6" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#spss-12"><i class="fa fa-check"></i><b>15.3.6</b> SPSS</a></li>
<li class="chapter" data-level="15.3.7" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#jasp-14"><i class="fa fa-check"></i><b>15.3.7</b> JASP</a></li>
<li class="chapter" data-level="15.3.8" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#r-15"><i class="fa fa-check"></i><b>15.3.8</b> R</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:tweeweg-anova"><i class="fa fa-check"></i><b>15.4</b> Tweeweg-variantieanalyse</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#een-intuïtieve-uitleg"><i class="fa fa-check"></i><b>15.4.1</b> Een intuïtieve uitleg</a></li>
<li class="chapter" data-level="15.4.2" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#een-formele-uitleg"><i class="fa fa-check"></i><b>15.4.2</b> Een formele uitleg</a></li>
<li class="chapter" data-level="15.4.3" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#sec:anova-twoway-posthoc"><i class="fa fa-check"></i><b>15.4.3</b> Post-hoc vergelijkingen</a></li>
<li class="chapter" data-level="15.4.4" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#spss-13"><i class="fa fa-check"></i><b>15.4.4</b> SPSS</a></li>
<li class="chapter" data-level="15.4.5" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#jasp-15"><i class="fa fa-check"></i><b>15.4.5</b> JASP</a></li>
<li class="chapter" data-level="15.4.6" data-path="ch-variantieanalyse.html"><a href="ch-variantieanalyse.html#r-16"><i class="fa fa-check"></i><b>15.4.6</b> R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html"><i class="fa fa-check"></i><b>16</b> Chi-kwadraat-toetsen</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#sec:h16inleiding"><i class="fa fa-check"></i><b>16.1</b> Inleiding</a></li>
<li class="chapter" data-level="16.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#sec:chi2gof"><i class="fa fa-check"></i><b>16.2</b> <span class="math inline">\(\chi^2\)</span>-toets voor “goodness of fit” in enkele steekproef</a></li>
<li class="chapter" data-level="16.3" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#chi2-toets-voor-homogeniteit-van-een-variabele-in-meerdere-steekproeven"><i class="fa fa-check"></i><b>16.3</b> <span class="math inline">\(\chi^2\)</span>-toets voor homogeniteit van een variabele in meerdere steekproeven</a></li>
<li class="chapter" data-level="16.4" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#chi2-toets-voor-verband-tussen-twee-variabelen-in-enkele-steekproef"><i class="fa fa-check"></i><b>16.4</b> <span class="math inline">\(\chi^2\)</span>-toets voor verband tussen twee variabelen in enkele steekproef</a></li>
<li class="chapter" data-level="16.5" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#sec:chi2toets-aannames"><i class="fa fa-check"></i><b>16.5</b> aannames</a></li>
<li class="chapter" data-level="16.6" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#formules-6"><i class="fa fa-check"></i><b>16.6</b> formules</a></li>
<li class="chapter" data-level="16.7" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#spss-14"><i class="fa fa-check"></i><b>16.7</b> SPSS</a>
<ul>
<li class="chapter" data-level="16.7.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-voorbereiding"><i class="fa fa-check"></i><b>16.7.1</b> goodness of fit: voorbereiding</a></li>
<li class="chapter" data-level="16.7.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-toetsing"><i class="fa fa-check"></i><b>16.7.2</b> goodness of fit: toetsing</a></li>
<li class="chapter" data-level="16.7.3" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-voorbereiding"><i class="fa fa-check"></i><b>16.7.3</b> kruistabellen: voorbereiding</a></li>
<li class="chapter" data-level="16.7.4" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-toetsing"><i class="fa fa-check"></i><b>16.7.4</b> kruistabellen: toetsing</a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#jasp-16"><i class="fa fa-check"></i><b>16.8</b> JASP</a>
<ul>
<li class="chapter" data-level="16.8.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-voorbereiding-1"><i class="fa fa-check"></i><b>16.8.1</b> goodness of fit: voorbereiding</a></li>
<li class="chapter" data-level="16.8.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-toetsing-1"><i class="fa fa-check"></i><b>16.8.2</b> goodness of fit: toetsing</a></li>
<li class="chapter" data-level="16.8.3" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-voorbereiding-1"><i class="fa fa-check"></i><b>16.8.3</b> kruistabellen: voorbereiding</a></li>
<li class="chapter" data-level="16.8.4" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-toetsing-1"><i class="fa fa-check"></i><b>16.8.4</b> kruistabellen: toetsing</a></li>
</ul></li>
<li class="chapter" data-level="16.9" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#r-17"><i class="fa fa-check"></i><b>16.9</b> R</a>
<ul>
<li class="chapter" data-level="16.9.1" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#goodness-of-fit-toetsing-2"><i class="fa fa-check"></i><b>16.9.1</b> goodness of fit: toetsing</a></li>
<li class="chapter" data-level="16.9.2" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#kruistabellen-voorbereiding-en-toetsing"><i class="fa fa-check"></i><b>16.9.2</b> kruistabellen: voorbereiding en toetsing</a></li>
</ul></li>
<li class="chapter" data-level="16.10" data-path="ch-chi-kwadraat-toetsen.html"><a href="ch-chi-kwadraat-toetsen.html#effectgrootte-odds-ratio"><i class="fa fa-check"></i><b>16.10</b> Effectgrootte: odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html"><i class="fa fa-check"></i><b>17</b> Andere nonparametrische toetsen</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:h17inleiding"><i class="fa fa-check"></i><b>17.1</b> Inleiding</a></li>
<li class="chapter" data-level="17.2" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#gepaarde-observaties-enkele-steekproef"><i class="fa fa-check"></i><b>17.2</b> Gepaarde observaties, enkele steekproef</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:tekentoets"><i class="fa fa-check"></i><b>17.2.1</b> Tekentoets</a></li>
<li class="chapter" data-level="17.2.2" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:Wilcoxon-signed-rank"><i class="fa fa-check"></i><b>17.2.2</b> Wilcoxon signed-ranks test</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#onafhankelijke-observaties-meerdere-steekproeven"><i class="fa fa-check"></i><b>17.3</b> Onafhankelijke observaties, meerdere steekproeven</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#mediaantoets"><i class="fa fa-check"></i><b>17.3.1</b> Mediaantoets</a></li>
<li class="chapter" data-level="17.3.2" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#sec:wilcoxon-rank-sum"><i class="fa fa-check"></i><b>17.3.2</b> Wilcoxon rank sum test, ofwel Mann-Whitney U test</a></li>
<li class="chapter" data-level="17.3.3" data-path="ch-andere-nonpar-toetsen.html"><a href="ch-andere-nonpar-toetsen.html#kruskall-wallis-h-test"><i class="fa fa-check"></i><b>17.3.3</b> Kruskall-Wallis H test</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Bijlagen</b></span></li>
<li class="chapter" data-level="A" data-path="app-randomgetallen.html"><a href="app-randomgetallen.html"><i class="fa fa-check"></i><b>A</b> Willekeurige getallen</a></li>
<li class="chapter" data-level="B" data-path="app-kritiekeZwaarden.html"><a href="app-kritiekeZwaarden.html"><i class="fa fa-check"></i><b>B</b> Standaard-normale kansverdeling</a></li>
<li class="chapter" data-level="C" data-path="app-kritieketwaarden.html"><a href="app-kritieketwaarden.html"><i class="fa fa-check"></i><b>C</b> Kritieke waarden van <span class="math inline">\(t\)</span>-verdeling</a></li>
<li class="chapter" data-level="D" data-path="app-kritiekechi2waarden.html"><a href="app-kritiekechi2waarden.html"><i class="fa fa-check"></i><b>D</b> Kritieke waarden van <span class="math inline">\(\chi^2\)</span>-verdeling</a></li>
<li class="chapter" data-level="" data-path="referenties.html"><a href="referenties.html"><i class="fa fa-check"></i>Referenties</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Gemaakt met bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Kwantitatieve Methoden en Statistiek</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch-kansverdelingen" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Hoofdstuk 10</span> Kansverdelingen<a href="ch-kansverdelingen.html#ch-kansverdelingen" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="sec:kansen" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Kansen<a href="ch-kansverdelingen.html#sec:kansen" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bellen achter het stuur vergroot de kans op een ongeluk <span class="citation">(<a href="#ref-Bhar13">Bhargava and Pathania 2013</a>)</span>. De
gemiddelde kans op neerslag in Nederland is 7%. Mijn bestelling heeft
10% kans om een dag later dan beloofd afgeleverd te worden. Kansen en
waarschijnlijkheden spelen een belangrijke rol in ons dagelijks leven,
en ook in het wetenschappelijk onderzoek. Immers, veel hypothesen zijn
probabilistisch van aard (zie Hoofdstuk <a href="ch-onderzoek.html#ch-onderzoek">2</a>):
de hypothesen doen uitspraken over
een verschil in <em>kansen</em> van uitkomsten. Om conclusies te kunnen trekken
ten aanzien van die probabilistische hypothesen hebben we enige kennis
nodig over waarschijnlijkheden, kansberekening, en kansverdelingen.
Daarover gaat dit hoofdstuk.</p>
<p>Laten we ter inleiding eens kijken naar een Nederlands <em>Scrabble</em>-spel.
Het spel bevat een zakje met daarin 102 fiches, met op elke fiche een
letter<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a>. Van de 102 fiches zijn er 6 met de letter A. Als ik uit een
vol en goed gemengd zakje één fiche neem, wat is dan de kans dat ik de
letter A tref? Die kans-op-uitkomst-A wordt aangeduid als
<span class="math inline">\(P(\textrm{A})\)</span>, met de <span class="math inline">\(P\)</span> van <em>Probabilitas</em> (Lat. “kans,
waarschijnlijkheid”), en is te bepalen als
<span class="math display" id="eq:kans-scrabble-1-A">\[\begin{equation}
    P(\textrm{A})=
    \frac{\textrm{aantal A&#39;s}}{\textrm{totaal aantal fiches}}=
    \frac{6}{102} = 0.0588
  \tag{10.1}
\end{equation}\]</span></p>
<p>De kans op een gebeurtenis wordt uitgedrukt als een proportie, een getal
tussen <span class="math inline">\(0\)</span> en <span class="math inline">\(1\)</span>, of als een percentage, d.w.z. een proportie in
eenheden van <span class="math inline">\(1/100\)</span>. Een kans kan dus nooit kleiner zijn dan <span class="math inline">\(0\)</span> en kan
nooit groter zijn dan 1: de kans is immers de verhouding tussen (teller)
aantal specifieke uitkomsten en (noemer) totaal aantal mogelijke
uitkomsten (zie
formule <a href="ch-kansverdelingen.html#eq:kans-scrabble-1-A">(10.1)</a>), waarbij deze teller nooit groter kan
zijn dan deze noemer <span class="citation">(<a href="#ref-SK01">Schuurman and De Kluiver 2001</a>)</span>.</p>
<p>Als twee uitkomsten elkaar wederzijds uitsluiten, zoals bij de
uitkomsten A of B in ons Scrabble-voorbeeld, dan mogen we de kansen van
die uitkomsten <em>optellen</em> (somregel). De kans op uitkomst A <em>of</em>
uitkomst B (waarbij de uitkomsten A en B elkaar uitsluiten), is de <em>som</em>
van <span class="math inline">\(P(\textrm{A})\)</span> en <span class="math inline">\(P(\textrm{B})\)</span>:
<span class="math display" id="eq:kans-somregel">\[\begin{equation}
    P(\textrm{A of B}) = P(\textrm{A}) + P(\textrm{B})
  \tag{10.2}
\end{equation}\]</span></p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.1:</em>
In ons Scrabble-voorbeeld is <span class="math inline">\(P(\textrm{A})=\frac{6}{102}\)</span> en
<span class="math inline">\(P(\textrm{B})=\frac{2}{102}\)</span>. De kans op uitkomst A-of-B is dan
<span class="math inline">\(P(\textrm{A of B})=P(\textrm{A})+P(\textrm{B})=6/102+2/102=8/102=.0784\)</span>.</p>
</blockquote>
<hr />
<p>Als ik uit een vol en goed gemengd zakje één fiche neem, dan zijn er
twee complementaire uitkomsten mogelijk: ik tref een A, of ik tref
<em>niet</em> een A. De uitkomsten sluiten elkaar weer wederzijds uit, dus ook
de kansen op deze uitkomsten mogen we optellen. Bovendien zijn de
uitkomsten complementair, d.w.z. de uitkomst kan alleen maar één van
deze twee mogelijke uitkomsten zijn. De respectievelijke kansen op deze
complementaire gebeurtenissen zijn dan ook complementair, d.w.z. deze
respectievelijke kansen tellen op tot precies <span class="math inline">\(1\)</span> =100%
(complementregel). Er is immers 100% kans dat de uitkomst één van de
twee mogelijke uitkomsten van de trekking is. Als we <span class="math inline">\(P(\textrm{A})\)</span> al
kennen kunnen we de kans op de complementaire uitkomst makkelijk
uitrekenen:
<span class="math display" id="eq:complementregel">\[\begin{align}
    P(\textrm{A}) + P(\textrm{niet-A}) &amp; = &amp; 1\\
    P(\textrm{A}) &amp; = &amp; 1 - P(\textrm{niet-A})\\
    P(\textrm{niet-A}) &amp; = &amp; 1 - P(\textrm{A})
    \tag{10.3}
\end{align}\]</span></p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.2:</em>
In ons Scrabble-voorbeeld is <span class="math inline">\(P(\textrm{A})=\frac{6}{102}\)</span>. De kans op
uitkomst niet-A is dan
<span class="math inline">\(P(\textrm{niet-A})= 1 - P(\textrm{A}) = 1 - \frac{6}{102} = \frac{96}{102} = .9412\)</span>.</p>
</blockquote>
<hr />
<p>Laten we als gedachten-experiment nu een tweede Scrabble-spel pakken, en
daaruit een tweede zakje met fiches pakken, eveneens vol en goed
gemengd. Uit elk zakje nemen we nu blind één letterfiche. Er zijn nu
twee gebeurtenissen of uitkomsten, nl. de uitkomst van de eerste
trekking (uit het eerste zakje), en de uitkomst van de tweede trekking
(uit het tweede zakje). Deze twee uitkomsten sluiten elkaar niet
wederzijds uit, want de twee uitkomsten hebben geen wederzijdse invloed
op elkaar. De uitkomst uit het tweede zakje wordt immers niet beïnvloed
door de uitkomst van het eerste zakje, of omgekeerd. We zeggen dan dat
deze uitkomsten <em>onafhankelijk</em> van elkaar zijn. Als de uitkomsten
inderdaad onafhankelijk van elkaar zijn, dan berekenen we de kans op een
combinatie van uitkomsten door de kansen te <em>vermenigvuldigen</em>
(productregel). De kans op de combinatie van uitkomst A <em>en</em> uitkomst B
(waarbij de uitkomsten A en B onafhankelijk van elkaar zijn), is het
<em>product</em> van <span class="math inline">\(P(\textrm{A})\)</span> en <span class="math inline">\(P(\textrm{B})\)</span>:
<span class="math display" id="eq:kans-productregel">\[\begin{equation}
    P(\textrm{A en B}) = P(\textrm{A}) \times P(\textrm{B})
  \tag{10.4}
\end{equation}\]</span></p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.3:</em>
In ons Scrabble-voorbeeld is <span class="math inline">\(P(\textrm{A})=\frac{6}{102}\)</span> en
<span class="math inline">\(P(\textrm{B})=\frac{2}{102}\)</span>. De kans op uitkomst A bij het eerste
zakje <em>en</em> B bij het tweede zakje is dan
<span class="math inline">\(P(\textrm{A en B})=P(\textrm{A}) \times P(\textrm{B})=\frac{6}{102} \times \frac{2}{102} = .0012\)</span>.</p>
</blockquote>
<hr />
<blockquote>
<p><em>Voorbeeld 10.4:</em>
In ons Scrabble-voorbeeld is <span class="math inline">\(P(\textrm{klinker})=\frac{38}{102}\)</span>. De kans
om een klinker (A, E, I, O, U, Y) te trekken uit het eerste zakje <em>en</em>
een klinker uit het tweede zakje is dan
<span class="math inline">\(P(\textrm{klinker-en-klinker})=P(\textrm{eerste klinker}) \times P(\textrm{tweede klinker})=\frac{38}{102} \times \frac{38}{102} = (\frac{38}{102})^2 = .1388\)</span>.</p>
</blockquote>
<hr />
</div>
<div id="sec:binomiaalverdeling" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Binomiale kansverdeling<a href="ch-kansverdelingen.html#sec:binomiaalverdeling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Voor het vervolg van dit hoofdstuk brengen we twee wijzigingen aan in
het Scrabble-spel. Ten eerste verwijderen we de 2 blanco fiches zonder
letter uit het zakje. Er blijven dan precies 100 fiches over, waarvan 38
met een klinker (vocaal, <span class="math inline">\(V\)</span>) en 62 met een medeklinker (consonant,
<span class="math inline">\(C\)</span>). Er blijven dus slechts twee mogelijke categorieën van uitkomsten
over, die elkaar wederzijds uitsluiten. Zo’n variabele van het nominale
meetnivo, met precies twee categorieën, noemen we bi-nomiaal
(‘twee-namig’). We beschouwen de klinkers als treffers, en de
medeklinkers als missers. Deze twee mogelijke uitkomsten zijn
complementair: <span class="math inline">\(P(V)=.38\)</span> (afgekort als <span class="math inline">\(p\)</span>) en <span class="math inline">\(P(C)=.62\)</span> (afgekort als
<span class="math inline">\(q=1-p\)</span>).</p>
<p>Ten tweede leggen we het getrokken letterfiche voortaan terug in het
zakje, nadat we de getrokken letter genoteerd hebben. Op die manier
hebben we niet tientallen complete letterzakjes nodig, maar slechts één
letterzakje dat na elke teruglegging weer compleet en goed gemengd is.
We beschouwen de uitkomsten van opeenvolgende trekkingen als
onafhankelijk.</p>
<p><strong>Terzijde:</strong> De uitkomst van een bepaalde trekking is dus onafhankelijk
van de uitkomst van vorige trekkingen. Als er zojuist <span class="math inline">\(100\times\)</span>
achtereen een klinker getrokken is, dan heeft dat geen enkele invloed op
(de uitkomst van) de eerstvolgende trekking uit het letterzakje. Het
letterzakje, of de hand van de trekker, heeft immers geen geheugen. Bij
<em>elke</em> trekking is de kans op een treffer <span class="math inline">\(p=.38\)</span>, ook als er zojuist
<span class="math inline">\(100\times\)</span> of <span class="math inline">\(1000\times\)</span> een klinker is getrokken. Hetzelfde geldt
voor de opeenvolgende uitkomsten bij roulette: bij elke ronde is de kans
op een treffer <span class="math inline">\(1/37\)</span>, ook als het balletje zojuist <span class="math inline">\(100\times\)</span> op
eenzelfde getal terecht is gekomen<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a>.</p>
<p>Laten we met bovengenoemde wijzigingen nu <span class="math inline">\(n=3\)</span> trekkingen uitvoeren
(met teruglegging, zie boven), en voor elke mogelijke uitkomst de kans
op die uitkomst bepalen, zie
Tabel <a href="ch-kansverdelingen.html#tab:klinkerkansen">10.1</a>.</p>
<table>
<caption><span id="tab:klinkerkansen">Tabel 10.1: </span> Kansen van mogelijke uitkomsten van <span class="math inline">\(n=3\)</span> trekkingen van klinkers,
<span class="math inline">\(p=.38\)</span>, met teruglegging (zie tekst).</caption>
<thead>
<tr class="header">
<th align="left">uitkomst</th>
<th align="center">aantal klinkers</th>
<th align="center">kans</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CCC</td>
<td align="center">0</td>
<td align="center"><span class="math inline">\(qqq = q^3\)</span></td>
</tr>
<tr class="even">
<td align="left">VCC</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(pqq = pq^2\)</span></td>
</tr>
<tr class="odd">
<td align="left">CVC</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(qpq = pq^2\)</span></td>
</tr>
<tr class="even">
<td align="left">CCV</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(qqp = pq^2\)</span></td>
</tr>
<tr class="odd">
<td align="left">VVC</td>
<td align="center">2</td>
<td align="center"><span class="math inline">\(ppq = p^2q\)</span></td>
</tr>
<tr class="even">
<td align="left">VCV</td>
<td align="center">2</td>
<td align="center"><span class="math inline">\(pqp = p^2q\)</span></td>
</tr>
<tr class="odd">
<td align="left">CVV</td>
<td align="center">2</td>
<td align="center"><span class="math inline">\(qpp = p^2q\)</span></td>
</tr>
<tr class="even">
<td align="left">VVV</td>
<td align="center">3</td>
<td align="center"><span class="math inline">\(ppp = p^3\)</span></td>
</tr>
</tbody>
</table>
<p>Het aantal treffers (klinkers) in de <span class="math inline">\(n=3\)</span> trekkingen heeft de
<em>kansverdeling</em> zoals samengevat in
Tabel <a href="ch-kansverdelingen.html#tab:binomkansverdeling3">10.2</a> (eerste en laatste kolom) en
Figuur <a href="ch-kansverdelingen.html#fig:binomkansverdeling3">10.1</a> (horizontale en verticale as).
In zo’n kansverdeling zien we voor elke mogelijke uitkomst van <span class="math inline">\(x\)</span> (hier:
aantal klinkers) hoe groot de kans op die uitkomst is.</p>
<table>
<caption><span id="tab:binomkansverdeling3">Tabel 10.2: </span> Kansverdeling van een binomiale variabele met <span class="math inline">\(n=3\)</span> en <span class="math inline">\(p=.38\)</span>.</caption>
<thead>
<tr class="header">
<th align="left">aantal klinkers</th>
<th align="right">kans</th>
<th align="center">kans</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="right"><span class="math inline">\(1 q^3\)</span></td>
<td align="center">= .2383</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="right"><span class="math inline">\(3 p q^2\)</span></td>
<td align="center">= .4383</td>
</tr>
<tr class="odd">
<td align="left">2</td>
<td align="right"><span class="math inline">\(3 p^2 q\)</span></td>
<td align="center">= .2686</td>
</tr>
<tr class="even">
<td align="left">3</td>
<td align="right"><span class="math inline">\(1 p^3\)</span></td>
<td align="center">= .0549</td>
</tr>
<tr class="odd">
<td align="left">som</td>
<td align="right"><span class="math inline">\((p+q)^3\)</span></td>
<td align="center">= 1.0000</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:binomkansverdeling3"></span>
<img src="KMS-NL_files/figure-html/binomkansverdeling3-1.png" alt="Kansverdeling van een binomiale variabele x met n=3 en p=.38." width="384" />
<p class="caption">
Figuur 10.1: Kansverdeling van een binomiale variabele x met n=3 en p=.38.
</p>
</div>
<p>De kansverdeling van een binomiale variabele noemen we de binomiale
kansverdeling, ook aangeduid als binomiale verdeling of
binomiaalverdeling. De exacte kansen van de binomiale kansverdeling kan
je uitrekenen met formule <a href="ch-kansverdelingen.html#eq:prob-binomial">(10.5)</a> hieronder.</p>
<div id="formules" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> formules<a href="ch-kansverdelingen.html#formules" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De kans op een <span class="math inline">\(x\)</span> aantal treffers in <span class="math inline">\(n\)</span> trekkingen is gegeven als
<span class="math display" id="eq:prob-binomial">\[\begin{equation}
  P(x\,\mbox{treffers}) = {n \choose x} p^x (1-p)^{n-x}
  \tag{10.5}
\end{equation}\]</span>
waarbij <span class="math inline">\(n\)</span> is het aantal trekkingen of pogingen, <span class="math inline">\(x\)</span> is het aantal treffers (tussen
0 en <span class="math inline">\(n\)</span>), en <span class="math inline">\(p\)</span> is de kans op een treffer.</p>
<p>De coëfficient <span class="math inline">\({n \choose x}\)</span> geeft het aantal verschillende ordeningen
aan waarin we een combinatie (greep) van <span class="math inline">\(x\)</span> elementen uit <span class="math inline">\(n\)</span> kunnen
kiezen. Bij <span class="math inline">\(x=1\)</span> klinker uit <span class="math inline">\(n=3\)</span> trekkingen zijn er drie
mogelijkheden: de ene klinker zou getrokken kunnen zijn in de eerste
trekking, of de tweede trekking, of de derde trekking, zie
Tabel <a href="ch-kansverdelingen.html#tab:klinkerkansen">10.1</a>. Het aantal verschillende mogelijke
ordeningen is gegeven als
<span class="math display" id="eq:choose">\[\begin{equation}
  {n \choose x} = \frac{n!}{x!(n-x)!}
  \tag{10.6}
\end{equation}\]</span>
waarbij
<span class="math inline">\(x! = x (x-1) (x-2) \dots \times 2 \times 1\)</span>, dus
<span class="math inline">\(4!=4\times3\times2\times1=24\)</span>.</p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.5:</em> Er staan 4 stoelen voor 2 personen. Op een stoel mag maximaal 1 persoon
plaatsnemen. Hoeveel verschillende ordeningen van <span class="math inline">\(x=2\)</span> personen over
<span class="math inline">\(n=4\)</span> stoelen zijn er mogelijk?</p>
</blockquote>
<blockquote>
<p>Antwoord: Er zijn
<span class="math inline">\({4 \choose 2} = \frac{4\times3\times2\times1}{2\times1\times2\times1} = \frac{24}{4} = 6\)</span>
mogelijke ordeningen, namelijk 1100, 1010, 1001, 0110, 0101, en 0011.</p>
</blockquote>
<hr />
<p>Deze binomiaal-coëfficienten, die het aantal verschillende mogelijke
ordeningen aangeven, zijn snel terug te vinden in de zogenaamde Driehoek
van Pascal, afgebeeld in Tabel <a href="ch-kansverdelingen.html#tab:driehoekpascal">10.3</a>.
Het aantal verschillende
ordeningen van <span class="math inline">\(x=2\)</span> personen over <span class="math inline">\(n=4\)</span> stoelen vinden we in rij <span class="math inline">\(n=4\)</span>.
De bovenste rij is die voor <span class="math inline">\(n=0\)</span>. De vijfde rij is die voor <span class="math inline">\(n=4\)</span> en we
zien daar achtereenvolgens de binomiaal-coëfficienten voor
<span class="math inline">\(x= 0, 1, 2, 3, 4\)</span>. Voor <span class="math inline">\({4 \choose 2}\)</span> vinden we daar de
binomiaalcoëfficient <span class="math inline">\(6\)</span>. Iedere coefficiënt is de som van de twee
bovenliggende coëfficienten<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a>, en iedere coëfficient is op te vatten
als het aantal mogelijke wegen afdalend van de top van de driehoek naar
die cel.</p>
<table>
<caption><span id="tab:driehoekpascal">Tabel 10.3: </span> Driehoek van Pascal: binomiaalcoëfficienten voor het aantal mogelijke ordeningen voor een combinatie van <span class="math inline">\(x\)</span> elementen uit <span class="math inline">\(n\)</span> (zie tekst).</caption>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(n= 0\)</span>:</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td align="center">1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(n= 1\)</span>:</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td align="center"></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n= 2\)</span>:</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td align="center">2</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(n= 3\)</span>:</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>3</td>
<td align="center"></td>
<td>3</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n= 4\)</span>:</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>4</td>
<td></td>
<td align="center">6</td>
<td></td>
<td>4</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(n= 5\)</span>:</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>5</td>
<td></td>
<td>10</td>
<td align="center"></td>
<td>10</td>
<td></td>
<td>5</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n= 6\)</span>:</td>
<td></td>
<td>1</td>
<td></td>
<td>6</td>
<td></td>
<td>15</td>
<td></td>
<td align="center">20</td>
<td></td>
<td>15</td>
<td></td>
<td>6</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(n= 7\)</span>:</td>
<td>1</td>
<td></td>
<td>7</td>
<td></td>
<td>21</td>
<td></td>
<td>35</td>
<td align="center"></td>
<td>35</td>
<td></td>
<td>21</td>
<td></td>
<td>7</td>
<td></td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Het gemiddelde en de standaarddeviatie van de binomiale kansverdeling
zijn <span class="math display">\[\begin{aligned}
    \mu &amp; = &amp; np \\
    \sigma &amp; = &amp; \sqrt{ np(1-p) }\end{aligned}\]</span></p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.6:</em>
De binomiale kansverdeling voor <span class="math inline">\(x\)</span> treffers uit <span class="math inline">\(n=3\)</span> trekkingen met
<span class="math inline">\(p=.38\)</span> kans op een treffer is afgebeeld in
Figuur <a href="ch-kansverdelingen.html#fig:binomkansverdeling3">10.1</a>. Deze binomiale kansverdeling heeft
een gemiddelde <span class="math inline">\(\mu=n \times p = 3 \times .38 = 1.14\)</span>, en een
standaarddeviatie
<span class="math inline">\(\sigma = \sqrt{n \times p \times (1-p)} = \sqrt{ 3 \times .38 \times .62} = 0.84\)</span>
.</p>
</blockquote>
<hr />
</div>
<div id="jasp-4" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> JASP<a href="ch-kansverdelingen.html#jasp-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De binomiale kansverdeling van Figuur <a href="ch-kansverdelingen.html#fig:binomkansverdeling3">10.1</a> kan in JASP worden verkregen door in de bovenbalk te klikken op:</p>
<pre><code>Distributions &gt; Binomial (onder &#39;Discrete&#39;)</code></pre>
<p>Als <code>Distributions</code> nog niet in de bovenbalk staat kun je dit toevoegen door rechtsbovenin op de blauwe <strong>+</strong>-button te klikken en <code>Distributions</code> aan te vinken. 
In de “Binomial” invoer is de balk <code>Show Distribution</code> als het goed is open. Pas hier de waarden voor <span class="math inline">\(p\)</span> (onder “free parameter”) en <span class="math inline">\(n\)</span> (onder “Fixed parameter”) aan naar <span class="math inline">\(p=0.38\)</span> en <span class="math inline">\(n=3\)</span>. Pas onder “Options” ook de range aan naar <code>Range of x from 0 to 3</code>. Onder “Display” moet <code>Probability mass function</code> aangevinkt zijn. In de uitvoer zie je onder <em>Probability Mass Plot</em> de binomiale kansverdeling.</p>
</div>
<div id="r-4" class="section level3 hasAnchor" number="10.2.3">
<h3><span class="header-section-number">10.2.3</span> R<a href="ch-kansverdelingen.html#r-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="ch-kansverdelingen.html#cb52-1" tabindex="-1"></a><span class="fu">dbinom</span>( <span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">prob=</span>.<span class="dv">38</span> )</span></code></pre></div>
<pre><code>## [1] 0.238328 0.438216 0.268584 0.054872</code></pre>
<p>De uitvoer is weergegeven in Tabel <a href="ch-kansverdelingen.html#tab:binomkansverdeling3">10.2</a> hierboven.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="ch-kansverdelingen.html#cb54-1" tabindex="-1"></a>matrixcalc<span class="sc">::</span><span class="fu">pascal.matrix</span>( <span class="dv">10</span> ) <span class="co"># links onder diagonaal is Driehoek van Pascal</span></span></code></pre></div>
<pre><code>##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    1    0    0    0    0    0    0    0    0     0
##  [2,]    1    1    0    0    0    0    0    0    0     0
##  [3,]    1    2    1    0    0    0    0    0    0     0
##  [4,]    1    3    3    1    0    0    0    0    0     0
##  [5,]    1    4    6    4    1    0    0    0    0     0
##  [6,]    1    5   10   10    5    1    0    0    0     0
##  [7,]    1    6   15   20   15    6    1    0    0     0
##  [8,]    1    7   21   35   35   21    7    1    0     0
##  [9,]    1    8   28   56   70   56   28    8    1     0
## [10,]    1    9   36   84  126  126   84   36    9     1</code></pre>
<p>De driehoek van Pascal is te vinden links onder de diagonaal van deze matrix.</p>
</div>
</div>
<div id="sec:normaalverdeling" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Normale kansverdeling<a href="ch-kansverdelingen.html#sec:normaalverdeling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Naarmate de steekproefgrootte <span class="math inline">\(n\)</span> toeneemt, gaat de binomiale
kansverdeling minder trapsgewijs verspringen, en wordt de kansverdeling
meer vloeiend, zoals te zien in
Figuur <a href="ch-kansverdelingen.html#fig:binomkansverdeling50n500">10.2</a>.</p>
<div class="figure"><span style="display:block;" id="fig:binomkansverdeling50n500"></span>
<img src="KMS-NL_files/figure-html/binomkansverdeling50n500-1.png" alt="Kansverdeling van een binomiale variabele x met n=50 (links) en n=500 (rechts) en p=.38." width="672" />
<p class="caption">
Figuur 10.2: Kansverdeling van een binomiale variabele x met n=50 (links) en n=500 (rechts) en p=.38.
</p>
</div>
<p>Bij een nog grotere steekproef wordt de kansverdeling een vloeiende lijn.
Deze kansverdeling komt zo vaak voor, dat dit de <em>normale kansverdeling</em>
of ‘normale verdeling’ wordt genoemd. De verdeling wordt ook wel
aangeduid als de Gaussische verdeling (vernoemd naar de wiskundige Carl
Friedrich Gauss, 1777–1855), of de ‘bell curve’ (naar de vorm). Heel
veel variabelen volgen bij benadering deze kansverdeling:
geboortegewicht, lichaamslengte, omvang van woordenschat, IQ, inhoud van
een pak melk van 1 liter ℮, duur van een telefoongesprek, enz enz. Voor
al deze variabelen hebben observaties dicht bij het gemiddelde een hoge
kans om voor te komen, en observaties die sterk afwijken van het
gemiddelde zijn relatief zeldzaam (lage kans).</p>
<div class="figure"><span style="display:block;" id="fig:normaalkansverdeling"></span>
<img src="KMS-NL_files/figure-html/normaalkansverdeling-1.png" alt="Normale kansverdeling van een variabele x met gemiddelde 0 en standaarddeviatie 1." width="672" />
<p class="caption">
Figuur 10.3: Normale kansverdeling van een variabele x met gemiddelde 0 en standaarddeviatie 1.
</p>
</div>
<p>De normale kansverdeling van variabele <span class="math inline">\(X\)</span> met gemiddelde <span class="math inline">\(\mu\)</span> en
standaarddeviatie <span class="math inline">\(\sigma\)</span> heeft de volgende kenmerken (zie
Figuur <a href="ch-kansverdelingen.html#fig:normaalkansverdeling">10.3</a>):</p>
<ul>
<li><p>de verdeling is symmetrisch rond het gemiddelde <span class="math inline">\(\mu\)</span>,</p></li>
<li><p>de verdeling is asymptotisch, d.w.z. de staarten lopen eindeloos
door,</p></li>
<li><p>het gemiddelde, de mediaan en de modus vallen samen,</p></li>
<li><p>de totale oppervlakte onder de curve, d.i. de totale kans op één van
de mogelijke uitkomsten, is gelijk aan 1,</p></li>
<li><p>de oppervlakte onder de curve geeft de kans aan op een waarde van <span class="math inline">\(X\)</span> binnen een bepaald interval,</p></li>
<li><p>de buigpunten van de curve (van hol naar bol en v.v.) liggen bij
<span class="math inline">\(X=\mu-\sigma\)</span> en <span class="math inline">\(X=\mu+\sigma\)</span>,</p></li>
<li><p>ongeveer 2/3 van de observaties ligt
tussen <span class="math inline">\(X=\mu-\sigma\)</span> en <span class="math inline">\(X=\mu+\sigma\)</span> (donkergrijs gebied;
<span class="math inline">\(P(-1&lt;x/\sigma&lt;1)=.6827\)</span> of 68%) en ongeveer 95% van de observaties ligt
tussen <span class="math inline">\(-2\sigma\)</span> en <span class="math inline">\(+2\sigma\)</span> (donkergrijs plus lichtgrijze
gebieden; <span class="math inline">\(P(-2&lt;x/\sigma&lt;2)=.9546\)</span>), dit staat bekend als de
Empirical Rule.</p></li>
</ul>
<p>Een normale kansverdeling met <span class="math inline">\(\mu=0\)</span> en <span class="math inline">\(\sigma=1\)</span> wordt aangeduid als
de standaard-normale kansverdeling. Zoals we al eerder zagen
(§<a href="ch-centrumenspreiding.html#sec:standaardscores">9.8</a>) kunnen we een normaal-verdeelde
variabele <span class="math inline">\(x\)</span> standaardiseren, d.w.z. de observaties transformeren naar
een standaardscore of <span class="math inline">\(z\)</span>-score: <span class="math inline">\(z = (x-\overline{x})/s\)</span>.
De kansverdeling in
Figuur <a href="ch-kansverdelingen.html#fig:normaalkansverdeling">10.3</a> is die van de standaard-normale
kansverdeling van <span class="math inline">\(Z\)</span>, oftewel de kansverdeling van <span class="math inline">\((X-\mu)/\sigma\)</span>.</p>
<p>De kansverdeling van een normaal verdeelde variabele <span class="math inline">\(X\)</span> zou je zelf
kunnen uitrekenen met behulp van formule
<a href="ch-kansverdelingen.html#eq:prob-normal">(10.8)</a> hieronder. Maar het is handiger om daarvoor
een tabel te gebruiken; die staat in
Bijlage <a href="app-kritiekeZwaarden.html#app-kritiekeZwaarden">B</a>.
In grafische vorm uitgelegd geven die tabellen je,
voor verschillende oppervlakten ofwel kansen <span class="math inline">\(p\)</span> aan de rechter zijde onder de curve,
de positieve waarde van <span class="math inline">\(Z^*\)</span> die de linkergrens vormt
van die oppervlakte. Dat betekent dus dat je precies de kans <span class="math inline">\(p\)</span> hebt om
een waarde te vinden van <span class="math inline">\(Z\)</span> die even groot als of groter dan deze
ondergrens <span class="math inline">\(Z^*\)</span> is (mits de variabele inderdaad normaal verdeeld is).</p>
<hr />
<blockquote>
<p>Voorbeeld 10.7: Aan de rechterzijde van Figuur <a href="ch-kansverdelingen.html#fig:normaalkansverdeling">10.3</a> zien we een klein wit oppervlak onder de curve. Dit oppervlak geeft de kans weer dat <span class="math inline">\(Z&gt;2\)</span>. Het oppervlak heeft een omvang van 0.0228. De kans om een waarde van <span class="math inline">\(Z&gt;2\)</span> te vinden is dus 0.0228 ofwel iets minder dan 2.5%. (Tip: relateer deze kans aan de bovengenoemde Empirical Rule).</p>
</blockquote>
<hr />
<p>In Bijlage <a href="app-kritiekeZwaarden.html#app-kritiekeZwaarden">B</a> vind je gemakshalve niet een maar twee
tabellen, elk bestaande uit meerdere kolom-aanduidingen en één rij van
cellen. De eerste tabel geeft je, voor verschillende ‘afgeronde’ kansen
<span class="math inline">\(p\)</span> (kolommen), de kritieke waarde <span class="math inline">\(Z^*\)</span> (cellen) waarvoor geldt dat de
kans <span class="math inline">\(p\)</span> om een waarde van <span class="math inline">\(Z\)</span> te vinden die even groot als of groter
dan deze kritieke waarde <span class="math inline">\(Z^*\)</span> is, precies gelijk is aan de waarde <span class="math inline">\(p\)</span>
bovenaan de kolom. De tweede tabel werkt net zo, maar dan voor
‘afgeronde’ waarden van <span class="math inline">\(Z^*\)</span> in de cellen, en precieze kansen <span class="math inline">\(p\)</span> in de
kolom-aanduidingen.</p>
<p>Wat is de kans <span class="math inline">\(p\)</span> dat <span class="math inline">\(Z&gt;1\)</span>? In de tweede deeltabel, tweede kolom,
vinden we <span class="math inline">\(p=0.1587\)</span>. We weten daarmee ook dat <span class="math inline">\(P(Z&lt;1)\)</span> wel
<span class="math inline">\(1-0.1587=0.8413\)</span> moet zijn. Bovendien weten we dat de verdeling
symmetrisch is (zie hierboven), dus weten we dat <span class="math inline">\(P(Z&lt; -1)\)</span> ook <span class="math inline">\(.1587\)</span>
moet zijn. Wat is de kans <span class="math inline">\(p\)</span> dat <span class="math inline">\(Z&gt;3\)</span> is? In de tweede deeltabel
vinden we voor grenswaarde <span class="math inline">\(Z^*=3\)</span> de overschrijdingskans
<span class="math inline">\(p=0.0013\)</span>. Voor een normaal verdeelde variabele <span class="math inline">\(Z\)</span> is er dus een
overschrijdingskans <span class="math inline">\(p=0.0013\)</span> (meestal gerapporteerd als <span class="math inline">\(p=.001\)</span>) om een waarde van <span class="math inline">\(Z\)</span> te vinden die
tenminste drie standaarddeviaties boven het gemiddelde ligt.</p>
<p>Vaak willen we het omgekeerde weten: als we een bepaalde
overschrijdingskans kiezen, welke grenswaarde <span class="math inline">\(Z^*\)</span> hoort daar dan bij?
Welke grenswaarde onderscheidt de hoogste 5% van de observaties van de
onderste 95% (<span class="math inline">\(p=0.05\)</span>)? In de eerste deeltabel vinden we
voor overschrijdingskans <span class="math inline">\(p=0.05\)</span> de grenswaarde <span class="math inline">\(Z^*=1.645\)</span>. Deze
grenswaarde, teruggerekend naar de oorspronkelijke variabele, wordt dan
vaak aangeduid als het 95e percentiel of ‘P95’ van de verdeling. Wie
tenminste deze score heeft behaald, behoort bij de beste 5% en heeft het dus
beter gedaan dan 95% van de deelnemers.</p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.8:</em>
Extreme waarden komen bij een normaal-verdeelde variabele per definitie
weinig voor. Maar wat is de grens voor een extreme waarde? Laten we
aannemen dat we niet meer dan 5% van alle observaties als extreem willen
beschouwen. De normale kansverdeling is symmetrisch, dus van die 5% is
te verwachten dat de ene helft (2.5%) ligt aan het linker uiteinde van
de verdeling, en de andere 2.5% aan de rechterzijde. Welke grenswaarde
<span class="math inline">\(Z^*\)</span> correspondeert met deze overschrijdingskans <span class="math inline">\(p=0.025\)</span>?</p>
</blockquote>
<blockquote>
<p>In Bijlage @ref(app- kritiekeZwaarden) nemen we de eerste deeltabel. In de kolom
voor overschrijdingskans <span class="math inline">\(p=0.025\)</span>, vinden we grenswaarde
<span class="math inline">\(Z^*=1.960\)</span>. Als we een observatie vinden met <span class="math inline">\(Z \ge 1.960\)</span> of met
<span class="math inline">\(Z \le -1.960\)</span> dan beschouwen we dat als een extreme, zeldzame
observatie.</p>
</blockquote>
<hr />
<blockquote>
<p><em>Voorbeeld 10.9:</em>
Intelligentie wordt uitgedrukt als een IQ-score, een variabele met een
normale kansverdeling met <span class="math inline">\(\mu=100\)</span> en <span class="math inline">\(\sigma=15\)</span>. “Membership of Mensa
is open to persons who have attained a score within the upper two
percent of the general population on an approved intelligence test that
has been properly administered and supervised”
(<a href="www.mensa.org">www.mensa.org</a>). Welke IQ-score moet je tenminste
behalen om lid te kunnen worden?</p>
</blockquote>
<blockquote>
<p>Antwoord: Het 98e percentiel van een standaard-normaal verdeelde
variabele ligt bij <span class="math inline">\(Z^*=+2.0537\)</span>, en dus met
<span class="math inline">\(x=\overline{x}+2.0537 s = 100+30.8 = 130.8\)</span>. Naar boven afgerond moet
je dus een IQ-score behalen van 131 punten of hoger.</p>
</blockquote>
<hr />
<blockquote>
<p><em>Voorbeeld 10.10:</em>
Verifieer de bovengenoemde Empirical Rule met behulp van
Bijlage <a href="app-kritiekeZwaarden.html#app-kritiekeZwaarden">B</a>.</p>
</blockquote>
<hr />
<!-- 
De tweede tabel in Bijlage \@ref{app-kritiekeZwaarden} geeft je ook, 
voor verschillende positieve waarden van die
ondergrens $Z^*$, de precieze kans $p$ om een waarde te vinden van $Z$
die even groot als of groter dan deze ondergrens $Z^*$ is. Die precieze
kans $p$ noemen we de *overschrijdingskans* behorend bij die waarde van
$Z$ volgens de kansverdeling.
-->
<div id="formules-1" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> formules<a href="ch-kansverdelingen.html#formules-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Als variabele <span class="math inline">\(X\)</span> een normale kansverdeling heeft, met gemiddelde <span class="math inline">\(\mu\)</span>
en standaarddeviatie <span class="math inline">\(\sigma\)</span>, dan wordt dat aangegeven als
<span class="math display" id="eq:normaalverdeeld">\[\begin{equation}
  X \sim \mathcal{N}(\mu,\sigma)
  \tag{10.7}
\end{equation}\]</span></p>
<p>De normale kansverdeling van variabele <span class="math inline">\(X\)</span> met gemiddelde <span class="math inline">\(\mu\)</span> en
standaarddeviatie <span class="math inline">\(\sigma\)</span> is
<span class="math display" id="eq:prob-normal">\[\begin{equation}
  P(X) = \frac{1}{\sigma \sqrt{2\pi}} \mbox{e}^{ \frac{-(X-\mu)^2}{2\sigma^2} }.
  \tag{10.8}
\end{equation}\]</span></p>
<p>De standaard-normale kansverdeling van variabele <span class="math inline">\(Z\)</span> met gemiddelde
<span class="math inline">\(\mu=0\)</span> en standaarddeviatie <span class="math inline">\(\sigma=1\)</span> is
<span class="math display" id="eq:prob-standaardnormaal">\[\begin{equation}
    P(Z) = \frac{1}{\sqrt{2\pi}} \mbox{e}^{ \frac{-Z^2}{2} }
  \tag{10.9}
\end{equation}\]</span></p>
</div>
<div id="jasp-5" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> JASP<a href="ch-kansverdelingen.html#jasp-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De normale kansverdeling van Figuur <a href="ch-kansverdelingen.html#fig:normaalkansverdeling">10.3</a> kan in JASP worden verkregen door in de bovenbalk te klikken op:</p>
<pre><code>Distributions &gt; Normal (onder &#39;Continuous&#39;)</code></pre>
<p>Als <code>Distributions</code> nog niet in de bovenbalk staat kun je dit toevoegen door rechtsbovenin op de blauwe <strong>+</strong>-button te klikken en <code>Distributions</code> aan te vinken.<br />
In de “Normal” invoer is de balk <code>Show Distribution</code> als het goed is open. Automatisch staan de waarden voor de standaard-normale kansverdeling al ingevuld en <code>Probability density function</code> aangevinkt; je ziet deze verdeling dus meteen in de uitvoer onder <em>Density Plot</em>.<br />
Voor andere normale kansverdelingen kunnen de waarden voor <span class="math inline">\(\mu\)</span> en <span class="math inline">\(\sigma\)</span> worden aangepast, en ook de range die wordt weergegeven (onder “Options”). Let op dat je bij “Parameters” <code>$\mu$, $\sigma$</code> selecteert als je het gemiddelde en de standaarddeviatie ingeeft (voor de standaard-normale kansverdeling maakt dit niet uit, want bij <span class="math inline">\(\sigma=1\)</span> geldt ook <span class="math inline">\(\sigma^2=1\)</span>).</p>
</div>
<div id="r-5" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> R<a href="ch-kansverdelingen.html#r-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De normale kansverdeling van Figuur <a href="ch-kansverdelingen.html#fig:normaalkansverdeling">10.3</a> kan in R worden afgebeeld
met het onderstaande commando. Hierin wordt een <code>curve</code> getekend, met <code>x</code> in het aangegeven domein, en waarbij <code>y</code> het resultaat is van de functie die de normale kansverdeling berekent volgens formule <a href="ch-kansverdelingen.html#eq:prob-normal">(10.8)</a>:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="ch-kansverdelingen.html#cb57-1" tabindex="-1"></a><span class="fu">curve</span>( <span class="fu">dnorm</span>( x, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span> ), <span class="co"># functie die y-waarden geeft, normal density</span></span>
<span id="cb57-2"><a href="ch-kansverdelingen.html#cb57-2" tabindex="-1"></a>       <span class="at">from=</span><span class="sc">-</span><span class="dv">5</span>, <span class="at">to=</span><span class="sc">+</span><span class="dv">5</span>, <span class="co"># domein van x</span></span>
<span id="cb57-3"><a href="ch-kansverdelingen.html#cb57-3" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">4</span>, <span class="co"># line width is 4x normaal</span></span>
<span id="cb57-4"><a href="ch-kansverdelingen.html#cb57-4" tabindex="-1"></a>       <span class="at">xlab=</span><span class="st">&quot;x&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;P(x)&quot;</span> <span class="co"># labels langs x-as en y-as</span></span>
<span id="cb57-5"><a href="ch-kansverdelingen.html#cb57-5" tabindex="-1"></a>       )</span></code></pre></div>
<p><img src="KMS-NL_files/figure-html/normkansverdeling.dnorm-1.png" width="672" /></p>
<p>Als je een extra argument <code>curve( ..., add=TRUE )</code> opgeeft, dan wordt de curve toegevoegd aan de meest recente plot (zie bijv. Figuur <a href="ch-kansverdelingen.html#fig:itunesmeanshist">10.6</a> hieronder).</p>
</div>
</div>
<div id="sec:isvarnormaalverdeeld" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Heeft mijn variabele een normale kansverdeling?<a href="ch-kansverdelingen.html#sec:isvarnormaalverdeeld" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Het langste nummer in mijn digitale muziekbibliotheek duurt ongeveer 50
minuten (dat is een klassiek-indiaas muziekstuk, een ‘morning raga’).
Een histogram van de duren van alle muzieknummers zie je in
Figuur <a href="ch-kansverdelingen.html#fig:itunestimeshist">10.4</a>.</p>
<div class="figure"><span style="display:block;" id="fig:itunestimeshist"></span>
<img src="KMS-NL_files/figure-html/itunestimeshist-1.png" alt="Histogram van de duren van muzieknummers in mijn digitale muziekbibliotheek." width="672" />
<p class="caption">
Figuur 10.4: Histogram van de duren van muzieknummers in mijn digitale muziekbibliotheek.
</p>
</div>
<p>Dit histogram laat zien dat deze duren
duidelijk <em>niet</em> een normale kansverdeling volgen: de verdeling is niet
symmetrisch, en de onderste staart loopt niet eindeloos door (er zijn
geen muzieknummers met negatieve duren).</p>
<p>Ook het gemiddelde <span class="math inline">\(\bar{x} =\)</span> 4.698 en
standaarddeviatie <span class="math inline">\(s =\)</span> 5.11
wijzen op een niet-normale kansverdeling:
bij een normale verdeling verwachten we dat slechts <span class="math inline">\((68/2)+50=84\)</span>% van de duren langer duurt dan
<span class="math inline">\(\bar{x}-s\approx 0\)</span> minuten, maar in werkelijkheid duurt 100%
(dus een groter deel dan verwacht) langer dan 0 minuten.</p>
<p>Een veel gebruikte manier om te inspecteren of een variabele <span class="math inline">\(X\)</span> een
normale kansverdeling heeft, is om een grafiek te maken met de
geobserveerde waarden langs de ene as (hier de horizontale), en de corresponderende <span class="math inline">\(z\)</span>-scores
langs de andere as. Zo’n figuur wordt een quantile-quantile-plot of
QQ-plot genoemd; de QQ-plot voor de duren in mijn muziekbibliotheek zie
je in Figuur <a href="ch-kansverdelingen.html#fig:itunestimesqqplot">10.5</a>.</p>
<div class="figure"><span style="display:block;" id="fig:itunestimesqqplot"></span>
<img src="KMS-NL_files/figure-html/itunestimesqqplot-1.png" alt="Quantile-quantile-plot van de duren van muzieknummers in mijn digitale muziekbibliotheek." width="672" />
<p class="caption">
Figuur 10.5: Quantile-quantile-plot van de duren van muzieknummers in mijn digitale muziekbibliotheek.
</p>
</div>
<p>Als de duren een normale kansverdeling zouden hebben (normaal zouden
zijn verdeeld), dan zouden er een aantal negatieve duren moeten zijn, en
er zouden dan veel meer duren tussen 8 en 14 minuten moeten zijn (i.p.v.
tussen 8 en 50 minuten). De afwijkingen van de rechte lijn in
Figuur <a href="ch-kansverdelingen.html#fig:itunestimesqqplot">10.5</a> geven dus aan dat de geobserveerde
duren niet een normale kansverdeling volgen, zoals we al zagen in het
histogram (Figuur <a href="ch-kansverdelingen.html#fig:itunestimeshist">10.4</a>).</p>
<p>Er zijn ook verschillende statistische toetsen om te onderzoeken of een
variabele een normale kansverdeling heeft. De twee meest gebruikte zijn
de Shapiro-Wilk-toets (met toetsingsgrootheid <span class="math inline">\(W\)</span>) voor normaliteit, en
de Kolmogorov-Smirnov-toets (met toetsingsgrootheid <span class="math inline">\(D\)</span>) voor
normaliteit. Beide toetsen onderzoeken de
H0:<span class="math inline">\(X\sim\mathcal{N}(\bar{X},s)\)</span> (zie
formule <a href="ch-kansverdelingen.html#eq:normaalverdeeld">(10.7)</a>).</p>
<div id="spss-4" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> SPSS<a href="ch-kansverdelingen.html#spss-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>Analyze &gt; Descriptive Statistics &gt; Explore...</code></pre>
<p>Selecteer variabele Time (sleep naar Dependent List paneel).<br />
Kies knop <code>Plots</code>, en vink aan <code>Normality plots with tests</code>, dat
betekent ‘als je een QQ-plot oftewel Normality plot maakt, voer dan ook toetsen
op normaliteit uit’. Bevestig met <code>Continue</code> en daarna met <code>OK</code>. De
uitvoer bevat eerst de resultaten van de Shapiro-Wilks-toets en de
Kolmogorov-Smirnov toets. Volgens beide toetsen is de kans om deze
verdeling te vinden, als H0 waar is, bijna nul — zie echter de
waarschuwing in
§<a href="ch-toetsing.html#sec:pgroterdannul">13.3</a>! We verwerpen daarom H0 en concluderen
dat de duren van muzieknummers niet normaal verdeeld zijn. Na deze
toetsresultaten volgt o.a. een QQ-plot.</p>
</div>
<div id="jasp-6" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> JASP<a href="ch-kansverdelingen.html#jasp-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Klik in de bovenbalk op <code>Descriptives</code> en selecteer variabele Time in het veld “Variables”. Klik de balk <code>Plots</code> open en vink <code>Distribution plots</code> aan onder “Basic plots” voor een histogram. Vink ook <code>Q-Q plots</code> aan voor een quantile-quantile plot. Klik vervolgens de balk <code>Statistics</code> open en vink <code>Shapiro-Wilk test</code> aan onder “Distribution”.<br />
De uitvoer geeft de uitkomst van de Shapiro-Wilk-toets in de tabel <em>Descriptive Statistics</em>. We zien dat de kans om deze verdeling te vinden, als H0 waar is, bijna nul is. H0 wordt dus verworpen en we concluderen dat de duren van de muzieknummers niet normaal verdeeld zijn. Dit kun je ook terugzien in het histogram en de Q-Q plot.</p>
</div>
<div id="r-6" class="section level3 hasAnchor" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> R<a href="ch-kansverdelingen.html#r-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="ch-kansverdelingen.html#cb59-1" tabindex="-1"></a>itunes <span class="ot">&lt;-</span> <span class="fu">read.table</span>( <span class="at">file=</span><span class="st">&quot;data/itunestimes20120511.txt&quot;</span>, <span class="at">header=</span><span class="cn">TRUE</span> )</span>
<span id="cb59-2"><a href="ch-kansverdelingen.html#cb59-2" tabindex="-1"></a><span class="co"># Size in bytes, Time in ms</span></span>
<span id="cb59-3"><a href="ch-kansverdelingen.html#cb59-3" tabindex="-1"></a><span class="fu">qqnorm</span>(itunes<span class="sc">$</span>Time<span class="sc">/</span><span class="dv">60000</span>, <span class="at">datax=</span>T, <span class="at">plot.it=</span><span class="cn">FALSE</span>) <span class="co"># normally we&#39;d use plot.it=TRUE  </span></span>
<span id="cb59-4"><a href="ch-kansverdelingen.html#cb59-4" tabindex="-1"></a><span class="co"># qqline(itunes$Time/60000, datax=T, col=&quot;purple&quot;, lwd=T) # see QQ-plot above</span></span></code></pre></div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="ch-kansverdelingen.html#cb60-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(itunes<span class="sc">$</span>Time<span class="sc">/</span><span class="dv">60000</span>)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  itunes$Time/60000
## W = 0.50711, p-value &lt; 2.2e-16</code></pre>
<p>Volgens deze toets is de kans om deze verdeling te vinden, als H0 waar
is, bijna nul, nl. kleiner dan <span class="math inline">\(2.2 \times 10^{-16}\)</span> (d.i. kleiner dan
het kleinste getal dat het analysepakket hier kan weergeven). We
verwerpen daarom H0 en concluderen dat de duren van muzieknummers niet
normaal verdeeld zijn.</p>
</div>
</div>
<div id="sec:watalsnietnormaal" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Wat als mijn variabele niet normaal verdeeld is?<a href="ch-kansverdelingen.html#sec:watalsnietnormaal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In Deel III zullen we diverse statistische
toetsen bespreken. De toetsen die we bespreken in hoofdstukken
<a href="ch-toetsing.html#ch-toetsing">13</a> en <a href="ch-power.html#ch-power">14</a> en <a href="ch-variantieanalyse.html#ch-variantieanalyse">15</a>
vereisen echter dat de afhankelijke
variabele een normale kansverdeling heeft. Als een variabele <em>niet</em> een
(ongeveer) normale kansverdeling heeft, dan kan die variabele dus niet
zomaar gebruikt worden voor statistische toetsing met de daar behandelde
statistische toetsen, of exacter gezegd, de conclusies uit zo’n
statistische toetsing zijn dan niet valide. Wat te doen? Er zijn dan
twee mogelijkheden.</p>
<p>Ten eerste is het mogelijk om de afhankelijke variabele <span class="math inline">\(y\)</span> te
transformeren, d.w.z. dat we er een rekenkundige bewerking op loslaten.
Als het goed is, resulteert dat in een variabele <span class="math inline">\(y&#39;\)</span> die wèl bij
benadering normaal verdeeld is. Veel gebruikte transformaties zijn:
logaritmiseren (<span class="math inline">\(y&#39;=\log{y}\)</span>), worteltrekken (<span class="math inline">\(y&#39;=\sqrt{y}\)</span>), of
inverteren (<span class="math inline">\(y&#39;=1/y\)</span>). Vervolgens wordt de getransformeerde
afhankelijke variabele <span class="math inline">\(y&#39;\)</span> gebruikt voor de statistische toetsing.
Uiteraard moet je wel controleren of de nieuwe afhankelijke variabele
<span class="math inline">\(y&#39;\)</span> inderdaad (bij benadering) normaal verdeeld is. Ook moet je bij de
interpretatie van de resultaten van de analyse rekening houden met de
uitgevoerde transformatie!</p>
<p>Ten tweede is het soms mogelijk om een andere statistische toets te
gebruiken, die niet vereist dat de afhankelijke variabele normaal
verdeeld is. Dat worden non-parametrische toetsen genoemd. We gaan er
nader op in in de hoofdstukken <a href="ch-chi-kwadraat-toetsen.html#ch-chi-kwadraat-toetsen">16</a> en
<a href="ch-andere-nonpar-toetsen.html#ch-andere-nonpar-toetsen">17</a>.
Die toetsen hebben wel als nadeel
dat ze minder statistische power hebben (voor een bespreking van power,
zie hoofdstuk <a href="ch-power.html#ch-power">14</a>): ze zijn minder gevoelig, en vereisen dus grotere
steekproeven om een effect vast te stellen.</p>
</div>
<div id="sec:CentraalLimietTheorema" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Kansverdeling van gemiddelde<a href="ch-kansverdelingen.html#sec:CentraalLimietTheorema" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In deze paragraaf beschouwen we de muzieknummers in mijn digitale
muziekbibliotheek als een <em>populatie</em>. We nemen nu een willekeurige
steekproef van <span class="math inline">\(n=\)</span> 50 nummers, en bepalen de gemiddelde duur over deze
50 muzieknummers in de steekproef:
stel <span class="math inline">\(\bar{x} =\)</span> 4.401 minuten. Opvallend
genoeg ligt dit gemiddelde van de steekproef dicht bij het gemiddelde
van de populatie (<span class="math inline">\(\mu =\)</span> 4.615 minuten, zie hierboven).
Deze operatie herhalen we
<span class="math inline">\(250\times\)</span>: we krijgen zo 250 steekproefgemiddelden. De
frequentieverdeling van die 250 steekproefgemiddelden zie je in
Figuur <a href="ch-kansverdelingen.html#fig:itunesmeanshist">10.6</a>.</p>
<div class="figure"><span style="display:block;" id="fig:itunesmeanshist"></span>
<img src="KMS-NL_files/figure-html/itunesmeanshist-1.png" alt="Frequentieverdeling van 250 gemiddelden, elk over een willekeurige steekproef van $n=50$ muzieknummers (de afhankelijke variabele is de duur van een muzieknummer, in minuten). De bijpassende normaalverdeling is aangegeven als een vloeiende curve." width="672" />
<p class="caption">
Figuur 10.6: Frequentieverdeling van 250 gemiddelden, elk over een willekeurige steekproef van <span class="math inline">\(n=50\)</span> muzieknummers (de afhankelijke variabele is de duur van een muzieknummer, in minuten). De bijpassende normaalverdeling is aangegeven als een vloeiende curve.
</p>
</div>
<p>Opvallend genoeg vertonen deze <em>gemiddelden</em> van (de afhankelijke
variabele <span class="math inline">\(X\)</span> in) de steekproeven <em>wel</em> een min of meer normale kansverdeling, of de
variabele <span class="math inline">\(X\)</span> in de populatie nu wel of niet normaal verdeeld is. Anders
gezegd, de kansverdeling van een steekproefgemiddelde benadert <em>altijd</em> de
normale kansverdeling, ongeacht de kansverdeling van de betreffende
variabele in de populatie, indien tenminste de steekproef voldoende
groot was. (Dit staat bekend als het Centraal Limiet Theorema). Lees de
bovenstaande zinnen nog eens aandachtig door. Als vuistregel geldt dat
de omvang van de steekproef, <span class="math inline">\(n\)</span>, tenminste 30 moet zijn. Naarmate de
steekproef groter is, wijkt de kansverdeling van de
steekproefgemiddelden minder af van de normaalverdeling.</p>
<p>De normale kansverdeling van de steekproefgemiddelden heeft een eigen
gemiddelde, <span class="math inline">\(\mu_{\bar{X}}\)</span>, en een eigen standaarddeviatie,
<span class="math inline">\(s_{\bar{X}}\)</span>. Hiervoor geldt:
<span class="math display" id="eq:meanofmean">\[\begin{equation}
    \mu_{\bar{X}} = \mu_X
    \tag{10.10}
\end{equation}\]</span>
en
<span class="math display" id="eq:sem">\[\begin{equation}
    s_{\bar{X}} = \frac{s}{\sqrt{n}}
    \tag{10.11}
\end{equation}\]</span>
De standaarddeviatie van het
gemiddelde, <span class="math inline">\(s_{\bar{X}}\)</span>, staat ook bekend als de ‘standard error of
the mean’. De steekproefgemiddelden <span class="math inline">\(\bar{X}\)</span> hebben minder spreiding
dan de afzonderlijke observaties <span class="math inline">\(X\)</span>, en de gemiddelden variëren ook
minder naarmate er gemiddeld is over een grotere steekproef, zoals ook
blijkt uit formule <a href="ch-kansverdelingen.html#eq:sem">(10.11)</a>. Je kunt deze standard error of the mean goed
beschouwen als de ‘foutmarge’ bij de schatting van het
populatiegemiddelde uit het steekproefgemiddelde.</p>
<p>Het bijzondere is nu, dat we niet 250 herhaalde willekeurige
steekproeven hoeven te trekken en te analyseren. We weten immers dat de
steekproefgemiddelden een normale kansverdeling hebben met
<span class="math inline">\(\mu_{\bar{X}} = \mu_X\)</span> en <span class="math inline">\(s_{\bar{X}} = \frac{s}{\sqrt{n}}\)</span>. De
kansverdeling van het gemiddelde kunnen we dus afleiden uit slechts één
steekproef van <span class="math inline">\(n\)</span> observaties, met één steekproefgemiddelde <span class="math inline">\(\bar{X}\)</span>
en één standaarddeviatie <span class="math inline">\(s\)</span> <span class="citation">(<a href="#ref-Cumm12">Cumming 2012</a>)</span>. Lees ook deze alinea nog eens
aandachtig door.</p>
</div>
<div id="sec:betrouwbaarheidsinterval-gemiddelde" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> Betrouwbaarheidsinterval van het gemiddelde<a href="ch-kansverdelingen.html#sec:betrouwbaarheidsinterval-gemiddelde" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Zoals hierboven uitgelegd, kunnen we het gemiddelde van de steekproef,
<span class="math inline">\(\bar{X}\)</span>, gebruiken als een goede schatting van het onbekende
gemiddelde in de populatie, <span class="math inline">\(\mu\)</span>. Op grond van het Centraal Limiet
Theorema (§<a href="ch-kansverdelingen.html#sec:CentraalLimietTheorema">10.6</a>) weten we ook dat de gemiddelden
van herhaalde steekproeven (van <span class="math inline">\(n\)</span> observaties) een normale verdeling
volgen: <span class="math inline">\(\mu_{\bar{X}} \sim \mathcal{N}(\mu_{X},\sigma/\sqrt{n})\)</span>, en
dus dat 95% van deze herhaalde steekproefgemiddelden zullen liggen
tussen <span class="math inline">\(\mu_{X}-1.96\sigma/\sqrt{n}\)</span> en <span class="math inline">\(\mu_{X}+1.96\sigma/\sqrt{n}\)</span>.
Dit interval wordt het 95%-betrouwbaarheidsinterval genoemd. We weten
met 95% betrouwbaarheid dat het populatiegemiddelde <span class="math inline">\(\mu\)</span> in dit
interval ligt — mits <span class="math inline">\(n\)</span> voldoende groot is, en mits de
standaarddeviatie, <span class="math inline">\(\sigma\)</span>, in de populatie bekend is.</p>
<p>Aan die laatste voorwaarde wordt in de praktijk echter zelden of nooit
voldaan. De standaarddeviatie in de populatie is doorgaans niet bekend,
en deze <span class="math inline">\(\sigma\)</span> wordt daarom ook geschat uit de steekproef. We
gebruiken de steekproef van <span class="math inline">\(n\)</span> observaties dus niet alleen om <span class="math inline">\(\mu_X\)</span>
te schatten, maar ook om <span class="math inline">\(\sigma_X\)</span> te schatten. We mogen dan het
betrouwbaarheidsinterval niet meer bepalen op grond van de
standaard-normale kansverdeling. In plaats daarvan gebruiken we een
aangepaste versie daarvan, de zgn. <span class="math inline">\(t\)</span>-verdeling
(Figuur <a href="ch-kansverdelingen.html#fig:tkansverdeling">10.7</a>). Deze kansverdeling van <span class="math inline">\(t\)</span> is iets
breder, d.w.z. met een iets lagere top en met iets dikkere staarten, dan
de standaard-normale kansverdeling van <span class="math inline">\(Z\)</span> in
Figuur <a href="ch-kansverdelingen.html#fig:normaalkansverdeling">10.3</a>.
De gedachte daarbij is dat de
schatting van <span class="math inline">\(\mu\)</span> wat onzekerder is (dus de kansverdeling is breder)
omdat niet alleen <span class="math inline">\(\mu\)</span> maar ook de standard error of the mean
(<span class="math inline">\(s/\sqrt{n}\)</span>) geschat wordt op grond van de steekproef. In allebei de
schattingen kunnen afwijkingen zitten, waardoor iets meer kans is om een
steekproefgemiddelde te vinden dat afwijkt van het populatiegemiddelde.
Zoals we al zagen wordt de schatting van <span class="math inline">\(\mu\)</span> beter naarmate <span class="math inline">\(n\)</span> groter
is: de <span class="math inline">\(t\)</span>-verdeling benadert dan de standaard-normale kansverdeling.</p>
<div class="figure"><span style="display:block;" id="fig:tkansverdeling"></span>
<img src="KMS-NL_files/figure-html/tkansverdeling-1.png" alt="Kansverdeling volgens de t-verdeling van een variabele $x$ met gemiddelde 0 en standaarddeviatie 1, voor n=600 en n=6." width="672" />
<p class="caption">
Figuur 10.7: Kansverdeling volgens de t-verdeling van een variabele <span class="math inline">\(x\)</span> met gemiddelde 0 en standaarddeviatie 1, voor n=600 en n=6.
</p>
</div>
<p>Voor de <span class="math inline">\(t\)</span>-verdeling moeten we dus weten hoe groot de steekproef was;
deze <span class="math inline">\(n\)</span> bepaalt immers de precieze kansverdeling van <span class="math inline">\(t\)</span>, en daarmee de
kritieke waarde <span class="math inline">\(t*\)</span>. We gaan daar nader op in in
§<a href="ch-toetsing.html#sec:ttoets-vrijheidsgraden">13.2.1</a>. We volstaan hier met een
uitgewerkt voorbeeld.</p>
<hr />
<blockquote>
<p><em>Voorbeeld 10.11:</em>
Soms wil een onderzoeker weten hoe snel het Nederlands eigenlijk
gesproken wordt, en hoe groot de variatie tussen sprekers is in deze
spreeksnelheid. Deze variabele, spreeksnelheid, wordt uitgedrukt als het
aantal seconden dat een lettergreep duurt (meestal <span class="math inline">\(&lt;1\)</span> seconde). Hoewel <span class="citation">(<a href="#ref-Quene08">Quené 2008</a>)</span>
schat dat <span class="math inline">\(\mu=0.220\)</span> s en <span class="math inline">\(\sigma=0.0225\)</span> s, doen we alsof we deze
populatieparameters niet kennen — net als echte onderzoekers, die deze
populatieparameters meestal ook niet kennen.</p>
</blockquote>
<blockquote>
<p>Voor een steekproef van <span class="math inline">\(n=30\)</span> sprekers vinden we <span class="math inline">\(\bar{x}=0.215\)</span> en
<span class="math inline">\(s=0.0203\)</span> seconden. Daaruit schatten<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a> we <span class="math inline">\(\hat{\mu}=0.215\)</span> en
<span class="math inline">\(\hat{\sigma}=0.0203\)</span>. Omdat <span class="math inline">\(\sigma\)</span> niet bekend is, gebruiken we de
<span class="math inline">\(t\)</span>-verdeling om het betrouwbaarheidsinterval te bepalen. We gebruiken
de <span class="math inline">\(t\)</span>-verdeling voor <span class="math inline">\(n=30\)</span> en vinden een kritieke waarde <span class="math inline">\(t^*=2.05\)</span>
(zie
Bijlage <a href="app-kritieketwaarden.html#app-kritieketwaarden">C</a>, voor <span class="math inline">\(B=95\)</span>%).
Volgens
formule <a href="ch-kansverdelingen.html#eq:t-onesampleCI">(10.12)</a> weten we dan met 95% betrouwbaarheid dat het onbekende populatiegemiddelde <span class="math inline">\(\mu\)</span> ligt tussen
<span class="math inline">\(\bar{x}-2.05\times s_{\bar{x}}\)</span> en <span class="math inline">\(\bar{x}+2.05\times s_{\bar{x}}\)</span>,
oftewel tussen <span class="math inline">\(0.215-2.05\times0.0037\)</span> en <span class="math inline">\(0.215+2.05\times0.0037\)</span>,
oftewel tussen <span class="math inline">\(0.208\)</span> en <span class="math inline">\(0.223\)</span> seconde
Als de werkelijke waarde in de populatie tussen deze grenzen ligt, dan is er een kans van 95% om dit gemiddelde te vinden in een aselecte steekproef <span class="citation">(<a href="#ref-Spie19">Spiegelhalter 2019, 241</a>)</span>.</p>
</blockquote>
<hr />
<p>In Figuur <a href="ch-kansverdelingen.html#fig:tempo95CIs">10.8</a> zie je de resultaten van een
computer-simulatie om dit te illustreren. We hebben <span class="math inline">\(100\times\)</span>
denkbeeldige steekproeven getrokken van <span class="math inline">\(n=30\)</span> moedertaalsprekers van
het Standaard Nederlands, en de spreeksnelheid vastgesteld van deze
sprekers. Voor elke steekproef hebben we het 95%
betrouwbaarheidsinterval getekend. Voor 95 van de 100 steekproeven valt
het populatiegemiddelde <span class="math inline">\(\mu=0.220\)</span> inderdaad binnen het interval, maar
voor 5 van de 100 steekproeven ten onrechte niet (deze zijn gemarkeerd
langs de rechterkant).</p>
<div class="figure"><span style="display:block;" id="fig:tempo95CIs"></span>
<img src="KMS-NL_files/figure-html/tempo95CIs-1.png" alt="95%-Betrouwbaarheidsintervallen en steekproefgemiddelden, over 100 gesimuleerde steekproeven (n=30) uit een populatie met gemiddelde 0.220 en s.d. 0.0225; zie tekst." width="672" />
<p class="caption">
Figuur 10.8: 95%-Betrouwbaarheidsintervallen en steekproefgemiddelden, over 100 gesimuleerde steekproeven (n=30) uit een populatie met gemiddelde 0.220 en s.d. 0.0225; zie tekst.
</p>
</div>
<div id="formules-2" class="section level3 hasAnchor" number="10.7.1">
<h3><span class="header-section-number">10.7.1</span> formules<a href="ch-kansverdelingen.html#formules-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Het tweezijdige <span class="math inline">\(B\)</span>% betrouwbaarheidsinterval voor het
populatie-gemiddelde is
<span class="math display" id="eq:t-onesampleCI">\[\begin{equation}
  \bar{X} \pm t^*_{n-1} \times \frac{s}{\sqrt{n}}
  \tag{10.12}
\end{equation}\]</span>
waarbij <span class="math inline">\(t^*\)</span> met <span class="math inline">\(n-1\)</span> vrijheidsgraden gevonden wordt met behulp van
Bijlage <a href="app-kritieketwaarden.html#app-kritieketwaarden">C</a>, zie
§<a href="ch-toetsing.html#sec:ttoets-vrijheidsgraden">13.2.1</a> voor meer uitleg hierover.</p>

</div>
</div>
</div>
<h3>Referenties<a href="referenties.html#referenties" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-Bhar13" class="csl-entry">
Bhargava, Saurabh, and Vikram Pathania. 2013. <span>“Driving Under the (Cellular) Influence.”</span> <em>American Economic Journal: Economic Policy</em> 5 (3): 92–125.
</div>
<div id="ref-Cumm12" class="csl-entry">
Cumming, Geoff. 2012. <em>Understanding the New Statistics</em>. New York: Routledge.
</div>
<div id="ref-Quene08" class="csl-entry">
Quené, Hugo. 2008. <span>“Multilevel Modeling of Between-Speaker and Within-Speaker Variation in Spontaneous Speech Tempo.”</span> <em>Journal of the Acoustical Society of America</em> 123 (2): 1104–13.
</div>
<div id="ref-SK01" class="csl-entry">
Schuurman, Wouter, and Hans De Kluiver. 2001. <em>Kop of Munt: Kansrekening in Het Dagelijks Leven</em>. Amsterdam: Bert Bakker.
</div>
<div id="ref-Spie19" class="csl-entry">
Spiegelhalter, David. 2019. <em>The Art of Statistics: Learning from Data</em>. Pelican.
</div>
<div id="ref-Weis15" class="csl-entry">
Weisstein, Eric W. 2015. <span>“Pascal’s Formula.”</span> Wolfram. <a href="http://mathworld.wolfram.com/PascalsFormula.html">http://mathworld.wolfram.com/PascalsFormula.html</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="19">
<li id="fn19"><p>Twee van de fiches zijn echter zonder letter; later in deze paragraaf zullen we deze blanco fiches verwijderen uit het zakje.<a href="ch-kansverdelingen.html#fnref19" class="footnote-back">↩︎</a></p></li>
<li id="fn20"><p>Roulettespelers kunnen gokken op 36 van de 37 mogelijke uitkomsten, dus op de lange termijn ontvangt het casino <span class="math inline">\(1/37\)</span> deel van alle inzetten.<a href="ch-kansverdelingen.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>Dus <span class="math inline">\({n \choose x} = {n-1 \choose x} + {n-1 \choose x-1}\)</span>, <span class="citation">(<a href="#ref-Weis15">Weisstein 2015</a>)</span>.<a href="ch-kansverdelingen.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>Schattingen van parameters worden aangegeven met een “dakje” erboven.<a href="ch-kansverdelingen.html#fnref22" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch-centrumenspreiding.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch-samenhang.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/h10kansverdelingen.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["KMS-NL.pdf", "KMS-NL.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
